#if PARDISO

! Stokes problem on a cubic domain with a sphere at the center.
! A force and/or torque is applied on the particle.
! Gmsh mesh.
! Interfacial slip on the particle boundary.

program stokes43

  use tfem_m
  use pardiso_m
  use stokes_elements_m
  use io_utils_m
  use subs43_m
  use limits_m

  implicit none

  integer, parameter :: &
    uintpl = 6,     &  ! P2 velocities
    pintpl = 2,     &  ! P1 pressures
    physqvel = 1,   &  ! physical quantity nr of the velocities
    physqpress = 2, &  ! physical quantity nr of the pressures
    gauss = 15,     &  ! 15-point integration of tetrahedra
    gaussb = 6         ! 6-point integration of triangles

! definitions

  type(mesh_t) :: mesh, mesh_ext, mesh_int
  type(input_probdef_t) :: input_probdef
  type(problem_t) :: problem
  type(sysmatrix_t) :: sysmatrix
  type(sysvector_t):: sol
  type(sysvector_t) :: rhsd
  type(coefficients_t) :: coefficients
  type(solver_options_pardiso_t) :: solver_options_pardiso

! variables

  real(dp) :: &
    eta = 1.0_dp,          & ! solvent viscosity
    eta_slip = 0.1_dp        ! slip parameter

  integer ::  presnod(4) = [1,3,5,10]
  real(dp) :: up(6)
  logical :: impose_iterative_refinement = .false.

! shut off warning message
  WARN_ON_TEST_FOR_MULTIPLE_SIDELEM = .false.

! fill coefficients
  call create_coefficients ( coefficients, ncoefi=600, ncoefr=501 )

  coefficients%i(1:11) = &
    [ uintpl,   pintpl,     0,     0,         0,  &
       physqvel, physqpress, 0,     0,     gauss,  &
       gaussb ]
  coefficients%i(12:) = 0
  coefficients%r(1) = eta
  coefficients%r(2:) = 0
  coefficients%r(501) = eta_slip

  force = [ 1.0_dp, 0.0_dp, 0.0_dp ]
  torque = [ 0.0_dp, 0.0_dp, 0.0_dp ]

! read mesh generated by gmsh
  call read_mesh_gmsh ( mesh_ext, filename='mesh43.msh', ndim=3, &
    physgeom=.true. )

! create particle mesh from surface=7
  call mesh_convert ( mesh_ext, mesh_int, from_surface=7 )

! merge the fluid and particle meshes
  call mesh_merge ( mesh_ext, mesh_int, mesh, nogroupmerge=.true. )

! add a new surface given by the particle mesh
  call add_to_mesh ( mesh, surfacefromgroups=[2] )

  call delete ( mesh_ext, mesh_int )

  call fill_mesh_parts ( mesh )

! problem definition
  call create_input_probdef ( mesh, input_probdef, nvec=4, nphysq=2 )

! group 1
  input_probdef%vec_elementdof(1)%a(:,1) = 3  ! velocity
  input_probdef%vec_elementdof(1)%a(:,2) = 0
  input_probdef%vec_elementdof(1)%a(presnod,2) = 1  ! pressure
  input_probdef%vec_elementdof(1)%a(:,3) = 1  ! scalar
  input_probdef%vec_elementdof(1)%a(:,4) = 6  ! tensor

! group 2 (only velocities)
  input_probdef%vec_elementdof(2)%a(:,1) = 3  ! velocity
  input_probdef%vec_elementdof(2)%a(:,2) = 0
  input_probdef%vec_elementdof(2)%a(:,3) = 0  ! scalar
  input_probdef%vec_elementdof(2)%a(:,4) = 0  ! tensor

  input_probdef%physq = [1,2]
  input_probdef%probnr = 1

! cell boundaries
  call define_essential ( mesh, input_probdef, surface1=1, surface2=6, &
    physq=physqvel )
  call define_essential ( mesh, input_probdef, point=1, physq=physqpress )

! define constraint on the disk: rigid-body motion
  call define_constraint ( mesh, input_probdef, surface1=8, physq=physqvel, &
    discretization='collocation', nodedof=3, naddunknowns=6 )

! normal velocity coupling
  call define_constraint ( mesh, input_probdef, physq=physqvel, &
    surface1=7, surface2=8, discretization='weak', elementdof=[1,1,1,1,1,1] )

! connection: interfacial slip
  call define_connection ( mesh, input_probdef, surface1=7, surface2=8, &
    discretization='weak', physq=physqvel )

  call problem_definition ( input_probdef, mesh, problem )

! create system vectors (solution and right-hand side)
  call create_sysvector ( problem, sol, rhsd )

! cell boundaries
  call fill_sysvector ( mesh, problem, sol, surface1=1, surface2=6, &
    physq=physqvel, degfd=1, value=0.0_dp )
  call fill_sysvector ( mesh, problem, sol, surface1=1, surface2=6, &
    physq=physqvel, degfd=2, value=0.0_dp )
  call fill_sysvector ( mesh, problem, sol, surface1=1, surface2=6, &
    physq=physqvel, degfd=3, value=0.0_dp )

  call fill_sysvector ( mesh, problem, sol, point=1, physq=physqpress, &
    value=0._dp )

! create system matrix
  call create_sysmatrix_structure_base ( sysmatrix, mesh, problem, &
    symmetric=.true. )
  call create_sysmatrix_structure_constraint ( sysmatrix, mesh, problem, &
     diagonal=.true. )
  call create_sysmatrix_structure_connection ( sysmatrix, mesh, problem )
  call finalize_sysmatrix_structure ( sysmatrix )

  call create_sysmatrix_data ( sysmatrix )

! build (assemble) matrix and vector from elements
  call build_system ( mesh, problem, sysmatrix, rhsd, elemsub=stokes_elem, &
    coefficients=coefficients, elgroup1=1 )

! fill the matrix and vector for group 2 by zeros
  call build_system ( mesh, problem, sysmatrix, rhsd, &
    coefficients=coefficients, elgroup1=2, zeromatvec=.true., addmatvec=.true. )

! rigid-body motion
  call build_system_constraint ( mesh, problem, sysmatrix, rhsd, &
    constraint1=1, elemsub=elementc, coefficients=coefficients, &
    addmatvec=.true., diagonal=.true. )

! coupling of normal velocities
  call build_system_constraint ( mesh, problem, sysmatrix, rhsd, &
    constraint1=2, elemsub=stokes_constr_normal_vel, &
    coefficients=coefficients, addmatvec=.true., diagonal=.true. )

! interfacial slip
  call build_system_connection ( mesh, problem, sysmatrix, rhsd, &
    elemsub=elementcn, coefficients=coefficients, addmatvec=.true. )

  call add_effect_of_essential_to_rhs ( problem, sysmatrix, sol, rhsd )

! solve gradient/velocity/pressure problem
  solver_options_pardiso%matrixtype=-2
  if ( impose_iterative_refinement ) then
    solver_options_pardiso%niter_ref=10
    solver_options_pardiso%printlevel=4
  end if
  call solve_system_pardiso ( sysmatrix, rhsd, sol, &
    solver_options=solver_options_pardiso  )

  call delete_sysmatrix ( sysmatrix )

! get velocity
  call get_sysvector_constraint ( mesh, problem, sol, constraint=1, &
    addunknowns=.true., u=up )

  write ( *, '(1X,A,3F10.6)' ) 'velocity = ', up(1:3)
  write ( *, '(1X,A,3F10.6)' ) 'omega = ', up(4:6)

! Output velocity to vtk

  call write_vector_vtk ( mesh, problem, filename='stokes43.vtk', &
    dataname='velocity_vector', sysvector=sol, physq=1 )

! clear memory

  call delete ( mesh )
  call delete ( input_probdef )
  call delete ( problem )
  call delete ( sol, rhsd )
  call delete ( coefficients )

end program stokes43

#else
  print '(3(a/),a)', &
    'To run this example:', &
    ' - compile add-on pardiso', &
    ' - add the MKL library for linking with pardiso', &
    ' - set preprocessing macro PARDISO in Mdefs.mk'
end
#endif

