#!/bin/sh
                                                                                
# difres : generate difference of results for testprograms

function helptext ()
{
  echo "Usage: difres [OPTIONS] [program(s)]"
  echo "Show difference of results for given or all test programs"
  echo
  echo "Options:   (Description)"
  echo "   -c compiler  compare to the given compiler directory."
  echo "   -d results_compiler  compare output to the results of the given compiler"
  echo "                        specified by the directory of results"
  echo "                Compilers available:"
  ls | grep results_ | cut -c9- | sed "s/^/\t\t\t/" \
     | sed "/nagfor_macos/s/$/ (default)/"
  echo "   -h           this text is shown "
}

# get options

dir=results_nagfor_macos_arm64

while getopts c:d:h optvar; do
  case "$optvar"
  in
     c) dir="results_"$OPTARG ;;
     d) dir=$OPTARG ;;
     h) helptext ; exit ;;
     "?") helptext ; exit 1 ;;
 esac
done

shift `expr $OPTIND - 1`

if [ ! -d $dir ]; then
  echo $dir: compiler directory unknown
  exit 1
fi

if [ -f testresult ]; then
   rm testresult
fi

if [ $# -ge 1 ]
then
   src="$*"
else
   src="*.f90"
fi

programs=

for file in $src
do
   base=`basename $file .f90`
   grep "end program" $file >/dev/null
   if [ $? == 0 ]; then
     programs=$programs" $base"
   fi
done

for prog in $programs
do
   if [ -f $prog.res ]; then
      diff $dir/$prog.res $prog.res >$prog.dif
      if [ -s $prog.dif ]
      then
         echo "$prog different" >> testresult
      else
         echo "$prog OK" >> testresult
      fi
   fi
done
