! Viscoelastic problem:
! Oscillating Couette flow with a freely floating solid particle
! DEVSS-G/SUPG
! Implicit bilinear terms of CE in momentum balance.
! Particle updater uses a second-order AB2 scheme.
! second-order time integration
! ALE body-fitting mesh scheme
! Periodic velocities/conformation tensor using collocation on curves
! Mesh generated by Gmsh using triangles
! Remeshing is performed when the maximum normalized area or aspect ratio
! of the mesh elements is higher than a threshold.
! After remeshing, the field variables from previous time steps are obtained
! on the current mesh by solving a projection problem.
! Note: the coordinates of the old (discarded) mesh at previous time steps
! are projected onto the new (remeshed) mesh to obtain the new mesh at
! previous time steps. This is necessary to find the new mesh velocity.
! Note2: if the log transformation method is used, a projection problem
! is solved at each time step to find the L2-projection of c=exp(s).


program ale12

  use tfem_m
  use hsl_ma41_m
  use hsl_ma57_m
  use stokes_elements_m
  use viscoelastic_elements_m
  use io_utils_m
  use figplot_m
  use subs9_m
  use update_mesh_nodes9_m
  use projection_elements_m

  implicit none


! constants

  integer, parameter :: &
    uintpl = 6,       & ! P2 velocities
    pintpl = 2,       & ! P1 pressures
    gintpl = 2,       & ! P1 gradients
    cintpl = 2,       & ! P1 conformation
    physqgrad = 1,    & ! physical quantity nr of the gradients
    physqvel = 2,     & ! physical quantity nr of the velocities
    physqpress = 3,   & ! physical quantity nr of the pressures
    gauss = 6,        & ! 6-point Gauss integration of triangles
    gaussb = 3,       & ! 3-point integration of boundary elements
    gauss_proj = 6,   & ! integration rule for the projection problem
    inttype_proj = 3, & ! standard Gauss-Legendre (numerical table)
    ncompc = 3,       & ! number of conformation tensor components
    nmodes = 1,       & ! number of modes
    startm = 501,     & ! start of material model data
    coorsys = 0,      & ! coordinate system
    model = 3,        & ! Giesekus model
    vtkevery = 1,     & ! vtk file every vtkevery steps. -1: means none
    ncompv_P2 = 4,    & ! number of components for P2 projection:
                        ! x,y-coordinates at n and n-1
    ncompv_P1 = 6,    & ! number of components for P1 projection:
                        ! conformation components at n and n-1
    numtimesteps = 50   ! number of time steps

  logical, parameter :: check_projection = .false. ! write vtks before and after
                                                   ! the projection


! variables

  integer :: &
    timeint1 = 1,       & ! first-order, semi-implicit Euler
    timeint2 = 7,       & ! second-order, semi-implicit Gear/Karniadakis with
                          ! conformation prediction
    logc = 1              ! standard scheme or log transformation

  real(dp) :: &
    eta_s = 0.1_dp,     & ! solvent viscosity
    eta_p = 1.0_dp,     & ! polymer viscosity
    lambda = 1.0_dp,    & ! relaxation time
    mobility = 0.2_dp,  & ! mobility parameter in the Giesekus model (alpha)
    amp = 1.0_dp,       & ! amplitude of the imposed sinusoidal shear rate
    freq = 0.5_dp,      & ! frequency of the imposed sinusoidal shear rate
    time = 0.0_dp,      & ! initial time
    deltat = 0.02_dp,   & ! time step
    beta = 1.0_dp,      & ! upwinding parameter in the SUPG method
    dx_box = 0.1_dp,    & ! element spacing on the external boundaries
    dx_part = 0.02_dp,  & ! element spacing on the particle boundary
    rs_gup = 1.4_dp,    & ! real_storage gradient-velocity-pressure LU (HSL)
    is_gup = 1.5_dp,    & ! integer_storage gradient-velocity-pressure LU (HSL)
    rs_c  = 1.4_dp,     & ! real_storage for the conformation LU (HSL)
    is_c  = 1.6_dp,     & ! integer_storage for conformation LU (HSL)
    area_threshold = 0.1_dp,        & ! remeshing area threshold
    aspect_ratio_threshold = 0.1_dp   ! remeshing aspect ratio threshold


! definitions for ve and upg problems

  type(mesh_t) :: mesh_np1
  type(input_probdef_t) :: input_probdef, input_probdefc, input_probdefc_projc
  type(problem_t), target :: problem, problemc, problemc_projc
  type(sysmatrix_t) :: sysmatrix, sysmatrixc, sysmatrixc_projc
  type(sysvector_t), target :: sol_np1, sol_n, sol_nm1
  type(sysvector_t) :: rhsd
  type(oldvectors_t) :: oldvectors_ve
  type(coefficients_t) :: coefficients
  type(sysvector_t), dimension(ncompc,nmodes), target :: solc_np1, solc_n
  type(sysvector_t), dimension(ncompc,nmodes), target :: solc_nm1, rhsc
  type(sysvector_t), dimension(ncompc,nmodes), target :: solc_projc, rhsc_projc
  type(lu_ma41_t) :: luc
  type(lu_ma57_t) :: lu_exps_projc
  type(plot_options_t) :: plot_options
  type(solver_options_ma41_t) :: solver_options_ma41
  type(vector_t), target :: meshvel_np1
  type(subscript_t) :: velx, vely
  type(problem_t) :: problem_lapl


! temp definitions used to store old definitions before projection

  type(mesh_t), target :: mesh_np1_temp
  type(sysvector_t), dimension(ncompc,nmodes) :: solc_n_temp, solc_nm1_temp
  type(sysvector_t) :: sol_n_temp, sol_nm1_temp
  type(vector_t) :: coords_n_temp, coords_nm1_temp
  type(problem_t), target :: problem_temp, problemc_temp


! variables

  integer :: i, step=0, ipost=0

  real(dp) :: ox, oy, lx, ly, vel_lower_wall, vel_upper_wall
  real(dp) :: up(3), unm1(3), un(3), pp(3), ppn(3)

  real(dp), dimension(:), allocatable :: init_area, areav
  real(dp), dimension(:), allocatable :: init_aspect_ratio, aspect_ratio
  real(dp), allocatable, dimension(:,:) :: meshcoor_n, meshcoor_nm1, &
    meshcoor_temp
  real(dp) :: norm_area, norm_aspect_ratio

  character(len=30) :: filename
  logical :: remeshing=.false.

  real(dp) :: alpha, G


  open (unit = 100, file='output.out')


! set some parameters

  alpha = eta_p         ! DEVSS parameter
  G = eta_p / lambda    ! modulus


! fill coefficients

  call create_coefficients ( coefficients, ncoefi=150, ncoefr=500+3*nmodes )

  coefficients%i = &
    [ uintpl,   pintpl,     0,     0,         gintpl, &
      physqvel, physqpress, 0,     physqgrad, gauss,  &
      gaussb,   cintpl,     0,     0,         0,      &
      0,        0,          model, nmodes,    startm, &
      logc,     timeint1,    coorsys, ( 0, i = 24, 150 )  &
    ]

  coefficients%i(48) = 1 ! use mesh velocity for ALE formulation
  coefficients%i(49) = 1  ! exp(s) projection =.true. for logc=1

  coefficients%r(1:502) = &
    [ eta_s,    0._dp,   0._dp,   alpha, 0._dp, &
      0._dp, 0._dp,  deltat,   beta,  0._dp, &
      ( 0._dp, i = 11, 500 ), &
      G,     lambda  &
    ]

  if ( model == 3 ) then
    coefficients%r(503) = mobility
  end if


! mesh parameters

  ox = -1.0_dp
  oy = -0.5_dp
  lx =  2.0_dp
  ly =  1.0_dp


! one particle

  rp = 0.1_dp          ! particle radius
  xp(1,1) = 0.0_dp       ! x-position of the particle
  xp(1,2) = 0.1_dp       ! y-position of the particle

  pp(1) = xp(1,1)
  pp(2) = xp(1,2)
  pp(3) =  0._dp  ! initial rotation angle

  call generate_read_mesh


! plot mesh

  plot_options%fontsize = 6
  call plot_points_curves ( plot_options, mesh_np1, 'curves.fig' )
  plot_options%fontsize = 10
  call plot_mesh ( plot_options, mesh_np1, 'mesh.fig' )


! define the upg and ve problem, create (sys)vectors, subscripts, oldvectors
! and initialize sysvectors

  call define_problems_create_vectors


! initialize vectors with zero stress

  if ( logc == 0 ) then ! standard
    solc_np1(1,1)%u = 1   ! initial cxx
    solc_np1(2,1)%u = 0   ! initial cxy
    solc_np1(3,1)%u = 1   ! initial cyy
  else if ( logc == 1 ) then ! log scheme
    solc_np1(1,1)%u = 0   ! initial sxx
    solc_np1(2,1)%u = 0   ! initial sxy
    solc_np1(3,1)%u = 0   ! initial syy
  end if


! solve upG problem without the divtau term

  call build_solve_upG


! extract info on particle

  call get_sysvector_constraint ( mesh_np1, problem, sol_np1, constraint=1, &
    addunknowns=.true., u=up )

  write ( *, '(1X,A)' ) '****************************************'
  write ( *, '(1X,A,I0)' ) 'step = ', step
  write ( *, '(1X,A,3F10.6)' ) 'pp = ', pp
  write ( *, '(1X,A,3F10.6)' ) 'up = ', up
  write ( *, '(1X,A,F10.6)' )  'normalized area = ', norm_area
  write ( *, '(1X,A,F10.6)' )  'normalized aspect ratio = ', norm_aspect_ratio
  write ( *,* )

  write(100, '(i5,7es16.8)') step, time, pp, up


! write VTK files

  call postprocessing ( mesh_np1, sol_np1, solc_np1, ipost=ipost )
  ipost = ipost + 1


! copy old values

  call copy ( sol_np1, sol_n )
  call copy ( solc_np1, solc_n )
  meshcoor_n = mesh_np1%coor


! start time integration

  time = 0

  do step = 1, numtimesteps

    time = time + deltat
    if ( step > 1 ) coefficients%i(22) = timeint2

    if ( step == 1 ) then

!     advance with forward Euler
      un = up
      ppn = pp
      pp = pp + deltat * un

    else

!     advance particle position with 2nd order Adams-Bashforth
      unm1 = un
      un = up
      ppn = pp
      pp = pp + deltat*(3*un/2 - unm1/2)

    end if

    xp(1,1:2) = pp(1:2)


!   update mesh nodes: solve a Laplace's equation

    call update_mesh_nodes ( mesh_np1, problem_lapl, pp(1:2)-ppn(1:2) )

    call find_bounds_blocks ( mesh_np1 )


!   compute current aspect ratio

    call compute_element_aspect_ratio ( mesh_np1, areav, aspect_ratio )


!   compute maximum normalized aspect ratio and area
!   (with respect to the initial values)

    norm_area = maxval( abs(log(areav/init_area)) )
    norm_aspect_ratio = maxval( abs(log(aspect_ratio/init_aspect_ratio)) )


!   remeshing criterion

    remeshing = .false.

    if ( ( norm_area >= area_threshold .or. &
           norm_aspect_ratio >= aspect_ratio_threshold ) .and. &
           step /= numtimesteps ) then
      remeshing = .true.
    end if


    if ( remeshing ) then

      print *,'Remeshing and projection...'


!     check the projection (use mesh_np1 with the coordinates at the previous
!     time steps)

      if ( check_projection ) then
        allocate ( meshcoor_temp(mesh_np1%nnodes, mesh_np1%ndim) )
        meshcoor_temp = mesh_np1%coor
        mesh_np1%coor = meshcoor_n
        call postprocessing ( mesh_np1, sol_n, solc_n, check_proj='n_pre_proj' )
        mesh_np1%coor = meshcoor_nm1
        call postprocessing ( mesh_np1, sol_nm1, solc_nm1, &
          check_proj='nm1_pre_proj' )
        mesh_np1%coor = meshcoor_temp
        deallocate ( meshcoor_temp )
      end if


!     create vectors to store the mesh coordinates, these coordinates will
!     be used in the projection problem to find the new mesh at t_n and t_nm1

      call create ( problem, coords_n_temp, vec=2 )
      call create ( problem, coords_nm1_temp, vec=2 )

      coords_n_temp%u = reshape ( transpose ( meshcoor_n ), [size(meshcoor_n)] )
      coords_nm1_temp%u = reshape ( transpose ( meshcoor_nm1 ), &
                                    [size(meshcoor_nm1)] )


!     copy current definitions to temporary definitions used for the projection
!     problem

      call copy ( mesh_np1, mesh_np1_temp )
      call fill_mesh_parts ( mesh_np1_temp )
      call copy ( solc_n, solc_n_temp )
      call copy ( sol_n, sol_n_temp )
      call copy ( solc_nm1, solc_nm1_temp )
      call copy ( sol_nm1, sol_nm1_temp )
      call problem_definition ( input_probdef, mesh_np1, problem_temp )
      call problem_definition ( input_probdefc, mesh_np1, problemc_temp )


!     delete the old problems

      call delete_old_problems


!     generate new mesh

      call generate_read_mesh


!     define the upg and ve problem, create (sys)vectors, subscripts, oldvectors
!     and initialize sysvectors

      call define_problems_create_vectors


!     project the old solutions onto the new mesh and fill in the values

      call project_old_solutions_P2
      call project_old_solutions_P1


!     check the projection (use mesh_np1 with the coordinates at the previous
!     time steps)

      if ( check_projection ) then
        allocate ( meshcoor_temp(mesh_np1%nnodes, mesh_np1%ndim) )
        meshcoor_temp = mesh_np1%coor
        mesh_np1%coor = meshcoor_n
        call postprocessing ( mesh_np1, sol_n, solc_n, &
          check_proj='n_post_proj' )
        mesh_np1%coor = meshcoor_nm1
        call postprocessing ( mesh_np1, sol_nm1, solc_nm1, &
          check_proj='nm1_post_proj' )
        mesh_np1%coor = meshcoor_temp
        deallocate ( meshcoor_temp )
      end if


!     delete the temporary definitions

      call delete ( coords_n_temp, coords_nm1_temp )
      call delete ( mesh_np1_temp )
      call delete ( solc_n_temp )
      call delete ( sol_n_temp )
      call delete ( solc_nm1_temp )
      call delete ( sol_nm1_temp )
      call delete ( problemc_temp )
      call delete ( problem_temp )


    end if


!   find the mesh velocity using a backwards differencing scheme

    if ( step == 1  ) then
      meshvel_np1%u = reshape ( transpose ( ( mesh_np1%coor - meshcoor_n ) / &
                                     deltat ), [mesh_np1%ndim*mesh_np1%nnodes] )
    else
      meshvel_np1%u = reshape ( transpose ( &
        ( 1.5_dp*mesh_np1%coor - 2*meshcoor_n + 0.5_dp*meshcoor_nm1 ) / &
                                     deltat ), [mesh_np1%ndim*mesh_np1%nnodes] )
    end if


!   build and solve the upG system

    call build_solve_upG


!   copy old value (already here, so sol_np1 is used in the VE problem!)

    call copy ( sol_n, sol_nm1 )
    call copy ( sol_np1, sol_n )


!   build and solve the conformation problem

    call build_solve_ve


!   extract info on particle

    call get_sysvector_constraint ( mesh_np1, problem, sol_np1, constraint=1, &
      addunknowns=.true., u=up )

    write ( *, '(1X,A)' ) '****************************************'
    write ( *, '(1X,A,I0)' ) 'step = ', step
    write ( *, '(1X,A,3F10.6)' ) 'pp = ', pp
    write ( *, '(1X,A,3F10.6)' ) 'up = ', up
    write ( *, '(1X,A,F10.6)' )  'normalized area = ', norm_area
    write ( *, '(1X,A,F10.6)' )  'normalized aspect ratio = ', norm_aspect_ratio
    write ( *,* )

    write(100, '(i5,7es16.8)') step, time, pp, up


!   write VTK files

    if ( vtkevery > 0 ) then
      if ( mod(step,vtkevery) == 0 ) then
        call postprocessing ( mesh_np1, sol_np1, solc_np1, ipost=ipost )
        ipost = ipost + 1
      end if
    end if


!   copy old values
!   note: sol is already copied in the time integration loop)

    call copy ( solc_n, solc_nm1 )
    call copy ( solc_np1, solc_n )
    meshcoor_nm1 = meshcoor_n
    meshcoor_n = mesh_np1%coor


  end do


  close(unit=100)


! delete all data including all allocated memory

  call delete_old_problems


contains


! generate and read mesh

  subroutine generate_read_mesh

    call write_gmsh_parameters ( ox, oy, lx, ly, xp, rp, dx_box, dx_part )

    call execute_command_line ( 'gmsh -2 -order 2 -algo front2d -o mesh.msh &
                  &mesh.geo > outputmesh.out' )

!   read mesh generated by gmsh
    call read_mesh_gmsh ( mesh_np1, filename='mesh.msh', ndim=2, &
      physgeom=.true. )

    call add_to_mesh ( mesh_np1, curve=[-4] )     ! curve 6

    call fill_mesh_parts ( mesh_np1 )

!   allocate aspect ratio arrays
    allocate ( init_area(mesh_np1%nelem), areav(mesh_np1%nelem) )
    allocate ( init_aspect_ratio(mesh_np1%nelem), aspect_ratio(mesh_np1%nelem) )

!   define some arrays for the ALE mesh position at old times
    allocate ( meshcoor_n(mesh_np1%nnodes,mesh_np1%ndim), &
      meshcoor_nm1(mesh_np1%nnodes,mesh_np1%ndim) )

!   compute initial element aspect ratio
    call compute_element_aspect_ratio ( mesh_np1, init_area, init_aspect_ratio )

    norm_area = 0.0_dp
    norm_aspect_ratio = 0.0_dp

    call write_mesh_vtk ( mesh_np1, filename='mesh.vtk' )

  end subroutine generate_read_mesh


! compute the aspect ratio and area for each mesh element

  subroutine compute_element_aspect_ratio ( mesh, area, asp_ratio )

    type(mesh_t), intent(in) :: mesh
    real(dp), dimension(:), intent(out) :: asp_ratio, area

    integer, parameter :: elgrp=1
    integer :: elem, node(3)
    real(dp) :: la, lb, lc, sper
    real(dp) :: vert(3,2)

    do elem = 1,mesh%nelem

!     get coordinates of triangle vertices (local node numbers: 1, 3, 5)
      node = [1,3,5]
      vert = mesh%coor(mesh%topology(elgrp)%a(node,elem),:)

!     compute side lengths
      la = sqrt( (vert(1,1) - vert(2,1))**2 + (vert(1,2) - vert(2,2))**2 )
      lb = sqrt( (vert(2,1) - vert(3,1))**2 + (vert(2,2) - vert(3,2))**2 )
      lc = sqrt( (vert(3,1) - vert(1,1))**2 + (vert(3,2) - vert(1,2))**2 )

!     compute triangle semiperimeter and area
      sper = (la + lb + lc)/2.0_dp
      area(elem) = sqrt( sper*(sper - la)*(sper - lb)*(sper - lc) )

!     compute aspect ratio
      asp_ratio(elem) = max(la,lb,lc)**2/area(elem)

    end do

  end subroutine compute_element_aspect_ratio


! write the parameters in gmsh format

  subroutine write_gmsh_parameters ( ox, oy, lx, ly, xp, rp, dx_box, dx_part )

    real(dp), intent(in) :: ox, oy, lx, ly, xp(:,:), rp(:), dx_box, dx_part

    integer :: i, nobj

    nobj = size(rp)

    open ( unit=25, file='mesh.geo' )

    write ( 25, '(1X,A,F18.14,A)' ) 'ox = ', ox, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'oy = ', oy, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'lx = ', lx, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'ly = ', ly, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'dx_box = ', dx_box, ';'
    write ( 25, '(1X,A,I0,A)' ) 'nobj = ', nobj, ';'

    do i = 1, nobj
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'xp[', i, '] = ', xp(i,1), ';'
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'yp[', i, '] = ', xp(i,2), ';'
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'rp[', i, '] = ', rp(i), ';'
    end do

    write ( 25, '(1X,A,F18.14,A)' ) 'dx_part = ', dx_part, ';'

    write ( 25, '(/1x,a)' ) 'Include "particles_in_a_box_2D.igo";'

    close ( 25 )

  end subroutine write_gmsh_parameters


! start the problems

  subroutine define_problems_create_vectors

!   problem definition of gradient/velocity/pressure
    call create_input_probdef ( mesh_np1, input_probdef, nvec=6, nphysq=3 )

    input_probdef%vec_elementdof(1)%a =   &
        reshape ( [ 4,0,4,0,4,0,    &  ! G
                    2,2,2,2,2,2,    &  ! velocity
                    1,0,1,0,1,0,    &  ! pressure
                    1,1,1,1,1,1,    &  ! scalar, such as vorticity
                    3,3,3,3,3,3,    &  ! tensor
                    ncompv_P2,ncompv_P2,ncompv_P2,ncompv_P2,ncompv_P2, &
                    ncompv_P2 ], & ! projection
                    [6,6] )

    input_probdef%physq = [1,2,3]
    input_probdef%probnr = 1

!   cell boundaries
    call define_essential ( mesh_np1, input_probdef, curve1=1, physq=2 )
    call define_essential ( mesh_np1, input_probdef, curve1=3, physq=2 )

    call define_essential ( mesh_np1, input_probdef, point=1, physq=3 )

!   constraint on particle boundary (freely floating)
    call define_constraint ( mesh_np1, input_probdef, curve1=5, physq=2, &
      discretization='collocation', nodedof=2, naddunknowns=3 )

!   periodic velocities
    call define_constraint ( mesh_np1, input_probdef, &
      physq=physqvel, curve1=2, curve2=6, discretization='collocation', &
      exclude=3 )

    call problem_definition ( input_probdef, mesh_np1, problem )

!   define viscoelastic problem, essential conditions and constraints
    call create_input_probdef ( mesh_np1, input_probdefc, nvec=4, nphysq=1 )

    input_probdefc%vec_elementdof(1)%a =   &
        reshape ( [ 1,0,1,0,1,0,    &  ! c
                    1,1,1,1,1,1,    &  ! scalar for plotting
                    3,3,3,3,3,3,    &  ! tensor
                    ncompv_P1,0,ncompv_P1,0,ncompv_P1,0 ], & ! projection
                    [6,4] )

    input_probdefc%physq = [1]
    input_probdefc%probnr = 2

!   periodic conformation
    call define_constraint ( mesh_np1, input_probdefc, &
      curve1=2, curve2=6, discretization='collocation' )

    call problem_definition ( input_probdefc, mesh_np1, problemc )

!   create system vectors for the upG problem
    call create_sysvector ( problem, sol_np1, sol_n, sol_nm1, rhsd )


!   create mesh velocity vectors and vector to store mesh coordinates
    call create ( problem, meshvel_np1, vec=2 )

!   create subscripts for the mesh velocity
    call create_subscript ( mesh_np1, problem, velx, physqarr=[2], degfd=1 )
    call create_subscript ( mesh_np1, problem, vely, physqarr=[2], degfd=2 )

!   create system vectors (solution and right-hand side) for conformation and
    call create ( problemc, solc_np1, solc_n, solc_nm1, rhsc )

!   create system matrix for the upg problem
    call create_sysmatrix_structure_base ( sysmatrix, mesh_np1, problem )
    call create_sysmatrix_structure_constraint ( sysmatrix, mesh_np1, problem )
    call finalize_sysmatrix_structure ( sysmatrix )
    call create_sysmatrix_data ( sysmatrix )

!   create system matrix for the ve problem
    call create_sysmatrix_structure_base ( sysmatrixc, mesh_np1, problemc )
    call create_sysmatrix_structure_constraint ( sysmatrixc, mesh_np1, &
      problemc )
    call finalize_sysmatrix_structure ( sysmatrixc )
    call create_sysmatrix_data ( sysmatrixc )

!   initialize all vectors to zero
    sol_nm1%u = 0.0_dp
    solc_nm1(1,1)%u = 0.0_dp
    solc_nm1(2,1)%u = 0.0_dp
    solc_nm1(3,1)%u = 0.0_dp
    sol_n%u = 0.0_dp
    solc_n(1,1)%u = 0.0_dp
    solc_n(2,1)%u = 0.0_dp
    solc_n(3,1)%u = 0.0_dp
    meshvel_np1%u = 0.0_dp

!   problem definition for projected "c=exp(s)" of the log conformation s
    call create_input_probdef ( mesh_np1, input_probdefc_projc, nvec=1, &
      nphysq=1 )

      input_probdefc_projc%vec_elementdof(1)%a = &
          reshape ( [ 1,0,1,0,1,0 ], &
                      [6,1] )

    input_probdefc_projc%physq = [1]
    input_probdefc_projc%probnr = 3

    call problem_definition ( input_probdefc_projc, mesh_np1, problemc_projc )

    call create ( problemc_projc, solc_projc, rhsc_projc )

    solc_projc(1,1)%u = 1   ! initial cxx
    solc_projc(2,1)%u = 0   ! initial cxy
    solc_projc(3,1)%u = 1   ! initial cyy

!   create system matrix for projection problem
    call create_sysmatrix_structure ( sysmatrixc_projc, mesh_np1, &
      problemc_projc, symmetric=.true. )
    call create_sysmatrix_data ( sysmatrixc_projc )

!   create oldvectors
    call create_oldvectors ( oldvectors_ve, nsysvec=2, nsysvec2=3, nprob=3, &
      nvec=2 )
    oldvectors_ve%s(1)%p => sol_n
    oldvectors_ve%s(2)%p => sol_nm1
    oldvectors_ve%s2(1)%p => solc_n
    oldvectors_ve%s2(2)%p => solc_nm1
    oldvectors_ve%s2(3)%p => solc_projc
    oldvectors_ve%p(1)%p => problem
    oldvectors_ve%p(2)%p => problemc
    oldvectors_ve%p(3)%p => problemc_projc
    oldvectors_ve%v(1)%p => meshvel_np1

  end subroutine define_problems_create_vectors


! delete old problem

  subroutine delete_old_problems

    call delete ( problem, problemc )
    call delete ( problem_lapl )
    call delete ( sysmatrix, sysmatrixc )
    call delete ( input_probdef, input_probdefc )
    call delete ( mesh_np1 )
    call delete ( sol_np1, sol_n, sol_nm1 )
    call delete ( solc_np1, solc_n, solc_nm1 )
    call delete ( rhsc )
    call delete ( rhsd )
    call delete ( oldvectors_ve )
    call delete ( meshvel_np1 )
    call delete ( velx, vely )
    call delete ( problemc_projc )
    call delete ( input_probdefc_projc )
    call delete ( solc_projc, rhsc_projc )
    call delete ( sysmatrixc_projc )

!   deallocate area and aspect ratio arrays
    deallocate ( init_aspect_ratio, aspect_ratio )
    deallocate ( init_area, areav )
    deallocate ( meshcoor_n, meshcoor_nm1 )

  end subroutine delete_old_problems


! build and solve the upG system

  subroutine build_solve_upG

!   fill solution vector with essential boundary conditions

    vel_upper_wall = (oy + ly) * amp * cos( freq * time )
    vel_lower_wall = oy * amp * cos( freq * time )

!   cell boundaries
    call fill_sysvector ( mesh_np1, problem, sol_np1, curve1=1, physq=2, &
      degfd=1, value=vel_lower_wall )
    call fill_sysvector ( mesh_np1, problem, sol_np1, curve1=1, physq=2, &
      degfd=2, value=0.0_dp )
    call fill_sysvector ( mesh_np1, problem, sol_np1, curve1=3, physq=2, &
      degfd=1, value=vel_upper_wall )
    call fill_sysvector ( mesh_np1, problem, sol_np1, curve1=3, physq=2, &
      degfd=2, value=0.0_dp )

!   point pressure
    call fill_sysvector ( mesh_np1, problem, sol_np1, point=1, physq=3, &
      value=0._dp )

!   stokes velocity/pressure
    call build_system ( mesh_np1, problem, sysmatrix, rhsd, &
      elemsub=stokes_elem, physqrow=[2,3], physqcol=[2,3], &
      coefficients=coefficients )

!   DEVSS-G
    call build_system ( mesh_np1, problem, sysmatrix, rhsd, &
      elemsub=devssg_elem, addmatvec=.true., &
      physqrow=[1,2], physqcol=[1,2], coefficients=coefficients )

!   set to zero off-diagonal blocks gradient-pressure
    call build_system ( mesh_np1, problem, sysmatrix, rhsd, addmatvec=.true., &
      buildvector=.false., physqrow=[1], physqcol=[3], zeromatvec=.true. )
    call build_system ( mesh_np1, problem, sysmatrix, rhsd, addmatvec=.true., &
      buildvector=.false., physqrow=[3], physqcol=[1], zeromatvec=.true. )

!   constraints on curves
    call build_system_constraint ( mesh_np1, problem, sysmatrix, rhsd, &
      constraint1=1, elemsub=elementc, addmatvec=.true. )

!   periodical condition on velocities
    call build_system_constraint ( mesh_np1, problem, sysmatrix, rhsd, &
      constraint1=2, elemsub=stokes_constr_node_conn, addmatvec=.true., &
      coefficients=coefficients )

!   build (assemble) vector for gradient/velocity/pressure problem
    if ( step >= 1 ) then

!     exps projection (for log conformation)
      if ( logc == 1 ) then
        call solve_exps_projection
      end if

      call build_system ( mesh_np1, problem, sysmatrix, rhsd, &
        elemsub=divtau_implicit_ce_elem_c, &
        oldvectors=oldvectors_ve, physqrow=[2], physqcol=[2], &
        addmatvec=.true., coefficients=coefficients )
    end if

    call check ( sysmatrix )

    call add_effect_of_essential_to_rhs ( problem, sysmatrix, sol_np1, rhsd )

!   solve vpG system
    solver_options_ma41%real_storage=rs_gup
    solver_options_ma41%integer_storage=is_gup

    call solve_system_ma41 ( sysmatrix, rhsd, sol_np1, &
      solver_options=solver_options_ma41 )

  end subroutine build_solve_upG


! build and solve the viscoelastic problem

  subroutine build_solve_ve

    integer :: icomp

!   build (assemble) matrix and vector for conformation problem
    if ( step == 1 ) then
      call build_system ( mesh_np1, problemc, sysmatrixc, m2sysvector=rhsc, &
        elemsub=ce_supg_elem, oldvectors=oldvectors_ve, &
        coefficients=coefficients )
    else
      call build_system ( mesh_np1, problemc, sysmatrixc, m2sysvector=rhsc, &
        elemsub=ce_supg_elem_implicit_2nd_order, oldvectors=oldvectors_ve, &
        coefficients=coefficients )
    end if

!   periodical condition on conformation tensor
    call build_system_constraint ( mesh_np1, problemc, sysmatrixc, &
      m2sysvector=rhsc, elemsub=stokes_constr_node_conn, addmatvec=.true. )

    call check ( sysmatrixc )

!   solve conformation and keep LU decomposition in the loop over components
    solver_options_ma41%real_storage=rs_c
    solver_options_ma41%integer_storage=is_c

    do icomp = 1, ncompc
      call solve_system_ma41 ( sysmatrixc, rhsc(icomp,1), solc_np1(icomp,1), &
        luc, solver_options=solver_options_ma41 )
    end do

    call delete ( luc )  ! remove LU decomposition and rebuild next time step

  end subroutine build_solve_ve


! write the data to .vtk files

  subroutine postprocessing ( mesh, sol, solc, ipost, check_proj  )

    type(mesh_t), intent(inout) :: mesh
    type(sysvector_t), intent(in), target :: sol
    type(sysvector_t), dimension(:,:), intent(in), target :: solc
    integer, intent(in), optional :: ipost
    character(len=*), intent(in), optional :: check_proj

    type(oldvectors_t) :: oldvectors_dve
    type(vector_t) :: cxx, cyy, cxy, pressure

    if ( .not. mesh%meshparts) call fill_mesh_parts ( mesh )

    call create_oldvectors ( oldvectors_dve, nsysvec=1, nsysvec2=1 )
    oldvectors_dve%s(1)%p => sol

    call create_vector ( problem, pressure, vec=4 )

!   derive the pressure in all nodes
    call derive_vector ( mesh, problem, pressure, &
      elemsub=stokes_pressure, coefficients=coefficients, &
      oldvectors=oldvectors_dve )

    if ( present(ipost) ) write(filename,'(a,i4.4,a)') 'flow', ipost, '.vtk'
    if ( present(check_proj) ) then
      write(filename,'(a,i4.4,a)') 'flow_'//check_proj//'.vtk'
    end if
    call write_scalar_vtk ( mesh, problem, vector=pressure, &
      dataname='pressure',  filename=filename )

    call write_vector_vtk ( mesh, problem, filename=filename, &
      dataname='velocity', sysvector=sol, physq=physqvel, &
      append=.true. )

!   print the gradients to a .vtk
!   note: this was used to quickly check the projection and is not
!   very neat since the gradients are not known in all nodes. To turn of the
!   warning WARN_ON_NO_DATA_IN_NODES from limits_m is set to false.
!    WARN_ON_NO_DATA_IN_NODES = .false.

!    call write_scalar_vtk ( mesh, problem, sysvector=sol, &
!      physq=1, degfd=1, filename=filename, dataname='gradu_1', append=.true. )
!    call write_scalar_vtk ( mesh, problem, sysvector=sol, &
!      physq=1, degfd=2, filename=filename, dataname='gradu_2', append=.true. )
!    call write_scalar_vtk ( mesh, problem, sysvector=sol, &
!      physq=1, degfd=3, filename=filename, dataname='gradu_3', append=.true. )
!    call write_scalar_vtk ( mesh, problem, sysvector=sol, &
!      physq=1, degfd=4, filename=filename, dataname='gradu_4', append=.true. )

    oldvectors_dve%s2(1)%p => solc
    call create_vector ( problemc, cxx, vec=2 )
    call create_vector ( problemc, cxy, vec=2 )
    call create_vector ( problemc, cyy, vec=2 )

    coefficients%i(13)=1
    call derive_vector ( mesh, problemc, cxx, elemsub=deriv_conformation, &
      coefficients=coefficients, oldvectors=oldvectors_dve )
    coefficients%i(13)=2
    call derive_vector ( mesh, problemc, cxy, elemsub=deriv_conformation, &
      coefficients=coefficients, oldvectors=oldvectors_dve )
    coefficients%i(13)=3
    call derive_vector ( mesh, problemc, cyy, elemsub=deriv_conformation, &
      coefficients=coefficients, oldvectors=oldvectors_dve )

    if ( present(ipost) ) write(filename,'(a,i4.4,a)') 'c', ipost, '.vtk'
    if ( present(check_proj) ) then
      write(filename,'(a,i4.4,a)') 'c_'//check_proj//'.vtk'
    end if
    call write_scalar_vtk ( mesh, problemc, vector=cxx, &
      filename=filename, dataname='cxx' )

    call write_scalar_vtk ( mesh, problemc, vector=cxy, &
      filename=filename, dataname='cxy', append=.true. )

    call write_scalar_vtk ( mesh, problemc, vector=cyy, &
      filename=filename, dataname='cyy', append=.true. )

   call delete(cxx, cxy, cyy, pressure)
   call delete(oldvectors_dve)

  end subroutine postprocessing


! P2 project the velocities and coordinates on the new mesh

  subroutine project_old_solutions_P2

    type(input_probdef_t) :: input_probdef_proj
    type(problem_t) :: problem_proj
    type(sysmatrix_t) :: sysmatrix_proj
    type(sysvector_t) :: rhsd_proj(ncompv_P2)
    type(sysvector_t) :: sol_proj(ncompv_P2)
    type(oldvectors_t) :: oldvectors_proj
    type(coefficients_t) :: coefficients_proj
    type(vector_t), target :: vec_p
    type(lu_ma57_t) :: lu2

    integer :: i

!   create vector for projection
    call create ( problem_temp, vec_p, vec=6 )

!   transfer the coordinates at n
    call transfer_data ( mesh_np1_temp, problem_temp, &
      vector1=coords_n_temp, vector2=vec_p, degfd2=[1,2] )

!   transfer the coordinates at n-1
    call transfer_data ( mesh_np1_temp, problem_temp, &
      vector1=coords_nm1_temp, vector2=vec_p, degfd2=[3,4] )

!   problem definition for projection
    call create_input_probdef ( mesh_np1, input_probdef_proj )

    input_probdef_proj%elementdof(1)%a = 1
    call problem_definition ( input_probdef_proj, mesh_np1, problem_proj )

!   create system vectors (solution and right-hand side)
    call create ( problem_proj, sol_proj )
    call create ( problem_proj, rhsd_proj )

!   create system matrix
    call create_sysmatrix_structure ( sysmatrix_proj, mesh_np1, &
      problem_proj, symmetric=.true. )
    call create_sysmatrix_data ( sysmatrix_proj )

!   fill coefficients
    call create_coefficients ( coefficients_proj, ncoefi=100, ncoefr=50 )
    coefficients_proj%i = 0
    coefficients_proj%i(1:4) = [ uintpl, ncompv_P2, uintpl, uintpl ]
    coefficients_proj%i(10) = gauss_proj
    coefficients_proj%i(23) = coorsys
    coefficients_proj%i(40) = inttype_proj
    coefficients_proj%r = 0

!   oldvectors
    call create_oldvectors ( oldvectors_proj, nvec=1, nprob=1, nmesh=1 )
    oldvectors_proj%v(1)%p => vec_p
    oldvectors_proj%p(1)%p => problem_temp
    oldvectors_proj%m(1)%p => mesh_np1_temp

!   build (assemble) matrix and vector from elements
    call build_system ( mesh_np1, problem_proj, sysmatrix_proj, &
      msysvector=rhsd_proj, elemsub=projection_elem, &
      coefficients=coefficients_proj, oldvectors=oldvectors_proj )

!   solve the projection problem
    do i = 1, ncompv_P2
      call add_effect_of_essential_to_rhs ( problem_proj, sysmatrix_proj, &
       sol_proj(i), rhsd_proj(i) )
      call solve_system_ma57 ( sysmatrix_proj, rhsd_proj(i), sol_proj(i), &
        lu=lu2 )
    end do

!   create meshes at t_n and t_nm1 and update the old coordinates
    meshcoor_n(:,1) = sol_proj(1)%u
    meshcoor_n(:,2) = sol_proj(2)%u
    meshcoor_nm1(:,1) = sol_proj(3)%u
    meshcoor_nm1(:,2) = sol_proj(4)%u

!   delete definitions used for the projection problem
    call delete ( lu2 )
    call delete( input_probdef_proj )
    call delete( problem_proj )
    call delete( sysmatrix_proj )
    call delete( rhsd_proj )
    call delete( sol_proj )
    call delete( oldvectors_proj )
    call delete( coefficients_proj )
    call delete( vec_p )

  end subroutine project_old_solutions_P2


! P1 project the conformation components and velocity gradients on the new mesh

  subroutine project_old_solutions_P1

    type(input_probdef_t) :: input_probdef_proj
    type(problem_t) :: problem_proj
    type(sysmatrix_t) :: sysmatrix_proj
    type(sysvector_t) :: rhsd_proj(ncompv_P1)
    type(sysvector_t) :: sol_proj(ncompv_P1)
    type(oldvectors_t) :: oldvectors_proj
    type(coefficients_t) :: coefficients_proj
    type(vector_t), target :: vec_p
    type(lu_ma57_t) :: lu2

    type(subscript_t) :: cc

    integer :: i

!   create vector for projection
    call create ( problemc_temp, vec_p, vec=4 )

!   transfer the conformation tensor at n
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_n_temp(1,1), vector2=vec_p, physq1=[1], degfd2=[1] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_n_temp(2,1), vector2=vec_p, physq1=[1], degfd2=[2] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_n_temp(3,1), vector2=vec_p, physq1=[1], degfd2=[3] )

!   transfer the conformation tensor at n-1
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_nm1_temp(1,1), vector2=vec_p, physq1=[1], degfd2=[4] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_nm1_temp(2,1), vector2=vec_p, physq1=[1], degfd2=[5] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_nm1_temp(3,1), vector2=vec_p, physq1=[1], degfd2=[6] )

!   problem definition for projection
    call create_input_probdef ( mesh_np1, input_probdef_proj )

    input_probdef_proj%elementdof(1)%a = [1,0,1,0,1,0]
    call problem_definition ( input_probdef_proj, mesh_np1, problem_proj )

!   create system vectors (solution and right-hand side)
    call create ( problem_proj, sol_proj )
    call create ( problem_proj, rhsd_proj )

!   create system matrix
    call create_sysmatrix_structure ( sysmatrix_proj, mesh_np1, &
      problem_proj, symmetric=.true. )
    call create_sysmatrix_data ( sysmatrix_proj )

!   fill coefficients
    call create_coefficients ( coefficients_proj, ncoefi=100, ncoefr=50 )
    coefficients_proj%i = 0
    coefficients_proj%i(1:4) = [ gintpl, ncompv_P1, uintpl, gintpl ]
    coefficients_proj%i(10) = gauss_proj
    coefficients_proj%i(23) = coorsys
    coefficients_proj%i(40) = inttype_proj
    coefficients_proj%r = 0

!   oldvectors
    call create_oldvectors ( oldvectors_proj, nvec=1, nprob=1, nmesh=1 )
    oldvectors_proj%v(1)%p => vec_p
    oldvectors_proj%p(1)%p => problemc_temp
    oldvectors_proj%m(1)%p => mesh_np1_temp

!   build (assemble) matrix and vector from elements
    call build_system ( mesh_np1, problem_proj, sysmatrix_proj, &
      msysvector=rhsd_proj, elemsub=projection_elem, &
      coefficients=coefficients_proj, oldvectors=oldvectors_proj )

!   solve the projection problem
    do i = 1, ncompv_P1
      call add_effect_of_essential_to_rhs ( problem_proj, sysmatrix_proj, &
       sol_proj(i), rhsd_proj(i) )
      call solve_system_ma57 ( sysmatrix_proj, rhsd_proj(i), sol_proj(i), &
        lu=lu2 )
    end do

!   update the conformation tensor
!   note: because a subscript to the conformation tensor is not needed in the
!   main part of the program, a subscript is created here 'on the fly' and
!   deleted after it is used.
    call create_subscript ( mesh_np1, problemc, cc, physqarr=[1] )
    solc_n(1,1)%u(cc%s) = sol_proj(1)%u
    solc_n(2,1)%u(cc%s) = sol_proj(2)%u
    solc_n(3,1)%u(cc%s) = sol_proj(3)%u
    solc_nm1(1,1)%u(cc%s) = sol_proj(4)%u
    solc_nm1(2,1)%u(cc%s) = sol_proj(5)%u
    solc_nm1(3,1)%u(cc%s) = sol_proj(6)%u
    call delete ( cc )

!   delete definitions used for the projection problem
    call delete ( lu2 )
    call delete( input_probdef_proj )
    call delete( problem_proj )
    call delete( sysmatrix_proj )
    call delete( rhsd_proj )
    call delete( sol_proj )
    call delete( oldvectors_proj )
    call delete( coefficients_proj )
    call delete( vec_p )

  end subroutine project_old_solutions_P1


! project c=exp(s) on discrete fem space
  subroutine solve_exps_projection

    type(solver_options_ma57_t) :: solver_options_ma57

    integer :: i, m

!   build system matrix and vector for projection problem
    call build_system ( mesh_np1, problemc_projc, sysmatrixc_projc, &
      m2sysvector=rhsc_projc, elemsub=exps_projection_elem, &
      oldvectors=oldvectors_ve, coefficients=coefficients )

    call check ( sysmatrixc_projc )

!   MA57 solver storage
    solver_options_ma57%integer_storage = 1.3
    solver_options_ma57%real_storage    = 1.3

!   LU decomposition is done in the first loop traversing
    do m = 1, nmodes
      do i = 1, ncompc

        call add_effect_of_essential_to_rhs ( problemc_projc, &
          sysmatrixc_projc, solc_projc(i,m), rhsc_projc(i,m) )

        call solve_system_ma57 ( sysmatrixc_projc, rhsc_projc(i,m), &
           solc_projc(i,m), lu_exps_projc, solver_options=solver_options_ma57 )

      end do
    end do

    call delete ( lu_exps_projc )

  end subroutine solve_exps_projection


end program ale12
