#if SKIT2 && METIS5

! Viscoelastic problem:
! Oscillating Couette flow with a freely floating solid particle
! DEVSS-G/SUPG
! Implicit bilinear terms of CE in momentum balance.
! Particle updater uses a second-order AB2 scheme.
! second-order time integration
! ALE body-fitting mesh scheme
! Periodic velocities/conformation tensor using collocation on surfaces
! Mesh generated by Gmsh using tetrahedrons
! Remeshing is performed when the maximum normalized volume or aspect ratio
! of the mesh elements is higher than a threshold.
! After remeshing, the field variables from previous time steps are obtained
! on the current mesh by solving a projection problem.
! Note: the coordinates of the old (discarded) mesh at previous time steps
! are projected onto the new (remeshed) mesh to obtain the new mesh at
! previous time steps. This is necessary to find the new mesh velocity.
! Note2: if the log transformation method is used, a projection problem
! is solved at each time step to find the L2-projection of c=exp(s).
! This problem is similar to ale13, but now using sparskit as a solver for the
! upG system and using Metis to perform a renumbering of the mesh

program ale14

  use tfem_m
  use hsl_ma41_m
  use hsl_ma57_m
  use stokes_elements_m
  use viscoelastic_elements_m
  use io_utils_m
  use subs13_m
  use update_mesh_nodes13_m
  use projection_elements_m
  use metis5_m
  use sk_solve_m

  implicit none


! constants

  integer, parameter :: &
    uintpl = 6,       & ! P2 velocities
    pintpl = 2,       & ! P1 pressures
    gintpl = 2,       & ! P1 gradients
    cintpl = 2,       & ! P1 conformation
    physqgrad = 1,    & ! physical quantity nr of the gradients
    physqvel = 2,     & ! physical quantity nr of the velocities
    physqpress = 3,   & ! physical quantity nr of the pressures
    gauss = 8,        & ! 8-point Gauss integration of tets
    gaussb = 3,       & ! 3-point integration of boundary elements
    gauss_proj = 8,   & ! integration rule for the projection problem
    inttype_proj = 0, & ! standard Gauss-Legendre
    ncompc = 6,       & ! number of conformation tensor components
    nmodes = 1,       & ! number of modes
    startm = 501,     & ! start of material model data
    coorsys = 0,      & ! coordinate system
    model = 3,        & ! Giesekus model
    vtkevery = 10,    & ! vtk file every vtkevery steps. 0: means none
    ncompv_P2 = 6,    & ! number of components for P2 projection:
                        ! x,y,z-coordinates at n and n-1
    ncompv_P1 = 12,   & ! number of components for P1 projection:
                        ! conformation components at n and n-1
    numtimesteps = 5000 ! number of time steps

  logical, parameter :: check_projection = .false. ! write vtks before and after
                                                   ! the projection


! variables

  integer :: &
    timeint1 = 1,       & ! first-order, semi-implicit Euler
    timeint2 = 7,       & ! second-order, semi-implicit Gear/Karniadakis with
                          ! conformation prediction
    logc = 1              ! standard scheme or log transformation

  real(dp) :: &
    eta_s = 0.1_dp,     & ! solvent viscosity
    eta_p = 1.0_dp,     & ! polymer viscosity
    lambda = 1.0_dp,    & ! relaxation time
    mobility = 0.2_dp,  & ! mobility parameter in the Giesekus model (alpha)
    amp = 1.0_dp,       & ! amplitude of the imposed sinusoidal shear rate
    freq = 0.5_dp,      & ! frequency of the imposed sinusoidal shear rate
    time = 0.0_dp,      & ! initial time
    deltat = 0.02_dp,   & ! time step
    eps_sk = 1.e-6_dp,  & ! relative tolerance used in sparskit
    beta = 1.0_dp,      & ! upwinding parameter in the SUPG method
    dx_box = 0.2_dp,    & ! element spacing on the external boundaries
    dx_part = 0.04_dp,  & ! element spacing on the particle boundary
    rs_gup = 1.4_dp,    & ! real_storage gradient-velocity-pressure LU (HSL)
    is_gup = 1.5_dp,    & ! integer_storage gradient-velocity-pressure LU (HSL)
    rs_c  = 1.4_dp,     & ! real_storage for the conformation LU (HSL)
    is_c  = 1.6_dp,     & ! integer_storage for conformation LU (HSL)
    volume_threshold = 1.39_dp,      & ! remeshing volume threshold
    aspect_ratio_threshold = 1.39_dp   ! remeshing aspect ratio threshold


! definitions for ve and upg problems

  type(mesh_t) :: mesh_np1
  type(input_probdef_t) :: input_probdef, input_probdefc, input_probdefc_projc
  type(problem_t), target :: problem, problemc, problemc_projc
  type(sysmatrix_t) :: sysmatrix, sysmatrixc, sysmatrixc_projc
  type(sysvector_t), target :: sol_np1, sol_n, sol_nm1
  type(sysvector_t) :: rhsd
  type(oldvectors_t) :: oldvectors_ve
  type(coefficients_t) :: coefficients
  type(sysvector_t), dimension(ncompc,nmodes), target :: solc_np1, solc_n
  type(sysvector_t), dimension(ncompc,nmodes), target :: solc_nm1, rhsc
  type(sysvector_t), dimension(ncompc,nmodes), target :: solc_projc, rhsc_projc
  type(lu_ma41_t) :: luc
  type(lu_ma57_t) :: lu_exps_projc
  type(solver_options_ma41_t) :: solver_options_ma41
  type(solver_options_sk_t) :: solver_options_sk
  type(ilu_sk_t) :: ilu
  type(vector_t), target :: meshvel_np1
  type(subscript_t) :: velx, vely, velz
  type(problem_t) :: problem_lapl


! temp definitions used to store old definitions before projection

  type(mesh_t), target :: mesh_np1_temp
  type(sysvector_t), dimension(ncompc,nmodes) :: solc_n_temp, solc_nm1_temp
  type(sysvector_t) :: sol_n_temp, sol_nm1_temp
  type(vector_t) :: coords_n_temp, coords_nm1_temp
  type(problem_t), target :: problem_temp, problemc_temp


! variables

  integer :: i, step=0, ipost=0

  real(dp) :: ox, oy, oz, lx, ly, lz, vel_lower_wall, vel_upper_wall
  real(dp) :: up(6), unm1(6), un(6), pp(6), ppn(6)

  real(dp), dimension(:), allocatable :: init_volume, volumev
  real(dp), dimension(:), allocatable :: init_aspect_ratio, aspect_ratio
  real(dp), allocatable, dimension(:,:) :: meshcoor_n, meshcoor_nm1, &
    meshcoor_temp
  real(dp) :: norm_volume, norm_aspect_ratio, normf

  character(len=30) :: filename
  logical :: remeshing=.false., maxmvmreached

  integer :: icomp
  real(dp) :: alpha, G


  open (unit = 100, file='output.txt')


! set some parameters

  alpha = eta_p         ! DEVSS parameter
  G = eta_p / lambda    ! modulus


! fill coefficients

  call create_coefficients ( coefficients, ncoefi=150, ncoefr=500+3*nmodes )

  coefficients%i = &
    [ uintpl,   pintpl,     0,     0,         gintpl, &
      physqvel, physqpress, 0,     physqgrad, gauss,  &
      gaussb,   cintpl,     0,     0,         0,      &
      0,        0,          model, nmodes,    startm, &
      logc,     timeint1,    coorsys, ( 0, i = 24, 150 )  &
    ]

  coefficients%i(48) = 1 ! use mesh velocity for ALE formulation
  coefficients%i(49) = 1  ! exp(s) projection =.true. for logc=1

  coefficients%r(1:502) = &
    [ eta_s,    0._dp,   0._dp,   alpha, 0._dp, &
      0._dp, 0._dp,  deltat,   beta,  0._dp, &
      ( 0._dp, i = 11, 500 ), &
      G,     lambda  &
    ]

  if ( model == 3 ) then
    coefficients%r(503) = mobility
  end if


! mesh parameters

  ox = -1.0_dp
  oy = -0.5_dp
  oz = -0.5_dp
  lx =  2.0_dp
  ly =  1.0_dp
  lz =  1.0_dp


! one particle

  rp = 0.1_dp          ! particle radius
  xp(1,1) = 0.0_dp       ! x-position of the particle
  xp(1,2) = 0.1_dp       ! y-position of the particle
  xp(1,3) = 0.0_dp       ! z-position of the particle

  pp(1:3) = [xp(1,1:3)]
  pp(3:6) =  0._dp      ! initial rotation angle

  call generate_read_mesh


! define the upg and ve problem, create (sys)vectors, subscripts, oldvectors
! and initialize sysvectors

  call define_problems_create_vectors


! initialize vectors with zero stress

  if ( logc == 0 ) then ! standard
    solc_np1(1,1)%u = 1 ! initial cxx
    solc_np1(2,1)%u = 0 ! initial cxy
    solc_np1(3,1)%u = 0 ! initial cxz
    solc_np1(4,1)%u = 1 ! initial cyy
    solc_np1(5,1)%u = 0 ! initial cyz
    solc_np1(6,1)%u = 1 ! initial czz
  else if ( logc == 1 ) then ! log scheme
    solc_np1(1,1)%u = 0 ! initial sxx
    solc_np1(2,1)%u = 0 ! initial sxy
    solc_np1(3,1)%u = 0 ! initial sxz
    solc_np1(4,1)%u = 0 ! initial syy
    solc_np1(5,1)%u = 0 ! initial syz
    solc_np1(6,1)%u = 0 ! initial szz
  end if


! solve upG problem without the divtau term

  call build_solve_upG


! extract info on particle

  call get_sysvector_constraint ( mesh_np1, problem, sol_np1, constraint=1, &
    addunknowns=.true., u=up )

  write ( *, '(1X,A)' ) '****************************************'
  write ( *, '(1X,A,I0)' ) 'step = ', step
  write ( *, '(1X,A,6F12.6)' ) 'pp = ', pp
  write ( *, '(1X,A,6F12.6)' ) 'up = ', up
  write ( *, '(1X,A,F10.6)' )  'normalized volume = ', norm_volume
  write ( *, '(1X,A,F10.6)' )  'normalized aspect ratio = ', norm_aspect_ratio
  write ( *,* )

  write(100, '(i6,13es22.12)') step, time, pp, up


! write VTK files

  call postprocessing ( mesh_np1, sol_np1, solc_np1, ipost=ipost )
  ipost = ipost + 1


! copy old values

  call copy ( sol_np1, sol_n )
  call copy ( solc_np1, solc_n )
  meshcoor_n = mesh_np1%coor


! start time integration

  time = 0

  do step = 1, numtimesteps

    time = time + deltat
    if ( step > 1 ) coefficients%i(22) = timeint2

    if ( step == 1 ) then

!     advance with forward Euler
      un = up
      ppn = pp
      pp = pp + deltat * un

    else

!     advance particle position with 2nd order Adams-Bashforth
      unm1 = un
      un = up
      ppn = pp
      pp = pp + deltat*(3*un/2 - unm1/2)

    end if

    xp(1,1:3) = pp(1:3)


!   update mesh nodes: solve a Laplace's equation

    call update_mesh_nodes ( mesh_np1, problem_lapl, pp(1:3)-ppn(1:3) )

    call find_bounds_blocks ( mesh_np1 )


!   compute current aspect ratio

    call compute_element_aspect_ratio ( mesh_np1, volumev, aspect_ratio )


!   compute maximum normalized aspect ratio and volume
!   (with respect to the initial values)

    norm_volume = maxval( abs(log(volumev/init_volume)) )
    norm_aspect_ratio = maxval( abs(log(aspect_ratio/init_aspect_ratio)) )


!   remeshing criterion

    remeshing = .false.

    if ( ( norm_volume >= volume_threshold .or. &
           norm_aspect_ratio >= aspect_ratio_threshold ) .and. &
           step /= numtimesteps ) then
      remeshing = .true.
    end if


    if ( remeshing ) then

      print *,'Remeshing and projection...'


!     check the projection
!     (use mesh_np1 with the coordinates at the previous time steps)

      if ( check_projection ) then
        allocate ( meshcoor_temp(mesh_np1%nnodes, mesh_np1%ndim) )
        meshcoor_temp = mesh_np1%coor
        mesh_np1%coor = meshcoor_n
        call postprocessing ( mesh_np1, sol_n, solc_n, check_proj='n_pre_proj' )
        mesh_np1%coor = meshcoor_nm1
        call postprocessing ( mesh_np1, sol_nm1, solc_nm1, &
          check_proj='nm1_pre_proj' )
        mesh_np1%coor = meshcoor_temp
        deallocate ( meshcoor_temp )
      end if


!     create vectors to store the mesh coordinates, these coordinates will
!     be used in the projection problem to find the new mesh at t_n and t_nm1

      call create ( problem, coords_n_temp, vec=2 )
      call create ( problem, coords_nm1_temp, vec=2 )

      coords_n_temp%u = reshape ( transpose ( meshcoor_n ), [size(meshcoor_n)] )
      coords_nm1_temp%u = reshape ( transpose ( meshcoor_nm1 ), &
                                    [size(meshcoor_nm1)] )


!     copy current definitions to temporary definitions used for the projection
!     problem

      call copy ( mesh_np1, mesh_np1_temp )
      call fill_mesh_parts ( mesh_np1_temp )
      call copy ( solc_n, solc_n_temp )
      call copy ( sol_n, sol_n_temp )
      call copy ( solc_nm1, solc_nm1_temp )
      call copy ( sol_nm1, sol_nm1_temp )
      call problem_definition ( input_probdef, mesh_np1, problem_temp )
      call problem_definition ( input_probdefc, mesh_np1, problemc_temp )


!     delete the old problems

      call delete_old_problems


!     generate new mesh

      call generate_read_mesh


!     define the upg and ve problem, create (sys)vectors, subscripts, oldvectors
!     and initialize sysvectors

      call define_problems_create_vectors


!     project the old solutions onto the new mesh and fill in the values

      call project_old_solutions_P2
      call project_old_solutions_P1


!     check the projection (use mesh_np1 with the coordinates at the
!     previous time steps)

      if ( check_projection ) then
        allocate ( meshcoor_temp(mesh_np1%nnodes, mesh_np1%ndim) )
        meshcoor_temp = mesh_np1%coor
        mesh_np1%coor = meshcoor_n
        call postprocessing ( mesh_np1, sol_n, solc_n, &
          check_proj='n_post_proj' )
        mesh_np1%coor = meshcoor_nm1
        call postprocessing ( mesh_np1, sol_nm1, solc_nm1, &
          check_proj='nm1_post_proj' )
        mesh_np1%coor = meshcoor_temp
        deallocate ( meshcoor_temp )
      end if


!     delete the temporary definitions

      call delete ( coords_n_temp, coords_nm1_temp )
      call delete ( mesh_np1_temp )
      call delete ( solc_n_temp )
      call delete ( sol_n_temp )
      call delete ( solc_nm1_temp )
      call delete ( sol_nm1_temp )
      call delete ( problemc_temp )
      call delete ( problem_temp )


    end if


!   find the mesh velocity using a backwards differencing scheme

    if ( step == 1  ) then
      meshvel_np1%u = &
        reshape ( transpose ( ( mesh_np1%coor - meshcoor_n ) / deltat ), &
                              [mesh_np1%ndim*mesh_np1%nnodes] )
    else
      meshvel_np1%u = &
        reshape ( transpose ( ( 1.5_dp*mesh_np1%coor - 2*meshcoor_n +  &
          0.5_dp*meshcoor_nm1 ) / deltat ), [mesh_np1%ndim*mesh_np1%nnodes] )
    end if


!   build and solve the upG system

    call build_solve_upG


!   copy old value (already here, so sol_np1 is used in the VE problem!)

    call copy ( sol_n, sol_nm1 )
    call copy ( sol_np1, sol_n )


!   build and solve the conformation problem

    call build_solve_ve


!   extract info on particle

    call get_sysvector_constraint ( mesh_np1, problem, sol_np1, constraint=1, &
      addunknowns=.true., u=up )

    write ( *, '(1X,A)' ) '****************************************'
    write ( *, '(1X,A,I0)' ) 'step = ', step
    write ( *, '(1X,A,6F12.6)' ) 'pp = ', pp
    write ( *, '(1X,A,6F12.6)' ) 'up = ', up
    write ( *, '(1X,A,F10.6)' )  'normalized volume = ', norm_volume
    write ( *, '(1X,A,F10.6)' )  'normalized aspect ratio = ', norm_aspect_ratio
    write ( *,* )

    write(100, '(i6,13es22.12)') step, time, pp, up


!   write VTK files

    if ( vtkevery > 0 ) then
      if ( mod(step,vtkevery) == 0 ) then
        call postprocessing ( mesh_np1, sol_np1, solc_np1, ipost=ipost )
        ipost = ipost + 1
      end if
    end if


!   copy old values
!   note: sol is already copied in the time integration loop)

    call copy ( solc_n, solc_nm1 )
    call copy ( solc_np1, solc_n )
    meshcoor_nm1 = meshcoor_n
    meshcoor_n = mesh_np1%coor


  end do


  close(unit=100)


! delete all data including all allocated memory

  call delete_old_problems


contains


! generate and read mesh

  subroutine generate_read_mesh

    call write_gmsh_parameters ( ox, oy, oz, lx, ly, lz, xp, rp, dx_box, &
      dx_part )

    call execute_command_line ( 'gmsh -3 -order 2 -algo del3d -o mesh.msh &
                  &mesh.geo > outputmesh.out' )

!   read mesh generated by gmsh
    call read_mesh_gmsh ( mesh_np1, filename='mesh.msh', ndim=3, &
      physgeom=.true. )

!   local node numbering surface 4 to match local node numbering of surface 2
    call add_to_mesh ( mesh_np1, matchingsurface=[4,2], replace=4, &
      displacement=[-lx,0._dp,0._dp] )
!   local node numbering surface 6 to match local node numbering of surface 5
    call add_to_mesh ( mesh_np1, matchingsurface=[6,5], replace=6, &
      displacement=[0._dp,0._dp,-lz] )

    call fill_mesh_parts ( mesh_np1 )

!   renumber using metis
    call renumber_metis ( mesh_np1 )

!   allocate aspect ratio arrays
    allocate ( init_volume(mesh_np1%nelem), volumev(mesh_np1%nelem) )
    allocate ( init_aspect_ratio(mesh_np1%nelem), aspect_ratio(mesh_np1%nelem) )

!   define some arrays for the ale mesh position at old times
    allocate ( meshcoor_n(mesh_np1%nnodes,mesh_np1%ndim), &
      meshcoor_nm1(mesh_np1%nnodes,mesh_np1%ndim) )

!   compute initial element aspect ratio
    call compute_element_aspect_ratio ( mesh_np1, init_volume, &
      init_aspect_ratio )

    norm_volume = 0.0_dp
    norm_aspect_ratio = 0.0_dp

    call write_mesh_vtk ( mesh_np1, filename='mesh.vtk' )

  end subroutine generate_read_mesh


! compute the aspect ratio and volume for each mesh element

  subroutine compute_element_aspect_ratio ( mesh, volume, asp_ratio )

    use math_defs_m

    type(mesh_t), intent(in) :: mesh
    real(dp), dimension(:), intent(out) :: asp_ratio, volume

    integer :: elem, node(4), grp, totelem
    real(dp) :: la, lb, lc, ld, le, lf
    real(dp) :: vert(4,3)

    node = [1,3,5,10]

    totelem = 0

    do grp = 1, mesh%nelgrp
      do elem = 1,mesh%grpnumel(grp)

        totelem = totelem + 1

!       get coordinates of tetrahedron vertices
        vert = mesh%coor(mesh%topology(grp)%a(node,elem),:)

!       compute side lengths
        la = lv ( vert(1,:) - vert(2,:) )
        lb = lv ( vert(2,:) - vert(3,:) )
        lc = lv ( vert(3,:) - vert(1,:) )
        ld = lv ( vert(1,:) - vert(4,:) )
        le = lv ( vert(2,:) - vert(4,:) )
        lf = lv ( vert(3,:) - vert(4,:) )

!       compute volume of tetrahedron
        volume(totelem) = abs ( dot_product ( vert(1,:) - vert(4,:), &
          cross_product ( vert(2,:) - vert(4,:), vert(3,:) - vert(4,:) ) ) ) / 6

!       compute aspect ratio
        asp_ratio(totelem) = max(la,lb,lc,ld,le,lf)**3/volume(totelem)

      end do
    end do

  end subroutine compute_element_aspect_ratio


! length function

  function lv ( a )

    real(dp), intent(in), dimension(3) :: a
    real(dp) :: lv

    lv = sqrt ( a(1)**2 + a(2)**2 + a(3)**2 )

  end function lv


! write the parameters in gmsh format

  subroutine write_gmsh_parameters ( ox, oy, oz, lx, ly, lz, xp, rp, dx_box, &
    dx_part )

    real(dp), intent(in) :: ox, oy, oz, lx, ly, lz, xp(:,:), rp(:), &
      dx_box, dx_part

    integer :: i, nobj

    nobj = size(rp)

    open ( unit=25, file='mesh.geo' )

    write ( 25, '(1X,A,F18.14,A)' ) 'ox = ', ox, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'oy = ', oy, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'oz = ', oz, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'lx = ', lx, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'ly = ', ly, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'lz = ', lz, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'dx_box = ', dx_box, ';'
    write ( 25, '(1X,A,I0,A)' ) 'nobj = ', nobj, ';'

    do i = 1, nobj
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'xp[', i, '] = ', xp(i,1), ';'
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'yp[', i, '] = ', xp(i,2), ';'
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'zp[', 1, '] = ', xp(i,3), ';'
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'rp[', i, '] = ', rp(i), ';'
    end do

    write ( 25, '(1X,A,F18.14,A)' ) 'dx_part = ', dx_part, ';'

    write ( 25, '(/1x,a)' ) 'Include "particles_in_a_box_3D.igo";'

    close ( 25 )

  end subroutine write_gmsh_parameters


! start the problems

  subroutine define_problems_create_vectors

    integer :: i

!   problem definition of gradient/velocity/pressure
!   NOTE, shifting of physical quantities to the end of the system vector
!         affects the number of iterations. For this problem, shifting
!         pressures increases the number of iterations significantly
!         (compared to no shifting). Shifting only G is used here.

!    call create_input_probdef ( mesh_np1, input_probdef, nvec=5, nphysq=3 )
    call create_input_probdef ( mesh_np1, input_probdef, nvec=5, nphysq=3, &
      nphysqshifted=1 )
!    call create_input_probdef ( mesh_np1, input_probdef, nvec=5, nphysq=3, &
!      nphysqshifted=2 )

    input_probdef%vec_elementdof(1)%a =   &
        reshape ( [ 9,0,9,0,9,0,0,0,0,9,    &  ! G
                    3,3,3,3,3,3,3,3,3,3,    &  ! velocity
                    1,0,1,0,1,0,0,0,0,1,    &  ! pressure
                    1,1,1,1,1,1,1,1,1,1,    &  ! scalar, such as vorticity
                    (ncompv_P2, i=1,10 ) ],&  ! projection
                    [10,5] )

    input_probdef%physq = [1,2,3]
    input_probdef%physqshifted = [1] ! G only shifting
!    input_probdef%physqshifted = (/3/) ! pressure only shifting
!    input_probdef%physqshifted = (/3,1/) ! G and pressure shifting
!    input_probdef%physqshifted = (/1,3/) ! pressure and G shifting
    input_probdef%probnr = 1

!   cell boundaries
    call define_essential (mesh_np1, input_probdef, surface1=1, physq=physqvel)
    call define_essential (mesh_np1, input_probdef, surface1=3, physq=physqvel)

    call define_essential (mesh_np1, input_probdef, point=1, physq=physqpress )

!   constraint on particle boundary (freely floating)
    call define_constraint ( mesh_np1, input_probdef, surface1=7, &
      physq=physqvel, discretization='collocation', nodedof=3, naddunknowns=6 )

!   periodic velocities
    call define_constraint ( mesh_np1, input_probdef, &
      physq=physqvel, surface1=2, surface2=4, discretization='collocation', &
      excludesurfaces=[1,3] )
    call define_constraint ( mesh_np1, input_probdef, &
      physq=physqvel, surface1=5, surface2=6, discretization='collocation', &
      excludesurfaces=[1,2,3] )

    call problem_definition ( input_probdef, mesh_np1, problem )

!   define viscoelastic problem, essential conditions and constraints
    call create_input_probdef ( mesh_np1, input_probdefc, nvec=3, nphysq=1 )

    input_probdefc%vec_elementdof(1)%a =   &
        reshape ( [ 1,0,1,0,1,0,0,0,0,1,    &  ! c
                    1,1,1,1,1,1,1,1,1,1,    &  ! scalar for plotting
                    ncompv_P1,0,ncompv_P1,0,ncompv_P1, &
                    0,0,0,0,ncompv_P1 ], & ! projection
                    [10,3] )

    input_probdefc%physq = [1]
    input_probdefc%probnr = 2

!   periodic conformation
    call define_constraint ( mesh_np1, input_probdefc, &
      surface1=2, surface2=4, discretization='collocation' )
    call define_constraint ( mesh_np1, input_probdefc, &
      surface1=5, surface2=6, discretization='collocation', &
      excludesurfaces=[2] )

    call problem_definition ( input_probdefc, mesh_np1, problemc )

!   create system vectors for the upG problem
    call create_sysvector ( problem, sol_np1, sol_n, sol_nm1, rhsd )


!   create mesh velocity vectors and vector to store mesh coordinates
    call create ( problem, meshvel_np1, vec=2 )

!   create subscripts for the mesh velocity
    call create_subscript ( mesh_np1, problem, velx, physqarr=[2], degfd=1 )
    call create_subscript ( mesh_np1, problem, vely, physqarr=[2], degfd=2 )
    call create_subscript ( mesh_np1, problem, velz, physqarr=[2], degfd=3 )

!   create system vectors (solution and right-hand side) for conformation and
    call create ( problemc, solc_np1, solc_n, solc_nm1, rhsc )

!   create system matrix for the upg problem
    call create_sysmatrix_structure_base ( sysmatrix, mesh_np1, problem )
    call create_sysmatrix_structure_constraint ( sysmatrix, mesh_np1, problem )
    call finalize_sysmatrix_structure ( sysmatrix )
    call create_sysmatrix_data ( sysmatrix )

!   create system matrix for the ve problem
    call create_sysmatrix_structure_base ( sysmatrixc, mesh_np1, problemc )
    call create_sysmatrix_structure_constraint ( sysmatrixc, mesh_np1, &
      problemc )
    call finalize_sysmatrix_structure ( sysmatrixc )
    call create_sysmatrix_data ( sysmatrixc )

!   initialize all vectors to zero
    sol_nm1%u = 0.0_dp
    solc_nm1(1,1)%u = 0.0_dp
    solc_nm1(2,1)%u = 0.0_dp
    solc_nm1(3,1)%u = 0.0_dp
    sol_n%u = 0.0_dp
    sol_np1%u = 0.0_dp
    solc_n(1,1)%u = 0.0_dp
    solc_n(2,1)%u = 0.0_dp
    solc_n(3,1)%u = 0.0_dp
    meshvel_np1%u = 0.0_dp

!   problem definition for projected "c=exp(s)" of the log conformation s
    call create_input_probdef ( mesh_np1, input_probdefc_projc, nvec=1, &
      nphysq=1 )

    input_probdefc_projc%vec_elementdof(1)%a = &
          reshape ( [ 1,0,1,0,1,0,0,0,0,1 ], &
                      [10,1] )

    input_probdefc_projc%physq = [1]
    input_probdefc_projc%probnr = 3

    call problem_definition ( input_probdefc_projc, mesh_np1, problemc_projc )

    call create ( problemc_projc, solc_projc, rhsc_projc )

    solc_projc(1,1)%u = 1 ! initial cxx
    solc_projc(2,1)%u = 0 ! initial cxy
    solc_projc(3,1)%u = 0 ! initial cxz
    solc_projc(4,1)%u = 1 ! initial cyy
    solc_projc(5,1)%u = 0 ! initial cyz
    solc_projc(6,1)%u = 1 ! initial czz

!   create system matrix for projection problem
    call create_sysmatrix_structure ( sysmatrixc_projc, mesh_np1, &
      problemc_projc, symmetric=.true. )
    call create_sysmatrix_data ( sysmatrixc_projc )

!   create oldvectors
    call create_oldvectors ( oldvectors_ve, nsysvec=2, nsysvec2=3, nprob=3, &
      nvec=2 )
    oldvectors_ve%s(1)%p => sol_n
    oldvectors_ve%s(2)%p => sol_nm1
    oldvectors_ve%s2(1)%p => solc_n
    oldvectors_ve%s2(2)%p => solc_nm1
    oldvectors_ve%s2(3)%p => solc_projc
    oldvectors_ve%p(1)%p => problem
    oldvectors_ve%p(2)%p => problemc
    oldvectors_ve%p(3)%p => problemc_projc
    oldvectors_ve%v(1)%p => meshvel_np1

  end subroutine define_problems_create_vectors


! delete old problem

  subroutine delete_old_problems

    call delete ( problem, problemc )
    call delete ( problem_lapl )
    call delete ( sysmatrix, sysmatrixc )
    call delete ( input_probdef, input_probdefc )
    call delete ( mesh_np1 )
    call delete ( sol_np1, sol_n, sol_nm1 )
    call delete ( solc_np1, solc_n, solc_nm1 )
    call delete ( rhsc )
    call delete ( rhsd )
    call delete ( oldvectors_ve )
    call delete ( meshvel_np1 )
    call delete ( velx, vely, velz )
    call delete ( problemc_projc )
    call delete ( input_probdefc_projc )
    call delete ( solc_projc, rhsc_projc )
    call delete ( sysmatrixc_projc )

!   deallocate volume and aspect ratio arrays
    deallocate ( init_aspect_ratio, aspect_ratio )
    deallocate ( init_volume, volumev )
    deallocate ( meshcoor_n, meshcoor_nm1 )

    if ( ilu%decomp ) call delete ( ilu )

  end subroutine delete_old_problems


! build and solve the up system

  subroutine build_solve_upG

    logical :: initsol
    integer :: nu

    rhsd%u = 0 ! initialize RHS to zero

!   stokes velocity/pressure
    call build_system ( mesh_np1, problem, sysmatrix, rhsd, &
      elemsub=stokes_elem, physqrow=[2,3], physqcol=[2,3], &
      coefficients=coefficients )

!   DEVSS-G
    call build_system ( mesh_np1, problem, sysmatrix, rhsd, &
      elemsub=devssg_elem, addmatvec=.true., &
      physqrow=[1,2], physqcol=[1,2], coefficients=coefficients )

!   set to zero off-diagonal blocks gradient-pressure
    call build_system ( mesh_np1, problem, sysmatrix, rhsd, addmatvec=.true., &
      buildvector=.false., physqrow=[1], physqcol=[3], zeromatvec=.true. )
    call build_system ( mesh_np1, problem, sysmatrix, rhsd, addmatvec=.true., &
      buildvector=.false., physqrow=[3], physqcol=[1], zeromatvec=.true. )

!   constraints on surfaces
    call build_system_constraint ( mesh_np1, problem, sysmatrix, rhsd, &
      constraint1=1, elemsub=elementc_3D, addmatvec=.true. )

!   periodical condition on velocities
    call build_system_constraint ( mesh_np1, problem, sysmatrix, rhsd, &
      constraint1=2, elemsub=stokes_constr_node_conn, addmatvec=.true., &
      coefficients=coefficients )
    call build_system_constraint ( mesh_np1, problem, sysmatrix, rhsd, &
      constraint1=3, elemsub=stokes_constr_node_conn, addmatvec=.true., &
      coefficients=coefficients )

!   build (assemble) vector for gradient/velocity/pressure problem
    if ( step >= 1 ) then

!     exps projection (for log conformation)
      if ( logc == 1 ) then
        call solve_exps_projection
      end if

      call build_system ( mesh_np1, problem, sysmatrix, rhsd, &
        elemsub=divtau_implicit_ce_elem_c, &
        oldvectors=oldvectors_ve, physqrow=[2], physqcol=[2], &
        addmatvec=.true., coefficients=coefficients )
    end if

    call check ( sysmatrix )

    if ( step == 1 ) then
      initsol = .false. ! do not use an initial guess
    else
      initsol=.true. ! use sol_n as an initial guess
      call copy ( sol_n, sol_np1 )
    end if

    call fill_sol_np1 ! essential BCs might change in time

    call add_effect_of_essential_to_rhs ( problem, sysmatrix, sol_np1, rhsd )

!   find the 2-norm of the RHS (which will be used to manually set a relative
!   tolerance)
    nu = problem%numundegfd
    normf = sqrt(dot_product(rhsd%u(:nu),rhsd%u(:nu)))

!   Here the GMRES iterative method is used with an ILU (ILUT) preconditioner.
!   Some comments about the parameters (more info can be found in the type
!   definition solver_options_sk_t / manual of sparsekit):
!   droptol : threshold for dropping small terms in the ILU, decreasing will
!             increase convergence rate, but increases time to compute the ILU,
!             time per mvm and memory usage
!   fillin  : controls the fill-in of the ILU (number elements that were
!             initially zero that became non-zero), increasing will
!             increase convergence rate, but increases time to compute the ILU,
!             time per mvm and memory usage
!   mgmres  : Krylov subspace dimension used in GMRES, increasing might increase
!             convergence rate but also increases time per mvm and memory usage
!   prec_store : reserved space for the ILU, set as low as possible (increase
!                when getting an overflow error)
    call set_solver_options ( solver_options_sk, printlevel=1, &
      type_prec=2, maxmvm=200, itsolver=8, mgmres=100, prec_store=4._dp, &
      preconditioner=1, droptol=1e-4_dp, fillin=5._dp, eps_rel=0._dp, &
      eps_abs=eps_sk*normf, stoponmaxmvm=.false. )

    print *,'Solving upG problem...'

    call solve_system_sk ( sysmatrix, rhsd, sol_np1, ilu=ilu, &
      solver_options=solver_options_sk, maxmvmreached=maxmvmreached, &
      initsol=initsol )

    if ( step == 0 .and. maxmvmreached ) then
      print *,'Error: maximum matrix-vector-multiplications'
      print *,'reached (at initial time step)'
      stop
    end if

    if ( maxmvmreached ) then ! try to solve with a fresh ILU

      call delete ( ilu )

      print *,'Solving upG problem...'

      call copy ( sol_n, sol_np1 )
      call fill_sol_np1 ! essential BCs might change in time

      call solve_system_sk ( sysmatrix, rhsd, sol_np1, ilu=ilu, &
        solver_options=solver_options_sk, maxmvmreached=maxmvmreached, &
        initsol=initsol )

      if ( maxmvmreached ) then
        print *,'Error: maximum matrix-vector-multiplications'
        print *,'reached (using a fresh ILU)'
        stop
      end if

    end if

  end subroutine build_solve_upG


! fill solution vector with essential boundary conditions

  subroutine fill_sol_np1

    vel_upper_wall = (oy + ly) * amp * cos( freq * time )
    vel_lower_wall = oy * amp * cos( freq * time )

!   cell boundaries
    call fill_sysvector ( mesh_np1, problem, sol_np1, surface1=1, &
      physq=physqvel, degfd=1, value=vel_lower_wall )
    call fill_sysvector ( mesh_np1, problem, sol_np1, surface1=1, &
      physq=physqvel, degfd=2, value=0.0_dp )
    call fill_sysvector ( mesh_np1, problem, sol_np1, surface1=1, &
      physq=physqvel, degfd=3, value=0.0_dp )
    call fill_sysvector ( mesh_np1, problem, sol_np1, surface1=3, &
      physq=physqvel, degfd=1, value=vel_upper_wall )
    call fill_sysvector ( mesh_np1, problem, sol_np1, surface1=3, &
      physq=physqvel, degfd=2, value=0.0_dp )
    call fill_sysvector ( mesh_np1, problem, sol_np1, surface1=3, &
      physq=physqvel, degfd=3, value=0.0_dp )

!   point pressure
    call fill_sysvector ( mesh_np1, problem, sol_np1, point=1, &
      physq=physqpress, value=0._dp )

  end subroutine fill_sol_np1


! build and solve the viscoelastic problem

  subroutine build_solve_ve

!   build (assemble) matrix and vector for conformation problem
    if ( step == 1 ) then
      call build_system ( mesh_np1, problemc, sysmatrixc, m2sysvector=rhsc, &
        elemsub=ce_supg_elem, oldvectors=oldvectors_ve, &
        coefficients=coefficients )
    else
      call build_system ( mesh_np1, problemc, sysmatrixc, m2sysvector=rhsc, &
        elemsub=ce_supg_elem_implicit_2nd_order, oldvectors=oldvectors_ve, &
        coefficients=coefficients )
    end if

!   periodical condition on conformation tensor
    call build_system_constraint ( mesh_np1, problemc, sysmatrixc, &
      constraint1=1, m2sysvector=rhsc, elemsub=stokes_constr_node_conn, &
      addmatvec=.true. )
    call build_system_constraint ( mesh_np1, problemc, sysmatrixc, &
      constraint1=2, m2sysvector=rhsc, elemsub=stokes_constr_node_conn, &
      addmatvec=.true. )

    call check ( sysmatrixc )

!   solve conformation and keep LU decomposition in the loop over components
    solver_options_ma41%real_storage=rs_c
    solver_options_ma41%integer_storage=is_c

    do icomp = 1, ncompc
      call solve_system_ma41 ( sysmatrixc, rhsc(icomp,1), solc_np1(icomp,1), &
        luc, solver_options=solver_options_ma41 )
    end do

    call delete ( luc )  ! remove LU decomposition and rebuild next time step

  end subroutine build_solve_ve


! write the data to .vtk files

  subroutine postprocessing ( mesh, sol, solc, ipost, check_proj  )

    type(mesh_t), intent(inout) :: mesh
    type(sysvector_t), intent(in), target :: sol
    type(sysvector_t), dimension(:,:), intent(in), target :: solc
    integer, intent(in), optional :: ipost
    character(len=*), intent(in), optional :: check_proj

    type(oldvectors_t) :: oldvectors_dve
    type(vector_t) :: cxx, cxy, cxz, cyy, cyz, czz, pressure

    if ( .not. mesh%meshparts) call fill_mesh_parts ( mesh )

    call create_oldvectors ( oldvectors_dve, nsysvec=1, nsysvec2=1 )
    oldvectors_dve%s(1)%p => sol

    call create_vector ( problem, pressure, vec=4 )

!   derive the pressure in all nodes
    call derive_vector ( mesh, problem, pressure, &
      elemsub=stokes_pressure, coefficients=coefficients, &
      oldvectors=oldvectors_dve )

    if ( present(ipost) ) write(filename,'(a,i4.4,a)') 'flow', ipost, '.vtk'
    if ( present(check_proj) ) then
      write(filename,'(a,i4.4,a)') 'flow_'//check_proj//'.vtk'
    end if
    call write_scalar_vtk ( mesh, problem, vector=pressure, &
      dataname='pressure',  filename=filename )

    call write_vector_vtk ( mesh, problem, filename=filename, &
      dataname='velocity', sysvector=sol, physq=physqvel, &
      append=.true. )

    oldvectors_dve%s2(1)%p => solc
    call create_vector ( problemc, cxx, vec=2 )
    call create_vector ( problemc, cxy, vec=2 )
    call create_vector ( problemc, cxz, vec=2 )
    call create_vector ( problemc, cyy, vec=2 )
    call create_vector ( problemc, cyz, vec=2 )
    call create_vector ( problemc, czz, vec=2 )

    coefficients%i(13)=1
    call derive_vector ( mesh, problemc, cxx, elemsub=deriv_conformation, &
      coefficients=coefficients, oldvectors=oldvectors_dve )
    coefficients%i(13)=2
    call derive_vector ( mesh, problemc, cxy, elemsub=deriv_conformation, &
      coefficients=coefficients, oldvectors=oldvectors_dve )
    coefficients%i(13)=3
    call derive_vector ( mesh, problemc, cxz, elemsub=deriv_conformation, &
      coefficients=coefficients, oldvectors=oldvectors_dve )
    coefficients%i(13)=4
    call derive_vector ( mesh, problemc, cyy, elemsub=deriv_conformation, &
      coefficients=coefficients, oldvectors=oldvectors_dve )
    coefficients%i(13)=5
    call derive_vector ( mesh, problemc, cyz, elemsub=deriv_conformation, &
      coefficients=coefficients, oldvectors=oldvectors_dve )
    coefficients%i(13)=6
    call derive_vector ( mesh, problemc, czz, elemsub=deriv_conformation, &
      coefficients=coefficients, oldvectors=oldvectors_dve )

    if ( present(ipost) ) write(filename,'(a,i4.4,a)') 'c', ipost, '.vtk'
    if ( present(check_proj) ) then
      write(filename,'(a,i4.4,a)') 'c_'//check_proj//'.vtk'
    end if
    call write_scalar_vtk ( mesh, problemc, vector=cxx, &
      filename=filename, dataname='cxx' )

    call write_scalar_vtk ( mesh, problemc, vector=cxy, &
      filename=filename, dataname='cxy', append=.true. )

    call write_scalar_vtk ( mesh, problemc, vector=cxz, &
      filename=filename, dataname='cxz', append=.true. )

    call write_scalar_vtk ( mesh, problemc, vector=cyy, &
      filename=filename, dataname='cyy', append=.true. )

    call write_scalar_vtk ( mesh, problemc, vector=cyz, &
      filename=filename, dataname='cyz', append=.true. )

    call write_scalar_vtk ( mesh, problemc, vector=czz, &
      filename=filename, dataname='czz', append=.true. )

    call delete(cxx, cxy, cxz, cyy)
    call delete(cyz, czz, pressure)
    call delete(oldvectors_dve)

  end subroutine postprocessing


! P2 project the velocities and coordinates on the new mesh

  subroutine project_old_solutions_P2

    type(input_probdef_t) :: input_probdef_proj
    type(problem_t) :: problem_proj
    type(sysmatrix_t) :: sysmatrix_proj
    type(sysvector_t) :: rhsd_proj(ncompv_P2)
    type(sysvector_t) :: sol_proj(ncompv_P2)
    type(oldvectors_t) :: oldvectors_proj
    type(coefficients_t) :: coefficients_proj
    type(vector_t), target :: vec_p
    type(lu_ma57_t) :: lu2

    type(subscript_t) :: val_proj

    integer :: i

!   create vector for projection
    call create ( problem_temp, vec_p, vec=5 )

!   transfer the coordinates at n
    call transfer_data ( mesh_np1_temp, problem_temp, &
      vector1=coords_n_temp, vector2=vec_p, degfd2=[1,2,3] )

!   transfer the coordinates at n-1
    call transfer_data ( mesh_np1_temp, problem_temp, &
      vector1=coords_nm1_temp, vector2=vec_p, degfd2=[4,5,6] )

!   problem definition for projection
    call create_input_probdef ( mesh_np1, input_probdef_proj )

    input_probdef_proj%elementdof(1)%a = 1
    call problem_definition ( input_probdef_proj, mesh_np1, problem_proj )

!   create system vectors (solution and right-hand side)
    call create ( problem_proj, sol_proj )
    call create ( problem_proj, rhsd_proj )

    call create_subscript ( mesh_np1, problem_proj, val_proj )

!   create system matrix
    call create_sysmatrix_structure ( sysmatrix_proj, mesh_np1, &
      problem_proj, symmetric=.true. )
    call create_sysmatrix_data ( sysmatrix_proj )

!   fill coefficients
    call create_coefficients ( coefficients_proj, ncoefi=100, ncoefr=50 )
    coefficients_proj%i = 0
    coefficients_proj%i(1:4) = [ uintpl, ncompv_P2, uintpl, uintpl ]
    coefficients_proj%i(10) = gauss_proj
    coefficients_proj%i(23) = coorsys
    coefficients_proj%i(40) = inttype_proj
    coefficients_proj%r = 0

!   oldvectors
    call create_oldvectors ( oldvectors_proj, nvec=1, nprob=1, nmesh=1 )
    oldvectors_proj%v(1)%p => vec_p
    oldvectors_proj%p(1)%p => problem_temp
    oldvectors_proj%m(1)%p => mesh_np1_temp

!   build (assemble) matrix and vector from elements
    call build_system ( mesh_np1, problem_proj, sysmatrix_proj, &
      msysvector=rhsd_proj, elemsub=projection_elem, &
      coefficients=coefficients_proj, oldvectors=oldvectors_proj )

!   solve the projection problem
    do i = 1, ncompv_P2
      call add_effect_of_essential_to_rhs ( problem_proj, sysmatrix_proj, &
       sol_proj(i), rhsd_proj(i) )
      call solve_system_ma57 ( sysmatrix_proj, rhsd_proj(i), sol_proj(i), &
        lu=lu2 )
    end do

!   create meshes at t_n and t_nm1 and update the old coordinates
!   note: subscripts in the projection problem are necessary because of the
!   metis renumbering of nodes
    meshcoor_n(:,1) = sol_proj(1)%u(val_proj%s)
    meshcoor_n(:,2) = sol_proj(2)%u(val_proj%s)
    meshcoor_n(:,3) = sol_proj(3)%u(val_proj%s)
    meshcoor_nm1(:,1) = sol_proj(4)%u(val_proj%s)
    meshcoor_nm1(:,2) = sol_proj(5)%u(val_proj%s)
    meshcoor_nm1(:,3) = sol_proj(6)%u(val_proj%s)

!   delete definitions used for the projection problem
    call delete ( lu2 )
    call delete( input_probdef_proj )
    call delete( problem_proj )
    call delete( sysmatrix_proj )
    call delete( rhsd_proj )
    call delete( sol_proj )
    call delete( oldvectors_proj )
    call delete( coefficients_proj )
    call delete( vec_p )
    call delete( val_proj )

  end subroutine project_old_solutions_P2


! P1 project the conformation components and velocity gradients on the new mesh

  subroutine project_old_solutions_P1

    type(input_probdef_t) :: input_probdef_proj
    type(problem_t) :: problem_proj
    type(sysmatrix_t) :: sysmatrix_proj
    type(sysvector_t) :: rhsd_proj(ncompv_P1)
    type(sysvector_t) :: sol_proj(ncompv_P1)
    type(oldvectors_t) :: oldvectors_proj
    type(coefficients_t) :: coefficients_proj
    type(vector_t), target :: vec_p
    type(lu_ma57_t) :: lu2

    type(subscript_t) :: cc
    type(subscript_t) :: val_proj

    integer :: i

!   create vector for projection
    call create ( problemc_temp, vec_p, vec=3 )

!   transfer the conformation tensor at n
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_n_temp(1,1), vector2=vec_p, physq1=[1], degfd2=[1] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_n_temp(2,1), vector2=vec_p, physq1=[1], degfd2=[2] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_n_temp(3,1), vector2=vec_p, physq1=[1], degfd2=[3] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_n_temp(4,1), vector2=vec_p, physq1=[1], degfd2=[4] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_n_temp(5,1), vector2=vec_p, physq1=[1], degfd2=[5] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_n_temp(6,1), vector2=vec_p, physq1=[1], degfd2=[6] )

!   transfer the conformation tensor at n-1
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_nm1_temp(1,1), vector2=vec_p, physq1=[1], degfd2=[7] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_nm1_temp(2,1), vector2=vec_p, physq1=[1], degfd2=[8] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_nm1_temp(3,1), vector2=vec_p, physq1=[1], degfd2=[9] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_nm1_temp(4,1), vector2=vec_p, physq1=[1], degfd2=[10] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_nm1_temp(5,1), vector2=vec_p, physq1=[1], degfd2=[11] )
    call transfer_data ( mesh_np1_temp, problemc_temp, &
      sysvector1=solc_nm1_temp(6,1), vector2=vec_p, physq1=[1], degfd2=[12] )

!   problem definition for projection
    call create_input_probdef ( mesh_np1, input_probdef_proj )

    input_probdef_proj%elementdof(1)%a = [1,0,1,0,1,0,0,0,0,1]
    call problem_definition ( input_probdef_proj, mesh_np1, problem_proj )

!   create system vectors (solution and right-hand side)
    call create ( problem_proj, sol_proj )
    call create ( problem_proj, rhsd_proj )

    call create_subscript ( mesh_np1, problem_proj, val_proj )

!   create system matrix
    call create_sysmatrix_structure ( sysmatrix_proj, mesh_np1, &
      problem_proj, symmetric=.true. )
    call create_sysmatrix_data ( sysmatrix_proj )

!   fill coefficients
    call create_coefficients ( coefficients_proj, ncoefi=100, ncoefr=50 )
    coefficients_proj%i = 0
    coefficients_proj%i(1:4) = [ gintpl, ncompv_P1, uintpl, gintpl ]
    coefficients_proj%i(10) = gauss_proj
    coefficients_proj%i(23) = coorsys
    coefficients_proj%i(40) = inttype_proj
    coefficients_proj%r = 0

!   oldvectors
    call create_oldvectors ( oldvectors_proj, nvec=1, nprob=1, nmesh=1 )
    oldvectors_proj%v(1)%p => vec_p
    oldvectors_proj%p(1)%p => problemc_temp
    oldvectors_proj%m(1)%p => mesh_np1_temp

!   build (assemble) matrix and vector from elements
    call build_system ( mesh_np1, problem_proj, sysmatrix_proj, &
      msysvector=rhsd_proj, elemsub=projection_elem, &
      coefficients=coefficients_proj, oldvectors=oldvectors_proj )

!   solve the projection problem
    do i = 1, ncompv_P1
      call add_effect_of_essential_to_rhs ( problem_proj, sysmatrix_proj, &
       sol_proj(i), rhsd_proj(i) )
      call solve_system_ma57 ( sysmatrix_proj, rhsd_proj(i), sol_proj(i), &
        lu=lu2 )
    end do

!   update the conformation tensor
!   note: because a subscript to the conformation tensor is not needed in the
!   main part of the program, a subscript is created here 'on the fly' and
!   deleted after it is used.
!   note2: subscripts in the projection problem are necessary because of the
!   metis renumbering of nodes
    call create_subscript ( mesh_np1, problemc, cc, physqarr=[1] )
    solc_n(1,1)%u(cc%s) = sol_proj(1)%u(val_proj%s)
    solc_n(2,1)%u(cc%s) = sol_proj(2)%u(val_proj%s)
    solc_n(3,1)%u(cc%s) = sol_proj(3)%u(val_proj%s)
    solc_n(4,1)%u(cc%s) = sol_proj(4)%u(val_proj%s)
    solc_n(5,1)%u(cc%s) = sol_proj(5)%u(val_proj%s)
    solc_n(6,1)%u(cc%s) = sol_proj(6)%u(val_proj%s)
    solc_nm1(1,1)%u(cc%s) = sol_proj(7)%u(val_proj%s)
    solc_nm1(2,1)%u(cc%s) = sol_proj(8)%u(val_proj%s)
    solc_nm1(3,1)%u(cc%s) = sol_proj(9)%u(val_proj%s)
    solc_nm1(4,1)%u(cc%s) = sol_proj(10)%u(val_proj%s)
    solc_nm1(5,1)%u(cc%s) = sol_proj(11)%u(val_proj%s)
    solc_nm1(6,1)%u(cc%s) = sol_proj(12)%u(val_proj%s)
    call delete ( cc )

!   delete definitions used for the projection problem
    call delete ( lu2 )
    call delete( input_probdef_proj )
    call delete( problem_proj )
    call delete( sysmatrix_proj )
    call delete( rhsd_proj )
    call delete( sol_proj )
    call delete( oldvectors_proj )
    call delete( coefficients_proj )
    call delete( vec_p )
    call delete( val_proj )

  end subroutine project_old_solutions_P1


! project c=exp(s) on discrete fem space
  subroutine solve_exps_projection

    type(solver_options_ma57_t) :: solver_options_ma57

    integer :: i, m

!   build system matrix and vector for projection problem
    call build_system ( mesh_np1, problemc_projc, sysmatrixc_projc, &
      m2sysvector=rhsc_projc, elemsub=exps_projection_elem, &
      oldvectors=oldvectors_ve, coefficients=coefficients )

    call check ( sysmatrixc_projc )

!   MA57 solver storage
    solver_options_ma57%integer_storage = 1.3
    solver_options_ma57%real_storage    = 1.3

!   LU decomposition is done in the first loop traversing
    do m = 1, nmodes
      do i = 1, ncompc

        call add_effect_of_essential_to_rhs ( problemc_projc, sysmatrixc_projc, &
           solc_projc(i,m), rhsc_projc(i,m) )

        call solve_system_ma57 ( sysmatrixc_projc, rhsc_projc(i,m), &
           solc_projc(i,m), lu_exps_projc, solver_options=solver_options_ma57 )

      end do
    end do

    call delete ( lu_exps_projc )

  end subroutine solve_exps_projection

end program ale14

#else
  print '(4(a/),a)', &
    'To run this example:', &
    ' - compile add-ons sk_solve and metis5', &
    ' - install and compile sparskit2', &
    ' - add metis5 lib for linking', &
    ' - set preprocessing macro SKIT2 and METIS5 in Mdefs.mk'
end
#endif
