! Viscoelastic problem:
! Oscillating Couette flow with a freely floating solid particle
! DEVSS-G/SUPG
! Implicit bilinear terms of CE in momentum balance.
! second-order time integration
! ALE body-fitting mesh scheme
! Mesh generated by Gmsh using triangles

program ale2

  use tfem_m
  use hsl_ma41_m
  use viscoelastic_elements_m
  use figplot_m
  use io_utils_m
  use subs1_m
  use update_mesh_nodes1_m

  implicit none

  integer, parameter :: &
    uintpl = 6,     &  ! P2 velocities
    pintpl = 2,     &  ! P1 pressures
    gintpl = 2,     &  ! P1 gradients
    cintpl = 2,     &  ! P1 conformation
    physqgrad = 1,  &  ! physical quantity nr of the gradients
    physqvel = 2,   &  ! physical quantity nr of the velocities
    physqpress = 3, &  ! physical quantity nr of the pressures
    gauss = 6,      &  ! 6-point Gauss integration of triangles
    gaussb = 3,     &  ! 3 point integration of boundary elements
    ncompc = 3,     &  ! number of conformation tensor components
    nmodes = 1,     &  ! number of modes
    startm = 501,   &  ! start of material model data
    coorsys = 0,    &  ! coordinate system
    model = 3          ! Giesekus model

! definitions

  type(mesh_t) :: mesh, mesh1
  type(input_probdef_t) :: input_probdef, input_probdefc
  type(problem_t), target :: problem, problemc
  type(sysmatrix_t) :: sysmatrix, sysmatrixc
  type(sysvector_t), target :: sol, solm1
  type(sysvector_t) :: rhsd
  type(oldvectors_t) :: oldvectors_ve
  type(coefficients_t) :: coefficients
  type(sysvector_t), dimension(ncompc,nmodes), target :: solc, solcm1
  type(sysvector_t), dimension(ncompc,nmodes) :: rhsc
  type(lu_ma41_t) :: luc
  type(plot_options_t) :: plot_options
  type(vector_t) :: velocity
  type(vector_t), target :: meshvel
  type(solver_options_ma41_t) :: solver_options_ma41
  type(subscriptvec_t) :: meshvelx, meshvely

  type(problem_t) :: problem_pois
  type(sysvector_t), dimension(2) :: sol_pois

  real(dp) :: oy, lx, ly, vel_lower_wall, vel_upper_wall
  real(dp) :: unm1(3), un(3), pp(3), upr(3)

! variables

  integer :: &
    timeint1 = 1,         & ! (first-order) time integration
    timeint2 = 7,         & ! (second-order) time integration
    numtimesteps = 1000,  & ! number of time steps
    ipost = 0,            & !
    logc = 1                ! standard scheme or log transformation

  real(dp) :: &
    eta_s = 0.1_dp,     & ! solvent viscosity
    eta_p = 1.0_dp,     & ! polymer viscosity
    lambda = 1.0_dp,    & ! relaxation time
    mobility = 0.2_dp,  & ! mobility parameter in the Giesekus model (alpha)
    amp = 1.0_dp,       & ! amplitude of the imposed sinusoidal shear rate
    freq = 1.0_dp,      & ! frequency of the imposed sinusoidal shear rate
    time = 0.0_dp,      & ! initial time
    deltat = 0.02_dp,   & ! time step
    beta = 1.0_dp,      & ! upwinding parameter in the SUPG method
    rs_gup = 1.4_dp,    & ! real_storage gradient-velocity-pressure LU (HSL)
    is_gup = 1.5_dp,    & ! integer_storage gradient-velocity-pressure LU (HSL)
    rs_c  = 1.4_dp,     & ! real_storage for the conformation LU (HSL)
    is_c  = 1.6_dp        ! integer_storage for conformation LU (HSL)

  integer :: icomp, step, i
  real(dp) :: alpha, G

  character(len=30) :: filename

  open (unit = 100, file='output.out')

! set some parameters
  alpha = eta_p         ! DEVSS parameter
  G = eta_p / lambda    ! modulus

! fill coefficients
  call create_coefficients ( coefficients, ncoefi=150, ncoefr=500+3*nmodes )

  coefficients%i = &
    [ uintpl,   pintpl,     0,     0,         gintpl, &
      physqvel, physqpress, 0,     physqgrad, gauss,  &
      gaussb,   cintpl,     0,     0,         0,      &
      0,        0,          model, nmodes,    startm, &
      logc,     timeint1,    coorsys, ( 0, i = 24, 150 )  &
    ]

  coefficients%i(48) = 1 ! use mesh velocity for ALE formulation

  coefficients%r(1:502) = &
    [ eta_s,    0._dp,   0._dp,   alpha, 0._dp, &
      0._dp, 0._dp,  deltat,   beta,  0._dp, &
      ( 0._dp, i = 11, 500 ), &
      G,     lambda  &
    ]

  if ( model == 3 ) then
    coefficients%r(503) = mobility
  end if

! mesh parameters
  oy = -0.5_dp
  lx =  2.0_dp
  ly =  1.0_dp

! one particle
  rp = 0.1_dp          ! particle radius
  xp(1) = 0.0_dp       ! x-position of the particle
  xp(2) = 0.1_dp       ! y-position of the particle

  pp = [ (xp(i),i=1,2), 0._dp ]

! read P2 and P1 gmsh mesh
  call read_mesh_gmsh ( mesh, filename='mesh_yp0_1_P2.msh', ndim=2, &
    physgeom=.true. )
  call read_mesh_gmsh ( mesh1, filename='mesh_yp0_1_P1.msh', ndim=2, &
    physgeom=.true. )

! add objectcurve = 2 (used for periodical bc of velocity)
  call add_to_mesh ( mesh, object='curve', objectcurve=2, &
    excludepoints=[2,3] )
  call add_to_mesh ( mesh, object='curve', objectcurve=2, &
    excludepoints=[2,3] )
  mesh%objects(2)%coor(:,1) = mesh%objects(2)%coor(:,1) - lx

! add objectcurve = 2 of mesh1 based on P1 elements (used for periodical bc of
! conformation)
  call add_to_mesh ( mesh, object='curve', objectcurve=2, objectmesh=mesh1 )
  call add_to_mesh ( mesh, object='curve', objectcurve=2, objectmesh=mesh1 )
  mesh%objects(4)%coor(:,1) = mesh%objects(4)%coor(:,1) - lx

  call delete ( mesh1)

  call fill_mesh_parts ( mesh )

! plot mesh
  plot_options%fontsize = 6
  call plot_points_curves ( plot_options, mesh, 'curves.fig' )
  plot_options%fontsize = 10
  call plot_mesh ( plot_options, mesh, 'mesh.fig' )

! problem definition of gradient/velocity/pressure
  call create_input_probdef ( mesh, input_probdef, nvec=5, nphysq=3 )

  input_probdef%vec_elementdof(1)%a =   &
      reshape ( [ 4,0,4,0,4,0,    &  ! G
                  2,2,2,2,2,2,    &  ! velocity
                  1,0,1,0,1,0,    &  ! pressure
                  1,1,1,1,1,1,    &  ! scalar, such as vorticity
                  3,3,3,3,3,3 ], &  ! tensor
                  [6,5] )
  input_probdef%physq = [1,2,3]
  input_probdef%probnr = 1

! cell boundaries
  call define_essential ( mesh, input_probdef, curve1=1, physq=2 )
  call define_essential ( mesh, input_probdef, curve1=3, physq=2 )

  call define_essential ( mesh, input_probdef, point=1, physq=3 )

! constraint on particle boundary (freely floating)
  call define_constraint ( mesh, input_probdef, curve1=5, physq=2, &
    discretization='collocation', nodedof=2, naddunknowns=3 )

! periodic velocities
  call define_constraint ( mesh, input_probdef, &
    physq=physqvel, object=1, object2=2, discretization='collocation', &
    nodedof=2 )

  call problem_definition ( input_probdef, mesh, problem )

! create subscript for the mesh velocity vector

  call create_subscript_vector ( mesh, problem, meshvelx, vec=2, degfd=1 )
  call create_subscript_vector ( mesh, problem, meshvely, vec=2, degfd=2 )

! problem definition conformation tensor
  call create_input_probdef ( mesh, input_probdefc, nvec=3, nphysq=1 )

  input_probdefc%vec_elementdof(1)%a =   &
      reshape ( [ 1,0,1,0,1,0,    &  ! c
                  1,1,1,1,1,1,    &  ! scalar for plotting
                  3,3,3,3,3,3 ], &  ! tensor
                  [6,3] )

  input_probdefc%physq = [1]
  input_probdefc%probnr = 2

! periodic conformation
  call define_constraint ( mesh, input_probdefc, &
    object=3, object2=4, discretization='collocation', nodedof=1 )

  call problem_definition ( input_probdefc, mesh, problemc )


! create system vectors (solution and right-hand side)
  call create_sysvector ( problem, sol, solm1, rhsd )

! create mesh velocity vectors
  call create ( problem, meshvel, vec=2 )
  meshvel%u = 0 ! set mesh velocity to zero for first time step

! create system matrix of gradient/velocity/pressure problem
  call create_sysmatrix_structure_base ( sysmatrix, mesh, problem )
  call create_sysmatrix_structure_constraint ( sysmatrix, mesh, problem )
  call finalize_sysmatrix_structure ( sysmatrix )

  call create_sysmatrix_data ( sysmatrix )

! create system vectors (solution and right-hand side) for conformation and
! initialize vectors with zero stress
  call create ( problemc, solc, solcm1, rhsc )

  if ( logc == 0 ) then ! standard
    solc(1,1)%u = 1   ! initial cxx
    solc(2,1)%u = 0   ! initial cxy
    solc(3,1)%u = 1   ! initial cyy
  else if ( logc == 1 ) then ! log scheme
    solc(1,1)%u = 0   ! initial sxx
    solc(2,1)%u = 0   ! initial sxy
    solc(3,1)%u = 0   ! initial syy
  end if

! create system matrix for conformation problem
  call create_sysmatrix_structure_base ( sysmatrixc, mesh, problemc )
  call create_sysmatrix_structure_constraint ( sysmatrixc, mesh, problemc )
  call finalize_sysmatrix_structure ( sysmatrixc )

  call create_sysmatrix_data ( sysmatrixc )

! create oldvectors

  call create_oldvectors ( oldvectors_ve, nsysvec=2, nsysvec2=2, nprob=2, &
    nvec=1 )

! store solution vectors and problem structures

  oldvectors_ve%s(1)%p => sol
  oldvectors_ve%s(2)%p => solm1
  oldvectors_ve%s2(1)%p => solc
  oldvectors_ve%s2(2)%p => solcm1
  oldvectors_ve%p(1)%p => problem
  oldvectors_ve%p(2)%p => problemc
  oldvectors_ve%v(1)%p => meshvel


! time stepping

  do step = 1, numtimesteps

    time = time + deltat

!   change the integration order
    if ( step >= 2) then
      coefficients%i(22) = timeint2
    end if

    if ( step >= 2 ) then

!     advance particle position (based on previous step)
      if ( step == 2 ) then
!       advance with forward Euler
        call get_sysvector_constraint ( mesh, problem, sol, constraint=1, &
          addunknowns=.true., u=un )
        pp = pp + deltat*un
      else
!       advance with 2nd order Adams-Bashforth
        unm1 = un
        call get_sysvector_constraint ( mesh, problem, sol, constraint=1, &
          addunknowns=.true., u=un )
        pp = pp + deltat*(3*un/2 - unm1/2)
      end if
      xp = pp(1:2)

    end if

!   update mesh nodes: solve a Laplace's equation (after the second step)

    if ( step == 2 ) then

      call update_mesh_nodes ( mesh, problem_pois, un(1:2), deltat, sol_pois, &
        method=1 )

    else if ( step > 2 ) then

      call update_mesh_nodes ( mesh, problem_pois, un(1:2), deltat, sol_pois, &
        method=2 )

    end if

!   copy the mesh velocity from sol_pois to the vector meshvel
!   NOTE: meshvel will be used in the element routines to take into account
!   the mesh velocity.

    if ( step >= 2 ) then

      meshvel%u(meshvelx%s) = sol_pois(1)%u(problem_pois%degfdperm(:,2))
      meshvel%u(meshvely%s) = sol_pois(2)%u(problem_pois%degfdperm(:,2))

    end if

    call copy ( sol, solm1 )

!   find new velocity-pressure solution

    vel_upper_wall = (oy + ly) * amp * cos( freq * time )
    vel_lower_wall = oy * amp * cos( freq * time )

    call fill_sysvector ( mesh, problem, sol, curve1=1, physq=2, degfd=1, &
      value=vel_lower_wall )
    call fill_sysvector ( mesh, problem, sol, curve1=1, physq=2, degfd=2, &
      value=0.0_dp )
    call fill_sysvector ( mesh, problem, sol, curve1=3, physq=2, degfd=1, &
      value=vel_upper_wall )
    call fill_sysvector ( mesh, problem, sol, curve1=3, physq=2, degfd=2, &
      value=0.0_dp )

    call fill_sysvector ( mesh, problem, sol, point=1, physq=3, value=0._dp )

    call build_vpG

    call check ( sysmatrix )

!   build implicit terms of CE with rhs in momentum balance

    call build_system ( mesh, problem, sysmatrix, rhsd, &
      elemsub=divtau_implicit_ce_elem_c, &
      oldvectors=oldvectors_ve, physqrow=[2], physqcol=[2], &
      addmatvec=.true., coefficients=coefficients )

    call check ( sysmatrix )

    call add_effect_of_essential_to_rhs ( problem, sysmatrix, sol, rhsd )

!   solve gradient/velocity/pressure problem

    solver_options_ma41%real_storage=rs_gup
    solver_options_ma41%integer_storage=is_gup

    call solve_system_ma41 ( sysmatrix, rhsd, sol, &
      solver_options=solver_options_ma41  )

!   build (assemble) matrix and vector for conformation problem

    if ( coefficients%i(22) == timeint1 ) then

      call build_system ( mesh, problemc, sysmatrixc, m2sysvector=rhsc, &
        elemsub=ce_supg_elem, oldvectors=oldvectors_ve, &
        coefficients=coefficients )

    else

      call build_system ( mesh, problemc, sysmatrixc, m2sysvector=rhsc, &
        elemsub=ce_supg_elem_implicit_2nd_order, oldvectors=oldvectors_ve, &
        coefficients=coefficients )

    end if

!   periodical condition on conformation tensor
    call build_system_constraint ( mesh, problemc, sysmatrixc, &
      m2sysvector=rhsc, elemsub=constraints_object_conn_P1, addmatvec=.true. )

    call check ( sysmatrixc )

    call copy ( solc, solcm1 )

!   solve conformation and keep LU decomposition in the loop over components
    solver_options_ma41%real_storage=rs_c
    solver_options_ma41%integer_storage=is_c

    do icomp = 1, ncompc
      call solve_system_ma41 ( sysmatrixc, rhsc(icomp,1), solc(icomp,1), luc, &
        solver_options=solver_options_ma41 )
    end do

    call delete ( luc )  ! remove LU decomposition and rebuild next time step

    print *,'**************************************************************'
    print *,'Step: ', step
    print *,'Time: ', time

    call get_sysvector_constraint ( mesh, problem, sol, constraint=1, &
      addunknowns=.true., u=upr )

    print *,'x-position of the particle: ',pp(1)
    print *,'y-position of the particle: ',pp(2)
    print *,'x-velocity of the particle: ', upr(1)
    print *,'y-velocity of the particle: ', upr(2)
    print *,'Rotation rate of the particle: ', upr(3)

    write(100,'(1X,F10.4,6F16.8)') time, pp, upr

!   write VTK files

    if ( mod(step-1,10000) == 0 ) then

      ipost = ipost + 1
      call create_vector ( problem, velocity, physq=2)
      call extract_physvector ( mesh, problem, sol, velocity)
      write(filename,'(a,i4.4,a)') 'velocity', ipost, '.vtk'
      call write_vector_vtk ( mesh, problem, filename=filename, &
        dataname='velocity', vector=velocity)

      call delete ( velocity )

    end if

  end do

! clear memory

  call delete ( mesh )
  call delete ( input_probdef, input_probdefc )
  call delete ( problem, problemc )
  call delete ( sol, solm1, rhsd )
  call delete ( oldvectors_ve )
  call delete ( coefficients )
  call delete ( solc, solcm1, rhsc )
  call delete ( meshvelx, meshvely )
  call delete ( problem_pois )
  call delete ( sol_pois )
  call delete ( meshvel )
  call delete ( sysmatrix )
  call delete ( sysmatrixc )

contains

  subroutine build_vpG

!   build (assemble) matrix and vector for gradient/velocity/pressure problem

!   stokes velocity/pressure
    call build_system ( mesh, problem, sysmatrix, rhsd, &
      elemsub=stokes_elem, physqrow=[2,3], physqcol=[2,3], &
      coefficients=coefficients )

!   DEVSS-G
    call build_system ( mesh, problem, sysmatrix, rhsd, &
      elemsub=devssg_elem, addmatvec=.true., &
      physqrow=[1,2], physqcol=[1,2], coefficients=coefficients )

!   set to zero off-diagonal blocks gradient-pressure
    call build_system ( mesh, problem, sysmatrix, rhsd, addmatvec=.true., &
      buildvector=.false., physqrow=[1], physqcol=[3], zeromatvec=.true. )
    call build_system ( mesh, problem, sysmatrix, rhsd, addmatvec=.true., &
      buildvector=.false., physqrow=[3], physqcol=[1], zeromatvec=.true. )

!   constraints on objects
    call build_system_constraint ( mesh, problem, sysmatrix, rhsd, &
      constraint1=1, elemsub=elementc, addmatvec=.true. )

!   periodical condition on velocities
    call build_system_constraint ( mesh, problem, sysmatrix, rhsd, &
      constraint1=2, elemsub=constraints_object_conn_P2, addmatvec=.true., &
      coefficients=coefficients )

  end subroutine build_vpG

end program ale2
