! Navier-Stokes problem:
! Oscillating Couette flow with a freely floating solid particle
! Neutrally buoyant particle ( density of particle = density of fluid )
! Second-order implicit Gear discretization. First step: Euler implicit.
! ALE body-fitting mesh scheme
! Particle updater uses a second-order AB2 scheme
! Mesh generated by Gmsh using triangles

program ale3

  use tfem_m
  use math_defs_m
  use hsl_ma41_m
  use stokes_elements_m
  use inertia_elements_m
  use io_utils_m
  use figplot_m
  use subs1_m
  use update_mesh_nodes3_m

  implicit none

! constants

 integer, parameter :: &
    uintpl = 6,             & ! P2 velocities
    pintpl = 2,             & ! P1 pressures
    physqvel = 1,           & ! physical quantity nr of the velocities
    physqpress = 2,         & ! physical quantity nr of the pressures
    gauss = 6,              & ! 6-point Gauss integration of triangles
    gaussb = 3,             & ! 3 point integration of boundary elements
    numtimesteps = 1000,    & ! number time steps
    numeulertimesteps = 1,  & ! number Euler time steps (at least one!)
    maxnumiterations = 100, & ! maximum number of iterations allowed to obtain
                              ! convergence
    num_picard = 1            ! number of Picard iterations, followed by Newton
                              ! iterations

  real(dp), parameter :: &
    eta = 1._dp,            & ! viscosity
    rho = 100._dp,          & ! fluid density
    rho_p = 100._dp,        & ! particle density
    amp = 1.0_dp,           & ! amplitude of the imposed sinusoidal shear rate
    freq = 1.0_dp,          & ! frequency of the imposed sinusoidal shear rate
    deltat = 0.02_dp,       & ! time step
    thresh = 1.e-8_dp         ! threshold for the iteration process


! definitions

  type(mesh_t) :: mesh
  type(input_probdef_t) :: input_probdef
  type(problem_t), target :: problem
  type(sysmatrix_t) :: sysmatrix, sysmatrix_stored
  type(sysvector_t), target :: sol_iter, soln, sol_hat
  type(sysvector_t) :: sol, solnm1, rhsd, rhsd_stored
  type(vector_t) :: velocity
  type(plot_options_t) :: plot_options
  type(oldvectors_t) :: oldvectors, oldvectors_hat, oldvectors_iter
  type(coefficients_t) :: coefficients
  type(subscript_t) :: vel, pres
  type(vector_t), target :: meshvel
  type(subscriptvec_t) :: meshvelx, meshvely

  type(problem_t) :: problem_pois

  integer :: i, step, iterstep, ipost=0
  real(dp) :: mass, moment, up_hat(3)
  real(dp) :: diffv, diffp, mfac, tn, tnp1
  real(dp) :: gamma0=1.5_dp, alpha0=2._dp, alpha1=-0.5_dp

  real(dp) :: oy, lx, ly, vel_lower_wall, vel_upper_wall
  real(dp) :: up(3), unm1(3), un(3), pp(3), ppn(3), matdiag(3), vec(3)

  real(dp), allocatable, dimension(:,:) :: meshcoor_n, meshcoor_nm1

  character(len=30) :: filename

  open (unit = 100, file='output.out')

! fill coefficients
  call create_coefficients ( coefficients, ncoefi=250, ncoefr=200 )

  coefficients%i = 0
  coefficients%i(1:11) = &
    [ uintpl,   pintpl,     0,     0,         0,  &
      physqvel, physqpress, 0,     0,     gauss,  &
      gaussb ]

  coefficients%i(48) = 1 ! use mesh velocity for ALE formulation

  coefficients%r = 0
  coefficients%r(1) = eta
  coefficients%r(8) = deltat
  coefficients%r(151) = rho

  call write_coefficients ( coefficients, filename='coefficients.out' )

! mesh parameters
  oy = -0.5_dp
  lx =  2.0_dp
  ly =  1.0_dp

! one particle
  rp = 0.1_dp          ! particle radius
  xp(1) = 0.0_dp       ! x-position of the particle
  xp(2) = 0.1_dp       ! y-position of the particle

  pp = [ (xp(i),i=1,2), 0._dp ]

! read P2 gmsh mesh
  call read_mesh_gmsh ( mesh, filename='mesh_yp0_1_P2.msh', ndim=2, &
    physgeom=.true. )

! add objectcurve = 2
  call add_to_mesh ( mesh, object='curve', objectcurve=2, &
    excludepoints=[2,3] )
  call add_to_mesh ( mesh, object='curve', objectcurve=2, &
    excludepoints=[2,3] )
  mesh%objects(2)%coor(:,1) = mesh%objects(2)%coor(:,1) - lx

  call fill_mesh_parts ( mesh )

! plot mesh
  plot_options%fontsize = 6
  call plot_points_curves ( plot_options, mesh, 'curves.fig' )
  plot_options%fontsize = 10
  call plot_mesh ( plot_options, mesh, 'mesh.fig' )

! problem definition

  call create_input_probdef ( mesh, input_probdef, nvec=3, nphysq=2 )

  input_probdef%vec_elementdof(1)%a =   &
      reshape ( [2,2,2,2,2,2,    &  ! velocity
                 1,0,1,0,1,0,    &  ! pressure
                 1,1,1,1,1,1 ], &  ! scalar, such as vorticity
                  [6,3] )

  input_probdef%physq = [1,2]

! cell boundaries
  call define_essential ( mesh, input_probdef, curve1=1, physq=1 )
  call define_essential ( mesh, input_probdef, curve1=3, physq=1 )

  call define_essential ( mesh, input_probdef, point=1, physq=2 )

! constraint on particle boundary (freely floating)
  call define_constraint ( mesh, input_probdef, curve1=5, physq=1, &
    discretization='collocation', nodedof=2, naddunknowns=3 )

! periodic velocities
  call define_constraint ( mesh, input_probdef, &
    physq=physqvel, object=1, object2=2, discretization='collocation', &
    nodedof=2 )

  call problem_definition ( input_probdef, mesh, problem )

! create system vectors (solution and right-hand side)

  call create_sysvector ( problem, sol, sol_iter, soln )
  call create_sysvector ( problem, solnm1, sol_hat )
  call create_sysvector ( problem, rhsd, rhsd_stored )

! define some arrays the ALE mesh position at old times

  allocate ( meshcoor_n(mesh%nnodes,2), meshcoor_nm1(mesh%nnodes,2) )
  meshcoor_n = mesh%coor
  meshcoor_nm1 = mesh%coor

! create mesh velocity vectors
  call create ( problem, meshvel, vec=1 )

! define vector subscripts for direct manipulation of sysvector data

! velocities
  call create_subscript ( mesh, problem, vel, physqarr=[1] )
! pressures
  call create_subscript ( mesh, problem, pres, physqarr=[2] )

! create subscript for the mesh velocity vector

  call create_subscript_vector ( mesh, problem, meshvelx, vec=1, degfd=1 )
  call create_subscript_vector ( mesh, problem, meshvely, vec=1, degfd=2 )

! create the structure oldvectors

  call create_oldvectors ( oldvectors, nsysvec=1 )
  call create_oldvectors ( oldvectors_hat, nsysvec=1 )
  call create_oldvectors ( oldvectors_iter, nsysvec=1, nprob=1, nvec=1 )

! set initial value of solution to zero

  soln%u = 0._dp
  sol_iter%u = soln%u
  up = 0._dp

! fill oldvectors

  oldvectors%s(1)%p => soln
  oldvectors_hat%s(1)%p => sol_hat  ! alpha0*un+alpha1*un-1
  oldvectors_iter%s(1)%p => sol_iter ! solution at end of previous iteration
  oldvectors_iter%p(1)%p => problem
  oldvectors_iter%v(1)%p => meshvel

! start time integration

  tn = 0

  integration: do step = 1, numtimesteps

    tnp1 = tn + deltat

    write(*,'(/a,i0,a,es12.4,a/)') ' ** time step = ', step, &
                                   ' time = ', tnp1, ' ** '

    meshcoor_nm1 = meshcoor_n
    meshcoor_n = mesh%coor

    if ( step == 1 ) then

      un = up  ! In the current problem up=0 at t=0

      ppn = pp
      pp = pp + deltat * up  ! In the current problem up=0 at t=0

    else if ( step >= 2 ) then

!     advance particle position with 2nd order Adams-Bashforth

      unm1 = un
      un = up
      ppn = pp

      pp = pp + deltat*(3*un/2 - unm1/2)

      xp = pp(1:2)

!     update mesh nodes: solve a Laplace's equation

      call update_mesh_nodes ( mesh, problem_pois, pp(1:2)-ppn(1:2) )

    end if

!   compute mesh velocity for tn+1 (Gear)

    if ( step == 1 ) then

!     step=1, particle velocity = 0 and mesh velocity=0

      meshvel%u = 0

    else if ( step >= 2 ) then

!     second-order accurate

      meshvel%u = reshape ( transpose ( &
        ( 1.5_dp*mesh%coor - 2*meshcoor_n + 0.5_dp*meshcoor_nm1 ) / deltat ), &
                         [2*mesh%nnodes] )

    end if


!   create system matrix

    call create_sysmatrix_structure_base ( sysmatrix, mesh, problem )
    call create_sysmatrix_structure_constraint ( sysmatrix, mesh, problem, &
      diagonal_addunknowns=.true. )
    call finalize_sysmatrix_structure ( sysmatrix )
    call create_sysmatrix_data ( sysmatrix )


!   build (assemble) matrix and vector from elements

!   Stokes flow : velocity / pressure
    call build_system ( mesh, problem, sysmatrix, rhsd, elemsub=stokes_elem, &
      coefficients=coefficients )

!   constraint on particle boundary
    call build_system_constraint ( mesh, problem, sysmatrix, rhsd, &
      constraint1=1, elemsub=elementc, addmatvec=.true., &
      coefficients=coefficients )

!   periodical condition on velocities
    call build_system_constraint ( mesh, problem, sysmatrix, rhsd, &
      constraint1=2, elemsub=constraints_object_conn_P2, addmatvec=.true., &
      coefficients=coefficients )

!   build instationary term ( rho du/dt )
    if ( step <= numeulertimesteps ) then
!     implicit Euler
      sol_hat%u(vel%s) = soln%u(vel%s)
      mfac = 1._dp
    else
!     second-order implicit Gear after Euler time steps
      sol_hat%u(vel%s) = alpha0*soln%u(vel%s) + alpha1*solnm1%u(vel%s)
      mfac = gamma0
    end if

    call build_system ( mesh, problem, sysmatrix, rhsd, &
      elemsub=inertia_elem_dudt, &
      coefficients=coefficients, oldvectors=oldvectors_hat, &
      physqcol=[physqvel], physqrow=[physqvel], &
      factormat=mfac, addmatvec=.true. )


!   build particle instationary terms
    mass = rho_p * pi * rp**2
    moment = 0.5 * mass * rp**2

    if ( step <= numeulertimesteps ) then
      ! first order Euler
      up_hat = un
      mfac = 1._dp
    else
      ! second-order BDF2 after Euler time steps
      up_hat = alpha0*un + alpha1*unm1
      mfac = gamma0
    end if

    matdiag(1) = mass * mfac / deltat
    matdiag(2) = mass * mfac / deltat
    matdiag(3) = moment * mfac / deltat

    vec(1) = mass * up_hat(1) / deltat
    vec(2) = mass * up_hat(2) / deltat
    vec(3) = moment * up_hat(3) / deltat

    call build_system_constraint_addunknowns ( mesh, problem, &
      sysmatrix=sysmatrix, sysvector=rhsd, constraint=1, &
      addmatvec=.true., matdiag=matdiag, rhs=vec )


!   store sysmatrix & rhsd for advection iteration

    call create_sysmatrix ( sysmatrix, sysmatrix_stored )
    call copy ( sysmatrix, sysmatrix_stored )
    call copy ( rhsd, rhsd_stored )

!   fill solution vector with essential boundary conditions

    vel_upper_wall = (oy + ly) * amp * cos( freq * tnp1 )
    vel_lower_wall = oy * amp * cos( freq * tnp1 )

    call fill_sysvector ( mesh, problem, sol, curve1=1, physq=1, degfd=1, &
      value=vel_lower_wall )
    call fill_sysvector ( mesh, problem, sol, curve1=1, physq=1, degfd=2, &
      value=0.0_dp )
    call fill_sysvector ( mesh, problem, sol, curve1=3, physq=1, degfd=1, &
      value=vel_upper_wall )
    call fill_sysvector ( mesh, problem, sol, curve1=3, physq=1, degfd=2, &
      value=0.0_dp )

    call fill_sysvector ( mesh, problem, sol, point=1, physq=2, value=0._dp )

!   interation procedure for advection term

    iterstep = 0

    iterate: do

      iterstep = iterstep + 1

      call copy ( sysmatrix_stored, sysmatrix )
      call copy ( rhsd_stored, rhsd )

!     first num_picard steps Picard iteration, then Newton iteration
!     the term un+1.grad un+1
      if ( iterstep <= num_picard ) then
        call build_system ( mesh, problem, sysmatrix, rhsd, &
          elemsub=inertia_elem_conv_picard, coefficients=coefficients, &
          oldvectors=oldvectors_iter, physqcol=[physqvel], &
          physqrow=[physqvel], addmatvec=.true. )
      else
        call build_system ( mesh, problem, sysmatrix, rhsd, &
          elemsub=inertia_elem_conv_newton, coefficients=coefficients, &
          oldvectors=oldvectors_iter, physqcol=[physqvel], &
          physqrow=[physqvel], addmatvec=.true. )
      end if

      call check ( sysmatrix )

      call add_effect_of_essential_to_rhs ( problem, sysmatrix, sol, rhsd )

      call solve_system_ma41 ( sysmatrix, rhsd, sol )

!     compute the difference between iteration steps
      diffv = maxval ( sqrt ( ( sol%u(vel%s) - sol_iter%u(vel%s) )** 2 ) )
      diffp = maxval ( sqrt ( ( sol%u(pres%s) - sol_iter%u(pres%s) )** 2 ) )

      write(*,'(a,i0,2(a,es12.4))') &
        '    iterstep = ', iterstep, ' diffv = ', diffv, ' diffp = ', diffp

      call copy ( sol, sol_iter )

      if ( diffv < thresh ) exit iterate

      if ( iterstep == maxnumiterations ) then
        write(*,'(a,i0)') &
          'Maximum number of iterations reached = ', maxnumiterations
        stop
      end if

    end do iterate

    call delete_sysmatrix ( sysmatrix, sysmatrix_stored )

!   copy the converged solution to the old step

    call copy ( soln, solnm1 )
    call copy ( sol, soln )

!   extract info on particle

    call get_sysvector_constraint ( mesh, problem, soln, constraint=1, &
      addunknowns=.true., u=up )

    print *, 'pp = ', pp
    print *, 'up = ', up

    write(100, '(i5,7es16.8)') step, tnp1, pp, up

    tn = tnp1

!   write VTK files

    if ( mod(step-1,10) == 0 ) then

      ipost = ipost + 1
      call create_vector ( problem, velocity, physq=1)
      call extract_physvector ( mesh, problem, sol, velocity)
      write(filename,'(a,i4.4,a)') 'velocity', ipost, '.vtk'
      call write_vector_vtk ( mesh, problem, filename=filename, &
        dataname='velocity', vector=velocity )

      call delete ( velocity )

    end if

  end do integration

  close(unit=100)


! delete all data including all allocated memory

  call delete ( problem )
  call delete ( input_probdef )
  call delete ( mesh )
  call delete ( sol, sol_iter, soln )
  call delete ( solnm1, sol_hat)
  call delete ( rhsd, rhsd_stored )
  call delete ( coefficients )
  call delete ( oldvectors, oldvectors_iter, oldvectors_hat )
  call delete ( vel, pres )
  call delete ( problem_pois )
  call delete ( meshvel )

  deallocate ( meshcoor_n, meshcoor_nm1 )

end program ale3
