! Viscoelastic problem (Oldroyd-B):
! Couette flow with a freely floating solid particle
! Neutrally buoyant particle ( density of particle = density of fluid )
! Second-order Gear with velocity prediction for inertia terms.
! DEVSS-G/SUPG
! Implicit bilinear terms of CE in momentum balance (stress implicit).
! L2-projection of c=exp(s) on the finite element approximation space in the
! momentum balance.
! Semi-implicit Gear with velocity prediction for the CE.
! Second-order time integration
! ALE body-fitting mesh scheme
! Particle updater uses a second-order AB2 scheme
! Mesh generated by Gmsh using triangles.
! This problem studies particle migration in a Couette flow.
! See Huang et al., J. Fluid Mech. (1997), vol. 343, pp. 73–94.
! NOTE: this problem is similar to ale7, but now using the L2-projection of
!       c=exp(s).


program ale8

  use tfem_m
  use math_defs_m
  use hsl_ma41_m
  use hsl_ma57_m
  use stokes_elements_m
  use inertia_elements_m
  use viscoelastic_elements_m
  use io_utils_m
  use figplot_m
  use subs1_m
  use update_mesh_nodes3_m

  implicit none

! constants

  integer, parameter :: &
    uintpl = 6,             & ! P2 velocities
    pintpl = 2,             & ! P1 pressures
    gintpl = 2,             & ! P1 gradients
    cintpl = 2,             & ! P1 conformation
    physqvel = 1,           & ! physical quantity nr of the velocities
    physqpress = 2,         & ! physical quantity nr of the pressures
    physqgrad = 3,          & ! physical quantity nr of the gradients
    gauss = 6,              & ! 6-point Gauss integration of triangles
    gaussb = 3,             & ! 3-point integration of boundary elements
    ncompc = 3,             & ! number of conformation tensor components
    nmodes = 1,             & ! number of modes
    startm = 501,           & ! start of material model data
    model = 2,              & ! 2 = Oldroyd-B
    numtimesteps = 15000,   & ! number time steps
    timeint1 = 1,           & ! first-order implicit Euler time integration,
                              ! first time step
    timeint2 = 7,           & ! second-order implicit Gear time integration
                              ! after first time step
    logc = 1,               & ! standard scheme or log transformation
    numeulertimesteps = 1     ! number Euler time steps (at least one!)

  real(dp), parameter :: &
    eta_s = 0.125_dp,       & ! viscosity
    eta_p = 0.875_dp,       & ! polymer viscosity
    lambda = 0.625_dp,      & ! relaxation time
    beta = 1.0_dp,          & ! upwinding parameter in the SUPG method
    rho = 40.0_dp,          & ! fluid density
    rho_p = 40.0_dp,        & ! particle density
    U_plate = 0.1_dp,       & ! velocity of the upper/lower plate is +/-U_plate
    deltat = 1.e-1_dp         ! time step

! definitions

  type(mesh_t) :: mesh, mesh1
  type(input_probdef_t) :: input_probdef, input_probdefc, input_probdefc_proj
  type(problem_t), target :: problem, problemc, problemc_proj
  type(sysmatrix_t) :: sysmatrix, sysmatrixc, sysmatrixc_proj
  type(sysvector_t), target :: sol, soln, sol_hat, solnm1
  type(sysvector_t) :: rhsd
  type(sysvector_t), dimension(ncompc,nmodes), target :: solcn, solcnm1, solc_proj
  type(sysvector_t), dimension(ncompc,nmodes) :: rhsc, rhsc_proj
  type(vector_t) :: velocity, pressure
  type(oldvectors_t) :: oldvectors, oldvectors_hat
  type(coefficients_t) :: coefficients
  type(subscript_t) :: vel, pres
  type(vector_t), target :: meshvel, meshvelm1
  type(subscriptvec_t) :: meshvelx, meshvely
  type(lu_ma41_t) :: luc
  type(lu_ma57_t) :: lu_exps_proj
  type(solver_options_ma41_t) :: solver_options

  type(problem_t) :: problem_pois

  integer :: i, m, icomp, step, ipost=0
  real(dp) :: H, mass, moment, up_hat(3)
  real(dp) :: mfac, tn, tnp1
  real(dp) :: gamma0=1.5_dp, alpha0=2._dp, alpha1=-0.5_dp
  real(dp) :: alpha, G
  real(dp) :: U_c, R, eta, Y_0, yp

! particle velocities
  real(dp) :: up(3), un(3), unm1(3)
! particle position with respect to the INITIAL frame
  real(dp) :: pp(3), ppn(3), ppnm1(3)

  real(dp) :: matdiag(3), vec(3)

  real(dp), allocatable, dimension(:,:) :: meshcoor_n, meshcoor_nm1


  character(len=30) :: filename

  open ( unit=10, file='out8.out' )

  solver_options%real_storage=1.5
  solver_options%integer_storage=2.0

  H = 1._dp                ! mesh height

! set some parameters

  alpha = eta_p  ! DEVSS parameter
  G = eta_p / lambda  ! modulus


! fill coefficients
  call create_coefficients ( coefficients, ncoefi=250, ncoefr=502 )

  coefficients%i = &
    [ uintpl,   pintpl,     0,     0,         gintpl, &
      physqvel, physqpress, 0,     physqgrad, gauss,  &
      gaussb,   cintpl,     0,     0,         0,      &
      0,        0,          model, nmodes,    startm, &
      logc,     timeint1,    ( 0, i = 23, 250 )  &
    ]

  coefficients%i(48) = 1 ! use mesh velocity for ALE formulation
  coefficients%i(49) = 1  ! exp(s) projection =.true. for logc=1

  coefficients%r = 0
  coefficients%r(1:10) = &
    [ eta_s, 0._dp,   0._dp,   alpha, 0._dp, &
      0._dp, 0._dp,  deltat,   beta,  0._dp  &
    ]
  coefficients%r(501:502) = [ G, lambda ]
  coefficients%r(151) = rho

! one particle
  rp = 0.125_dp       ! radius of particle
  yp = -0.125_dp      ! initial y-position of the particle
  xp = [0.0_dp, yp] ! initial position of the center of the particle
  pp = [ (xp(i),i=1,2), 0._dp ]   ! initial position and rotation

! read P2 and P1 gmsh mesh
  call read_mesh_gmsh ( mesh, filename='4x1_yp-0.125_M1_P2.msh', ndim=2, physgeom=.true. )
  call read_mesh_gmsh ( mesh1, filename='4x1_yp-0.125_M1_P1.msh', ndim=2, physgeom=.true. )

! add objectcurve = 2
  call add_to_mesh ( mesh, object='curve', objectcurve=2, excludepoints=[2,3] )
  call add_to_mesh ( mesh, object='curve', objectcurve=2, excludepoints=[2,3] )
  mesh%objects(2)%coor(:,1) = mesh%objects(2)%coor(:,1) - 4.0_dp*H

  call add_to_mesh ( mesh, object='curve', objectcurve=2, objectmesh=mesh1 )
  call add_to_mesh ( mesh, object='curve', objectcurve=2, objectmesh=mesh1 )
  mesh%objects(4)%coor(:,1) = mesh%objects(4)%coor(:,1) - 4.0_dp*H

  call delete (mesh1)
  call fill_mesh_parts ( mesh )

! problem definition of gradient/velocity/pressure
  call create_input_probdef ( mesh, input_probdef, nvec=5, nphysq=3 )

  input_probdef%vec_elementdof(1)%a =   &
      reshape ( [ 2,2,2,2,2,2,    &  ! velocity
                  1,0,1,0,1,0,    &  ! pressure
                  4,0,4,0,4,0,    &  ! G
                  1,1,1,1,1,1,    &  ! scalar, such as vorticity
                  3,3,3,3,3,3 ], &  ! tensor
                  [6,5] )
  input_probdef%physq = [1,2,3]
  input_probdef%probnr = 1

! cell boundaries
  call define_essential ( mesh, input_probdef, curve1=1, physq=physqvel )
  call define_essential ( mesh, input_probdef, curve1=3, physq=physqvel )

  call define_essential ( mesh, input_probdef, point=1, physq=physqpress )

! constraint on particle boundary (freely floating)
  call define_constraint ( mesh, input_probdef, curve1=5, physq=physqvel, &
    discretization='collocation', nodedof=2, naddunknowns=3 )

! periodic velocities
  call define_constraint ( mesh, input_probdef, &
    physq=physqvel, object=1, object2=2, discretization='collocation', &
    nodedof=2 )

  call problem_definition ( input_probdef, mesh, problem )

! problem definition conformation tensor
  call create_input_probdef ( mesh, input_probdefc, nvec=3, nphysq=1 )

  input_probdefc%vec_elementdof(1)%a =   &
      reshape ( [ 1,0,1,0,1,0,    &  ! c
                  1,1,1,1,1,1,    &  ! scalar for plotting
                  3,3,3,3,3,3 ], &  ! tensor
                  [6,3] )

  input_probdefc%physq = [1]
  input_probdefc%probnr = 2

! conformation
  call define_constraint ( mesh, input_probdefc, &
    object=3, object2=4, discretization='collocation', nodedof=1 )

  call problem_definition ( input_probdefc, mesh, problemc )

! create system vectors (solution and right-hand side)

  call create_sysvector ( problem, sol, soln )
  call create_sysvector ( problem, solnm1, sol_hat )
  call create_sysvector ( problem, rhsd )

! define some arrays the ALE mesh position at old times

  allocate ( meshcoor_n(mesh%nnodes,2), meshcoor_nm1(mesh%nnodes,2) )
  meshcoor_n = mesh%coor
  meshcoor_nm1 = mesh%coor


  call create ( problemc, solcn, solcnm1, rhsc )

! set initial value of solution to zero

  soln%u = 0
  up = 0._dp

  do m = 1, nmodes
    if ( logc == 0 ) then ! standard
      solcn(1,m)%u = 1   ! initial cxx
      solcn(2,m)%u = 0   ! initial cxy
      solcn(3,m)%u = 1   ! initial cyy
    else if ( logc == 1 ) then ! log scheme
      solcn(1,m)%u = 0   ! initial sxx
      solcn(2,m)%u = 0   ! initial sxy
      solcn(3,m)%u = 0   ! initial syy
    end if
  end do

! problem definition for projected "c=exp(s)" of the log conformation s

  call create_input_probdef ( mesh, input_probdefc_proj, nvec=1, nphysq=1 )

  input_probdefc_proj%vec_elementdof(1)%a = &
      reshape ( [ 1,0,1,0,1,0 ], &
                   [6,1] )

  input_probdefc_proj%physq = [1]
  input_probdefc_proj%probnr = 3

  call problem_definition ( input_probdefc_proj, mesh, problemc_proj )

  call create ( problemc_proj, solc_proj, rhsc_proj )

  solc_proj(1,1)%u = 1   ! initial cxx
  solc_proj(2,1)%u = 0   ! initial cxy
  solc_proj(3,1)%u = 1   ! initial cyy

! create system matrix for projection problem

  call create_sysmatrix_structure ( sysmatrixc_proj, mesh, problemc_proj, &
    symmetric=.true. )
  call create_sysmatrix_data ( sysmatrixc_proj )


! create system matrix for conformation problem
  call create_sysmatrix_structure_base ( sysmatrixc, mesh, problemc )
  call create_sysmatrix_structure_constraint ( sysmatrixc, mesh, problemc )
  call finalize_sysmatrix_structure ( sysmatrixc )

  call create_sysmatrix_data ( sysmatrixc )

! create mesh velocity vectors
  call create ( problem, meshvel, vec=physqvel )
  call create ( problem, meshvelm1, vec=physqvel )
  meshvel%u = 0 ! set mesh velocity to zero for first time step

! define vector subscripts for direct manipulation of sysvector data

! velocities
  call create_subscript ( mesh, problem, vel, physqarr=[physqvel] )
! pressures
  call create_subscript ( mesh, problem, pres, physqarr=[physqpress] )

! create subscript for the mesh velocity vector

  call create_subscript_vector ( mesh, problem, meshvelx, vec=physqvel, &
    degfd=1 )
  call create_subscript_vector ( mesh, problem, meshvely, vec=physqvel, &
    degfd=2 )

! create the structure oldvectors

  call create_oldvectors ( oldvectors, nsysvec=2, nsysvec2=3, nprob=3, nvec=2 )
  call create_oldvectors ( oldvectors_hat, nsysvec=1 )

! fill oldvectors

  oldvectors%s(1)%p => soln
  oldvectors%s(2)%p => solnm1
  oldvectors%s2(1)%p => solcn
  oldvectors%s2(2)%p => solcnm1
  oldvectors%s2(3)%p => solc_proj
  oldvectors%p(1)%p => problem
  oldvectors%p(2)%p => problemc
  oldvectors%p(3)%p => problemc_proj
  oldvectors%v(1)%p => meshvel
  oldvectors%v(2)%p => meshvelm1

  oldvectors_hat%s(1)%p => sol_hat


! fill solution vector with essential boundary conditions

  call fill_sysvector ( mesh, problem, sol, curve1=1, physq=physqvel, &
    degfd=1, value=-U_plate )
  call fill_sysvector ( mesh, problem, sol, curve1=1, physq=physqvel, &
    degfd=2, value=0.0_dp )
  call fill_sysvector ( mesh, problem, sol, curve1=3, physq=physqvel, &
    degfd=1, value=U_plate )
  call fill_sysvector ( mesh, problem, sol, curve1=3, physq=physqvel, &
    degfd=2, value=0.0_dp )
  call fill_sysvector ( mesh, problem, sol, point=1, physq=physqpress, &
    value=0._dp )

! print dimensionless numbers of Huang et al.

  U_c = U_plate * 2
  R = H / 2
  eta = eta_s+eta_p
  Y_0 = R + yp

  write(*,'(/4(a,es12.4/))') 'Re = ', rho_p*U_c*rp/eta, &
                            'De = ', lambda*U_c/rp, &
                            'blockage ratio beta = ', rp/R, &
                            'Y_0/W = ', Y_0/H

! start time integration

  tn = 0

  integration: do step = 1, numtimesteps

    tnp1 = tn + deltat

    write(*,'(/a,i0,a,es12.4,a/)') ' ** time step = ', step, &
                                   ' time = ', tnp1, ' ** '

!   change time integration scheme at the second time step
    if ( step == 2 ) then
      coefficients%i(22) = timeint2
    end if

    meshcoor_nm1 = meshcoor_n
    meshcoor_n = mesh%coor

!   Advance particle position in vertical direction only for ALE.

    if ( step == 1 ) then

      un = up  ! In the current problem up=0 at t=0

      ppn = pp
      pp = pp + deltat * up  ! In the current problem up=0 at t=0

    else if ( step >= 2 ) then

!     advance particle position with 2nd order Adams-Bashforth

      unm1 = un
      un = up
      ppnm1 = ppn
      ppn = pp

      pp = pp + deltat*(3*un/2 - unm1/2)

!     update mesh nodes: solve a Laplace's equation (vertically only)

      call update_mesh_nodes ( mesh, problem_pois, [ 0._dp, pp(2)-ppn(2) ] )

    end if

    xp(2) = pp(2)

!   compute mesh velocity for tn+1 (Gear)
!   NOTE: meshvel and meshvelm1 will be used in the element routines to take
!   into account the mesh velocity.

    if ( step == 1 ) then

!     step=1, particle velocity = 0 and mesh velocity=0

      meshvel%u = 0

    else if ( step >= 2 ) then

!     second-order accurate

      call copy ( meshvel, meshvelm1 )

!     mesh velocity in x-direction = particle velocity in x-direction, derived
!                                    using BDF2 of particle position
      meshvel%u(meshvelx%s) = ( 1.5_dp*pp(1) - 2*ppn(1) + &
                                0.5_dp*ppnm1(1) ) / deltat

!     mesh velocity in y-direction from BDF2 of mesh coordinates in y-direction
      meshvel%u(meshvely%s) = ( 1.5_dp*mesh%coor(:,2) - 2*meshcoor_n(:,2) + &
                                0.5_dp*meshcoor_nm1(:,2) ) / deltat

    end if

!   create system matrix

    call create_sysmatrix_structure_base ( sysmatrix, mesh, problem )
    call create_sysmatrix_structure_constraint ( sysmatrix, mesh, problem, &
      diagonal_addunknowns=.true. )
    call finalize_sysmatrix_structure ( sysmatrix )
    call create_sysmatrix_data ( sysmatrix )

!   build (assemble) matrix and vector from elements

!   Stokes flow : velocity / pressure
    call build_system ( mesh, problem, sysmatrix, rhsd, elemsub=stokes_elem, &
      physqrow=[physqvel,physqpress], physqcol=[physqvel,physqpress], &
      coefficients=coefficients )

!   DEVSS-G
    call build_system ( mesh, problem, sysmatrix, rhsd, elemsub=devssg_elem, &
      physqrow=[physqgrad,physqvel], physqcol=[physqgrad,physqvel], &
      addmatvec=.true., coefficients=coefficients )

!   set to zero off-diagonal blocks gradient-pressure
    call build_system ( mesh, problem, sysmatrix, rhsd, addmatvec=.true., &
      buildvector=.false., physqrow=[physqgrad], physqcol=[physqpress], &
      zeromatvec=.true. )
    call build_system ( mesh, problem, sysmatrix, rhsd, addmatvec=.true., &
      buildvector=.false., physqrow=[physqpress], physqcol=[physqgrad], &
      zeromatvec=.true. )


!   exps projection (for log conformation)

    if ( logc == 1 ) then

      call solve_exps_projection

    end if


!   build implicit terms of CE with rhs in momentum balance
    call build_system ( mesh, problem, sysmatrix, rhsd, &
      elemsub=divtau_implicit_ce_elem_c, &
      oldvectors=oldvectors, physqrow=[physqvel], physqcol=[physqvel], &
      addmatvec=.true., coefficients=coefficients )

!   weak constraints on particle domain
    call build_system_constraint ( mesh, problem, sysmatrix, rhsd, &
      constraint1=1, elemsub=elementc, addmatvec=.true., &
      coefficients=coefficients )

!   periodical condition on velocities
    call build_system_constraint ( mesh, problem, sysmatrix, rhsd, &
      constraint1=2, elemsub=constraints_object_conn_P2, addmatvec=.true., &
      coefficients=coefficients )

    if ( step <= numeulertimesteps ) then

!     u^n*grad u^n+1
      call build_system ( mesh, problem, sysmatrix, rhsd, &
        elemsub=inertia_elem_conv_picard, coefficients=coefficients, &
        oldvectors=oldvectors, physqcol=[physqvel], &
        physqrow=[physqvel], addmatvec=.true., buildvector=.false. )

    else

!     (2*u^n - u^n-1)*grad u^n+1 (second-order prediction)
      call build_system ( mesh, problem, sysmatrix, rhsd, &
        elemsub=inertia_elem_conv_pred_2nd_order, coefficients=coefficients, &
        oldvectors=oldvectors, physqcol=[physqvel], &
        physqrow=[physqvel], addmatvec=.true., buildvector=.false. )

    end if

!   build instability term ( rho du/dt )
    if ( step <= numeulertimesteps ) then
!     implicit Euler
      sol_hat%u(vel%s) = soln%u(vel%s)
      mfac = 1._dp
    else
!     second-order implicit Gear after Euler time steps
      sol_hat%u(vel%s) = alpha0*soln%u(vel%s) + alpha1*solnm1%u(vel%s)
      mfac = gamma0
    end if

    call build_system ( mesh, problem, sysmatrix, rhsd, &
      elemsub=inertia_elem_dudt, &
      coefficients=coefficients, oldvectors=oldvectors_hat, &
      physqcol=[physqvel], physqrow=[physqvel], &
      factormat=mfac, addmatvec=.true. )


!   build particle instationary terms
    mass = rho_p * pi * rp**2
    moment = 0.5 * mass * rp**2

    if ( step <= numeulertimesteps ) then
      ! first order Euler
      up_hat = un
      mfac = 1._dp
    else
      ! second-order BDF2 after Euler time steps
      up_hat = alpha0*un + alpha1*unm1
      mfac = gamma0
    end if

    matdiag(1) = mass * mfac / deltat
    matdiag(2) = mass * mfac / deltat
    matdiag(3) = moment * mfac / deltat

    vec(1) = mass * up_hat(1) / deltat
    vec(2) = mass * up_hat(2) / deltat
    vec(3) = moment * up_hat(3) / deltat

    call build_system_constraint_addunknowns ( mesh, problem, &
      sysmatrix=sysmatrix, sysvector=rhsd, constraint=1, &
      addmatvec=.true., matdiag=matdiag, rhs=vec )

    call add_effect_of_essential_to_rhs ( problem, sysmatrix, sol, rhsd )

    call solve_system_ma41 ( sysmatrix, rhsd, sol, &
      solver_options=solver_options )

    call delete ( sysmatrix )

!   copy the solution to the old step
    call copy ( soln, solnm1 )
    call copy ( sol, soln )

!   build (assemble) matrix and vector for conformation problem
    if ( coefficients%i(22) == timeint1 ) then
      call build_system ( mesh, problemc, sysmatrixc, m2sysvector=rhsc, &
        elemsub=ce_supg_elem, oldvectors=oldvectors, &
        coefficients=coefficients )
    else
      call build_system ( mesh, problemc, sysmatrixc, m2sysvector=rhsc, &
        elemsub=ce_supg_elem_implicit_2nd_order, oldvectors=oldvectors, &
        coefficients=coefficients )
    end if

!   periodical condition on conformation tensor
    call build_system_constraint ( mesh, problemc, sysmatrixc, &
      m2sysvector=rhsc, elemsub=constraints_object_conn_P1, addmatvec=.true. )

    call copy ( solcn, solcnm1 )

    call check ( sysmatrixc )

    do icomp = 1, ncompc
      call solve_system_ma41 ( sysmatrixc, rhsc(icomp,1), solcn(icomp,1), &
        luc, solver_options=solver_options )
    end do

    call delete ( luc )  ! remove LU decomposition and rebuild next time step

!   extract info on particle
    call get_sysvector_constraint ( mesh, problem, soln, constraint=1, &
      addunknowns=.true., u=up )

    print *, 'pp = ', pp
    print *, 'up = ', up

!   write data to file (inclunding dimensionless time and position)

    write(10, '(i5,9es16.8)') step, tnp1, pp, up, tnp1*U_c/H, (R+pp(2))/H

    tn = tnp1

!   write VTK files

    if ( mod(step,1000) == 0 ) then

      ipost = ipost + 1
      call create_vector ( problem, velocity, physq=physqvel)
      call extract_physvector ( mesh, problem, sol, velocity)
      write(filename,'(a,i4.4,a)') 'velocity', ipost, '.vtk'
      call write_vector_vtk ( mesh, problem, filename=filename, &
        dataname='velocity', vector=velocity)

      call delete ( velocity )

    end if

  end do integration

  close(unit=10)

! delete all data including all allocated memory

  call delete ( problem )
  call delete ( input_probdef )
  call delete ( mesh )
  call delete ( sol, soln )
  call delete ( solnm1, sol_hat)
  call delete ( rhsd )
  call delete ( problemc )
  call delete ( input_probdefc )
  call delete ( sysmatrixc )
  call delete ( solcn, solcnm1, rhsc )
  call delete ( velocity, pressure )
  call delete ( coefficients )
  call delete ( oldvectors, oldvectors_hat )
  call delete ( vel, pres )
  call delete ( meshvel, meshvelm1 )
  call delete ( meshvelx, meshvely )
  call delete ( sysmatrixc_proj )
  call delete ( problemc_proj )
  call delete ( input_probdefc_proj )
  call delete ( solc_proj, rhsc_proj )

  deallocate ( meshcoor_n, meshcoor_nm1 )


contains


! project c=exp(s) on discrete fem space

  subroutine solve_exps_projection

    type(solver_options_ma57_t) :: solver_options_ma57

    integer :: i, m

!   build system matrix and vector for projection problem

    call build_system ( mesh, problemc_proj, sysmatrixc_proj, &
      m2sysvector=rhsc_proj, elemsub=exps_projection_elem, &
      oldvectors=oldvectors, coefficients=coefficients )

    call check ( sysmatrixc_proj )

!   MA57 solver storage
    solver_options_ma57%integer_storage = 1.3
    solver_options_ma57%real_storage    = 1.3

!   LU decomposition is done in the first loop traversing

    do m = 1, nmodes
      do i = 1, ncompc

        call add_effect_of_essential_to_rhs ( problemc_proj, sysmatrixc_proj, &
           solc_proj(i,m), rhsc_proj(i,m) )

        call solve_system_ma57 ( sysmatrixc_proj, rhsc_proj(i,m), &
           solc_proj(i,m), lu_exps_proj, solver_options=solver_options_ma57 )

      end do
    end do

    call delete ( lu_exps_proj )

  end subroutine solve_exps_projection

end program ale8
