! Stokes problem:
! Oscillating Couette flow with a freely floating solid particle.
! ALE body-fitting mesh scheme.
! Particle updater uses a second-order AB2 scheme.
! Mesh generated by Gmsh using triangles.
! A remeshing is performed every a fixed number of steps.

program ale9

  use tfem_m
  use math_defs_m
  use hsl_ma41_m
  use stokes_elements_m
  use io_utils_m
  use figplot_m
  use subs9_m
  use update_mesh_nodes9_m

  implicit none

! constants

  integer, parameter :: &
    uintpl = 6,             & ! P2 velocities
    pintpl = 2,             & ! P1 pressures
    physqvel = 1,           & ! physical quantity nr of the velocities
    physqpress = 2,         & ! physical quantity nr of the pressures
    gauss = 6,              & ! 6-point Gauss integration of triangles
    gaussb = 3,             & ! 3 point integration of boundary elements
    numtimesteps = 500,     & ! number time steps
    vtkevery = 1,           & ! vtk file every vtkevery steps. -1: means none
    step_remeshing = 10       ! step interval for remeshing

  real(dp), parameter :: &
    eta = 1.0_dp,           & ! viscosity
    amp = 1.0_dp,           & ! amplitude of the imposed sinusoidal shear rate
    freq = 1.0_dp,          & ! frequency of the imposed sinusoidal shear rate
    deltat = 0.02_dp          ! time step

! definitions

  type(mesh_t) :: mesh
  type(input_probdef_t) :: input_probdef
  type(problem_t) :: problem
  type(sysmatrix_t) :: sysmatrix
  type(sysvector_t), target :: sol
  type(sysvector_t) :: rhsd
  type(vector_t) :: velocity
  type(plot_options_t) :: plot_options
  type(oldvectors_t) :: oldvectors
  type(coefficients_t) :: coefficients

  type(problem_t) :: problem_pois

  integer :: i, step, ipost=0
  real(dp) :: time=0.0_dp
  real(dp) :: dx_box, dx_part

  real(dp) :: ox, oy, lx, ly, vel_lower_wall, vel_upper_wall
  real(dp) :: up(3), unm1(3), un(3), pp(3), ppn(3)

  character(len=30) :: filename
  logical :: remeshing=.false.

  open (unit = 100, file='output.out')

! fill coefficients
  call create_coefficients ( coefficients, ncoefi=250, ncoefr=200 )

  coefficients%i = 0
  coefficients%i(1:11) = &
    [ uintpl,   pintpl,     0,     0,         0,  &
      physqvel, physqpress, 0,     0,     gauss,  &
      gaussb ]

  coefficients%r = 0
  coefficients%r(1) = eta

  call write_coefficients ( coefficients, filename='coefficients.out' )

! mesh parameters
  ox = -1.0_dp
  oy = -0.5_dp
  lx =  2.0_dp
  ly =  1.0_dp

! one particle
  rp(1) = 0.1_dp         ! particle radius
  xp(1,1) = 0.0_dp       ! x-position of the particle
  xp(1,2) = 0.1_dp       ! y-position of the particle

  pp = [ (xp(1,i),i=1,2), 0._dp ]

  dx_box = 0.1_dp       ! element spacing on the external boundaries
  dx_part = 0.02_dp     ! element spacing on the particle boundary

  call generate_read_mesh

! plot mesh
  plot_options%fontsize = 6
  call plot_points_curves ( plot_options, mesh, 'curves.fig' )
  plot_options%fontsize = 10
  call plot_mesh ( plot_options, mesh, 'mesh.fig' )

! define problem, essential conditions and constraints
  call initialize_problem

! create system matrix
  call create_system_matrix

! start time integration
  time = 0

  do step = 1, numtimesteps

    if ( step >= 2 ) then

      time = time + deltat

      if ( step == 2 ) then

!       advance with forward Euler
        un = up
        ppn = pp
        pp = pp + deltat * un

      else

!       advance particle position with 2nd order Adams-Bashforth
        unm1 = un
        un = up
        ppn = pp
        pp = pp + deltat*(3*un/2 - unm1/2)

      end if

      xp(1,1:2) = pp(1:2)

!     update mesh nodes: solve a Laplace's equation
      call update_mesh_nodes ( mesh, problem_pois, pp(1:2)-ppn(1:2) )

    end if

    if ( mod( step, step_remeshing ) == 0 .AND. step /= numtimesteps ) then
      remeshing = .true.
      print *,'Doing remeshing...'
    end if

    if ( remeshing ) then

      call delete_old_problem     ! delete old mesh, problem, ...

      call generate_read_mesh     ! generate and read mesh

      call initialize_problem     ! define new problem

      call create_system_matrix   ! create new system matrix

      remeshing = .false.

    end if

    call build_solve_system       ! build and solve the system

!   Post-processing

!   extract info on particle

    call get_sysvector_constraint ( mesh, problem, sol, constraint=1, &
      addunknowns=.true., u=up )

    print *, 'pp = ', pp
    print *, 'up = ', up

    write(100, '(i5,7es16.8)') step, time, pp, up

!   write VTK files

    if ( vtkevery > 0 ) then
      if ( mod(step,vtkevery) == 0 ) then
!
        ipost = ipost + 1
        call create_vector ( problem, velocity, physq=1)
        call extract_physvector ( mesh, problem, sol, velocity)
        write(filename,'(a,i4.4,a)') 'velocity', ipost, '.vtk'
        call write_vector_vtk ( mesh, problem, filename=filename, &
          dataname='velocity', vector=velocity )

        call delete ( velocity )

      end if
    end if

  end do

  close(unit=100)

! delete all data including all allocated memory

  call delete ( problem )
  call delete ( input_probdef )
  call delete ( mesh )
  call delete ( sol )
  call delete ( rhsd )
  call delete ( coefficients )
  call delete ( oldvectors )
  call delete ( problem_pois )

contains

! generate and read mesh

  subroutine generate_read_mesh

    call write_gmsh_parameters ( ox, oy, lx, ly, xp, rp, dx_box, dx_part )

    call execute_command_line ( 'gmsh -2 -order 2 -algo front2d -o mesh.msh &
                   &mesh.geo > outputmesh.out' )

!   read mesh generated by gmsh
    call read_mesh_gmsh ( mesh, filename='mesh.msh', ndim=2, physgeom=.true. )

!   add objectcurve = 2
    call add_to_mesh ( mesh, object='curve', objectcurve=2, &
      excludepoints=[2,3] )
    call add_to_mesh ( mesh, object='curve', objectcurve=2, &
      excludepoints=[2,3] )
    mesh%objects(2)%coor(:,1) = mesh%objects(2)%coor(:,1) - lx

    call fill_mesh_parts ( mesh )

    !call write_mesh_vtk ( mesh, filename='mesh.vtk' )

  end subroutine generate_read_mesh


  subroutine write_gmsh_parameters ( ox, oy, lx, ly, xp, rp, dx_box, dx_part )

    real(dp), intent(in) :: ox, oy, lx, ly, xp(:,:), rp(:), dx_box, dx_part

    integer :: i, nobj

    nobj = size(rp)

    open ( unit=25, file='mesh.geo' )

    write ( 25, '(1X,A,F18.14,A)' ) 'ox = ', ox, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'oy = ', oy, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'lx = ', lx, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'ly = ', ly, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'dx_box = ', dx_box, ';'
    write ( 25, '(1X,A,I0,A)' ) 'nobj = ', nobj, ';'

    do i = 1, nobj
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'xp[', i, '] = ', xp(i,1), ';'
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'yp[', i, '] = ', xp(i,2), ';'
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'rp[', i, '] = ', rp(i), ';'
    end do

    write ( 25, '(1X,A,F18.14,A)' ) 'dx_part = ', dx_part, ';'

    write ( 25, '(/1x,a)' ) 'Include "particles_in_a_box_2D.igo";'

    close ( 25 )

  end subroutine write_gmsh_parameters


! define problem, bcs, constraints

  subroutine initialize_problem

!   problem definition
    call create_input_probdef ( mesh, input_probdef, nvec=3, nphysq=2 )

    input_probdef%vec_elementdof(1)%a =   &
        reshape ( [2,2,2,2,2,2,    &  ! velocity
                   1,0,1,0,1,0,    &  ! pressure
                   1,1,1,1,1,1 ], &  ! scalar, such as vorticity
                    [6,3] )

    input_probdef%physq = [1,2]

!   cell boundaries
    call define_essential ( mesh, input_probdef, curve1=1, physq=1 )
    call define_essential ( mesh, input_probdef, curve1=3, physq=1 )

    call define_essential ( mesh, input_probdef, point=1, physq=2 )

!   constraint on particle boundary (freely floating)
     call define_constraint ( mesh, input_probdef, curve1=5, physq=1, &
       discretization='collocation', nodedof=2, naddunknowns=3 )

!   periodic velocities
    call define_constraint ( mesh, input_probdef, &
      physq=physqvel, object=1, object2=2, discretization='collocation', &
      nodedof=2 )

    call problem_definition ( input_probdef, mesh, problem )

!   create system vectors (solution and right-hand side)
    call create_sysvector ( problem, sol, rhsd )

!   create oldvectors
    call create_oldvectors ( oldvectors, nsysvec=1 )
    oldvectors%s(1)%p => sol

  end subroutine initialize_problem


! create system matrix

  subroutine create_system_matrix

    call create_sysmatrix_structure_base ( sysmatrix, mesh, problem, &
      symmetric=.true. )
    call create_sysmatrix_structure_constraint ( sysmatrix, mesh, problem )
    call finalize_sysmatrix_structure ( sysmatrix )

    call create_sysmatrix_data ( sysmatrix )

  end subroutine create_system_matrix


! build (assemble) matrix and vector from elements and solve

  subroutine build_solve_system

!   Stokes flow : velocity / pressure
    call build_system ( mesh, problem, sysmatrix, rhsd, elemsub=stokes_elem, &
      coefficients=coefficients )

!   constraint on particle boundary
    call build_system_constraint ( mesh, problem, sysmatrix, rhsd, &
      constraint1=1, elemsub=elementc, addmatvec=.true., &
      coefficients=coefficients )

!   periodical condition on velocities
    call build_system_constraint ( mesh, problem, sysmatrix, rhsd, &
      constraint1=2, elemsub=constraints_object_conn_P2, addmatvec=.true., &
      coefficients=coefficients )

!   boundary conditions
    vel_upper_wall = (oy + ly) * amp * cos( freq * time )
    vel_lower_wall = oy * amp * cos( freq * time )

    call fill_sysvector ( mesh, problem, sol, curve1=1, physq=1, degfd=1, &
      value=vel_lower_wall )
    call fill_sysvector ( mesh, problem, sol, curve1=1, physq=1, degfd=2, &
      value=0.0_dp )
    call fill_sysvector ( mesh, problem, sol, curve1=3, physq=1, degfd=1, &
      value=vel_upper_wall )
    call fill_sysvector ( mesh, problem, sol, curve1=3, physq=1, degfd=2, &
      value=0.0_dp )
    call fill_sysvector ( mesh, problem, sol, point=1, physq=2, value=0._dp )

    call check ( sysmatrix )

    call add_effect_of_essential_to_rhs ( problem, sysmatrix, sol, rhsd )

!   solve system
    call solve_system_ma57 ( sysmatrix, rhsd, sol )

  end subroutine build_solve_system


! delete old problem

  subroutine delete_old_problem

    call delete ( problem )
    call delete ( problem_pois )
    call delete ( sysmatrix )
    call delete ( input_probdef )
    call delete ( mesh )
    call delete ( sol )
    call delete ( rhsd )
    call delete ( oldvectors )

  end subroutine delete_old_problem

end program ale9
