
! Copyright (C) 2007-2022 Martien A. Hulsen
! Permission to copy or distribute this software or documentation
! in hard copy or soft copy granted only by written license
! obtained from Martien A. Hulsen.
! All rights reserved. No part of this publication may be reproduced,
! stored in a retrieval system ( e.g., in memory, disk, or core)
! or be transmitted by any means, electronic, mechanical, photocopy,
! recording, or otherwise, without written permission from the
! publisher.

! Defines routines for reading a mesh from the universal file format as
! produced by NX-Ideas (part of the Unigraphics (UGS) CAD/CAE/CAM package).

! The following element types can be imported:
!   3-node triangles
!   6-node triangles
!   4-node quadrilaterals
!   8-node quadrilaterals
!   4-node tetrahedrons
!   10-node tetrahedrons
!   8-node bricks
!   20-node bricks
!
! NOTICE:
!
! 1. Basically, all the meshes generated using ideas are three dimensional,
! i.e. mesh%ndim=3. So, if one wants to create a 2D mesh from a ideas mesh
! of a planar shape, the mesh must be converted to a 2D mesh using
! the subroutine mesh_convert with the option, coordinates=(/1,2/).
!
! 2. Quadratic quadrilateral and brick elements generated by ideas are
! of serendipity type. To convert the serendipity-type elements to
! Lagrange-type elements, one should use the subroutine mesh_convert
! with the option, lagrange='all'.
!
! 3. Mesh files imported from ideas do not contain points.
! If it is required to have points, for example to set the pressure in a single
! point, points can be added to the mesh using the subroutine add_to_mesh
! with the keyword point or points.

! TODO:
!   - multiple element shapes in one file

module ideas_utils_m

  use kind_defs_m
  use mesh_m
  use limits_m, only: MAXPOINTS, MAXCURVES, MAXOBJECTS, MAXSURFACES, &
                      MAXBLOCKS, MAXVOLUMES, MAXNODESETS, MAXELEMENTSETS

  implicit none


  integer :: unit_unv = 13 ! unit number for reading

! Parameters

  integer, parameter :: MAXCOLORS = 7

! interface to support older interfaces

  interface read_ideas_mesh
    module procedure read_mesh_ideas
  end interface read_ideas_mesh


contains


! read mesh from ideas unversal file

  subroutine read_mesh_ideas ( mesh, filename )

    type(mesh_t), intent(out) :: mesh

!   the filename for reading the mesh from

    character (len=*), intent(in) :: filename


!   boundary_t curves and surfaces

    type boun_info_t
      integer :: elem_unv ! element number in a unversal file
      integer :: face_unv ! face number in a unversal file
      integer :: elgrp    ! group number in a tfem mesh
      integer :: elem     ! element number in a group
      integer :: elnumnod ! number of nodes in the surface element
      integer :: elshape  ! shape number of the surface element
!     topology of boundary element
      integer, allocatable, dimension(:) :: topology
      character(len=13) :: elglobalshape
    end type boun_info_t

    type boundary_t
!     number of free edges or surfaces on a boundary
      integer :: nelem
      type(boun_info_t), allocatable, dimension(:) :: boun
    end type boundary_t

!   allocatable arrays

    real(dp), allocatable, dimension(:)    :: x, y, z

    integer, allocatable, dimension(:,:,:) :: faceadj, neladj

    integer, allocatable, dimension(:,:)   :: nelnod, nseq

!   curve/surface topology in a tfem mesh
!   curve_node_seq(i,face,elgrp)
!   surface_node_seq(i,face,elgrp)
!   i    : local node number of an element in tfem
!   face : face number defined in an ideas mesh

    integer, allocatable, dimension(:,:,:) :: curve_node_seq
    integer, allocatable, dimension(:,:,:) :: surface_node_seq

    integer, allocatable, dimension(:,:)   :: grp_elem

    integer, allocatable, dimension(:)     :: iseq, jseq, color, ne, boun_nodes

    type(boundary_t), allocatable, dimension(:) :: curves, surfaces

!   Color map:   Group number, Color

    integer, parameter :: &
       green   = 7!,  &   ! 1 --> Green    *** default color for a single group
!       blue    = 1,  &   ! 2 --> Blue
!       orange  = 10, &   ! 3 --> Orange
!       red     = 11, &   ! 4 --> Red
!       magenta = 12, &   ! 5 --> Magenta
!       pink    = 14, &   ! 6 --> Pink
!       cyan    = 4       ! 7 --> Cyan


!   local variables

    real(dp):: tvar, dummy

    integer :: istart, idaset, ios
    integer :: node, ic, ic_disp, icolor
    integer :: elem, ife, iphy, imat, inode
    integer :: i, j, iend, iload, iface, n

    integer :: elshape, numnod, nnodes, ncurves, nsurfaces
    integer :: elgrp, iptr, color_grp(2,MAXCOLORS)

    integer :: curve, surface, face, lnode, elem_unv

!   number element free edges (or faces) at each curve (or surface)

    integer, allocatable :: num_boun(:)

    character(len=256) :: load_set_name
    character(len=6  ) :: start_id


!   initialize num_boun

    allocate ( num_boun(max(MAXCURVES,MAXSURFACES)) )

    num_boun = 0

!   open file

    open ( unit=unit_unv, file=filename, form='formatted', iostat=ios, &
           status='old' )

    if ( ios /= 0 ) then
      write(*,'(/2a/)') 'Error in read_mesh_ideas: cannot open file: ', filename
      stop
    end if

!   read parameters; number of elements, nodes, and curves.

    nnodes = 0
    ncurves = 0
    nsurfaces = 0

    do

      read(unit_unv,'(i10)', iostat=ios) istart  ! dataset start id (    -1)
      if (ios /= 0) exit
      read(unit_unv,*) idaset                    ! dataset number

      if (idaset == 2411) then       ! node coordinates
        do
          read(unit_unv,'(4i10)') node, ic, ic_disp, icolor
          if (node == -1) exit
          read(unit_unv,*)
          nnodes = nnodes + 1
        end do
      else if (idaset == 2412) then  ! element connectivity
        do
          read(unit_unv,'(6i10)') elem, i, iphy, imat, icolor, inode
          if (elem == -1) exit
          if (elem == 1 ) ife = i

          iend = 1 + (inode-1)/8
          do i = 1, iend
            read(unit_unv,*)
          end do

          mesh%nelem = mesh%nelem + 1
        end do
      else if (idaset == 790) then   ! curves from load set data for BCs
        select case (ife)
          case (91,92,94,95)
            read(unit_unv,'(2i10)') i, iload        ! i : curve number
            if (i < 0) exit
            read(unit_unv,'(a)') load_set_name
            num_boun(i) = 0
            do
              read(unit_unv,'(4i10)') n, elem, iface, icolor
              if (n == -1) exit
              num_boun(i) = num_boun(i) + 1
              do j = 1, 5
                read(unit_unv,*)
              end do
            end do
            ncurves = ncurves + 1
          case (111,115,116,118)
            read(unit_unv,'(2i10)') i, iload        ! i : surface number
            if (i < 0) exit
            read(unit_unv,'(20a2)') load_set_name
            num_boun(i) = 0
            do
              read(unit_unv,'(4i10)') n, elem, iface, icolor
              if (n  == -1) exit
              read(unit_unv,*) tvar
              read(unit_unv,*) dummy
              num_boun(i) = num_boun(i) + 1
            end do
            nsurfaces = nsurfaces + 1
          case default
            write(*,'(/a/a,i0/)') 'Error in read_mesh_ideas:', &
              ' Element type unsupported: ', ife
            stop
        end select
      else
        do
          read(unit_unv,'(a6)') start_id
          if (start_id == '    -1') then
            exit
          end if
        end do
      end if
    end do

    rewind(unit_unv)

!   read element group information of universal file

    allocate(color(mesh%nelem))

    do

      read(unit_unv,'(i10)', iostat=ios) istart  ! dataset start id (    -1)
      if (ios /= 0) exit
      read(unit_unv,*) idaset        ! dataset number

      if (idaset == 2412) then       ! element connectivity
        do
          read(unit_unv,'(6i10)') elem, i, iphy, imat, icolor, inode
          if (elem == -1) exit

          iend = 1 + (inode-1)/8
          do i = 1, iend
            read(unit_unv,*)
          end do

          color(elem) = icolor
        end do
      else
        do
          read(unit_unv,'(a6)') start_id
          if (start_id == '    -1') then
            exit
          end if
        end do
      end if
    end do

    rewind(unit_unv)

!   count the number of groups in a mesh
!   color map
!   group number, color
!     1 --> green  (=7 )    *** default color for a single group
!     2 --> blue   (=1 )
!     3 --> orange (=10)
!     4 --> Red    (=11)
!     5 --> Magenta(=12)
!     6 --> Pink   (=14)
!     7 --> Cyan   (=4 )

    color_grp = 0

    iptr = 1

    color_grp(1,iptr) = green   ! color number default = 7 (green)

    do elem = 1, mesh%nelem
      if (any (color(elem) == color_grp(1,1:iptr) )) then
        cycle
      else
        iptr = iptr + 1
        color_grp(1,iptr) = color(elem)
      end if
    end do

    mesh%nelgrp = iptr

    do elgrp = 1, mesh%nelgrp
      select case (color_grp(1,elgrp))
        case (7);  color_grp(2,elgrp) = 1
        case (1);  color_grp(2,elgrp) = 2
        case (10); color_grp(2,elgrp) = 3
        case (11); color_grp(2,elgrp) = 4
        case (12); color_grp(2,elgrp) = 5
        case (14); color_grp(2,elgrp) = 6
        case (4);  color_grp(2,elgrp) = 7
        case default
          write(*,'(/a/a,i0/)') 'Error in read_mesh_ideas:', &
            'color number exceeds bound: ', color_grp(1,elgrp)
          stop
      end select
    end do

!   element and group info

    select case (ife) ! ideas finite element mesh id
      case(91)        ! 3-node triangle
        mesh%ndim = 3
        elshape   = 3
        numnod    = 3
        allocate (iseq(numnod), jseq(numnod), nelnod(numnod,mesh%nelem))
        iseq = [1,2,3]
        jseq = [1,3,2]
      case(92)        ! 6-node triangle
        mesh%ndim = 3
        elshape   = 4
        numnod    = 6
        allocate (iseq(numnod), jseq(numnod), nelnod(numnod,mesh%nelem))
        iseq = [1,2,3,4,5,6]
        jseq = [1,6,5,4,3,2]
      case(94)        ! 4-node quadrilateral
        mesh%ndim = 3
        elshape   = 5
        numnod    = 4
      case(95)        ! 8-node quadrilateral
        mesh%ndim = 3
        elshape   = 30
        numnod    = 8
        allocate (iseq(numnod), jseq(numnod), nelnod(numnod,mesh%nelem))
        iseq = [1,2,3,4,5,6,7,8]
        jseq = [1,8,7,6,5,4,3,2]
      case(111)       ! 4-node tetrahedron
        mesh%ndim = 3
        elshape   = 11
        numnod    = 4
      case(115)       ! 8-node hexahedron
        mesh%ndim = 3
        elshape   = 13
        numnod    = 8
      case(116)       ! 20-node hexahedron
        mesh%ndim = 3
        elshape   = 31
        numnod    = 20
        allocate (iseq(numnod), jseq(numnod), nelnod(numnod,mesh%nelem))
        iseq = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
        jseq = [1,2,3,8,4,7,6,5,9,10,12,11,13,14,15,20,16,19,18,17]
      case(118)       ! 10-node tetrahedron
        mesh%ndim = 3
        elshape   = 12
        numnod    = 10
      case default
        call errormsg_case_default ( 'read_mesh_ideas', &
          'ife', int_value=ife )
    end select

    allocate( mesh%element(mesh%nelgrp) )
    allocate( mesh%element_blend(mesh%nelgrp,0) )
    mesh%nnodes_blend = [0,mesh%nnodes]
    allocate( mesh%grpnumel(mesh%nelgrp) )
    allocate( grp_elem(2,mesh%nelem ) )

    mesh%element(:)%ndim = mesh%ndim

    if ( mesh%nelgrp == 1 ) then

      mesh%element(1)%elshape = elshape
      mesh%element(1)%numnod  = numnod
      mesh%grpnumel(1)        = mesh%nelem
      do i = 1, mesh%nelem
        grp_elem(1,i) = 1
        grp_elem(2,i) = i
      end do

    else

      mesh%element(:)%elshape = elshape
      mesh%element(:)%numnod  = numnod

      mesh%grpnumel = 0
      do elem = 1, mesh%nelem

        do elgrp = 1, mesh%nelgrp
          if (color(elem) == color_grp(1,elgrp)) then
            j = color_grp(2,elgrp)                    ! group number
            mesh%grpnumel(j) = mesh%grpnumel(j) + 1
            grp_elem(1,elem) = j                      ! group number of element
            grp_elem(2,elem) = mesh%grpnumel(j)       ! element number in group
          end if
        end do

      end do

    end if

!   set globalshape of elements

    do elgrp = 1, mesh%nelgrp
      select case ( mesh%element(elgrp)%elshape )
        case (1,2); mesh%element(elgrp)%globalshape = 'line'
        case (3,4,7,10); mesh%element(elgrp)%globalshape = 'triangle'
        case (5,6,9,30); mesh%element(elgrp)%globalshape = 'quadrilateral'
        case (13,14,17,31); mesh%element(elgrp)%globalshape = 'hexahedron'
        case (11,12,15,16,18); mesh%element(elgrp)%globalshape = 'tetrahedron'
        case default
          call errormsg_case_default ( 'read_mesh_ideas', &
          'mesh%element(elgrp)%elshape', int_value=mesh%element(elgrp)%elshape )
      end select
    end do

    allocate( mesh%topology(mesh%nelgrp) )

    allocate (x(nnodes), y(nnodes), z(nnodes))

    do elgrp = 1, mesh%nelgrp
      allocate( mesh%topology(elgrp)%a(mesh%element(elgrp)%numnod, &
                            & mesh%grpnumel(elgrp) ) )
    end do

    rewind(unit_unv)

    do

      read(unit_unv,'(i10)', iostat=ios) istart  ! dataset start id (    -1)
      if (ios /= 0) exit
      read(unit_unv,*) idaset        ! dataset number

      if (idaset == 2411) then       ! node coordinates
        do
          read(unit_unv,'(4i10)') node, ic, ic_disp, icolor
          if (node == -1) exit
          read (unit_unv, *) x(node), y(node), z(node)
        end do
      else if (idaset == 2412) then  ! element connectivity
        do
          read(unit_unv,'(6i10)') elem_unv, i, iphy, imat, icolor, inode

          if (elem_unv == -1) exit

          ife   = i
          elgrp = grp_elem(1,elem_unv)
          elem  = grp_elem(2,elem_unv)
          numnod= mesh%element(elgrp)%numnod

          select case (ife)
            case (91)       ! 3-node triangle
              read(unit_unv,'(3i10)')  mesh%topology(elgrp)%a(jseq,elem)
            case (92)       ! 6-node triangle
              read(unit_unv,'(6i10)')  mesh%topology(elgrp)%a(jseq,elem)
            case (94)       ! 4-node quadrilaterial
              read(unit_unv,'(4i10)')  mesh%topology(elgrp)%a(:,elem)
            case (95)       ! 8-node quadrilaterial
              read(unit_unv,'(8i10)')  mesh%topology(elgrp)%a(jseq,elem)
            case (111)      ! 4-node tetrahedron
              read(unit_unv,'(4i10)')  mesh%topology(elgrp)%a(:,elem)
            case (115)      ! 8-node hexahedron
              read(unit_unv,'(8i10)')  mesh%topology(elgrp)%a(:,elem)
            case (116)      ! 20-node hexahedron
              read(unit_unv,'(8i10)') nelnod(1 :8 ,elem_unv)
              read(unit_unv,'(8i10)') nelnod(9 :16,elem_unv)
              read(unit_unv,'(4i10)') nelnod(17:20,elem_unv)
              mesh%topology(elgrp)%a(iseq,elem) = nelnod(jseq,elem_unv)
            case (118)      ! 10-node tetrahedron
              read(unit_unv,'(8i10)')  mesh%topology(elgrp)%a(1:8, elem)
              read(unit_unv,'(2i10)')  mesh%topology(elgrp)%a(9:10,elem)
            case default
              call errormsg_case_default ( 'read_mesh_ideas', &
                'ife', int_value=ife )
          end select
        end do
      else
        do
          read(unit_unv,'(a6)') start_id
          if (start_id == '    -1') then
            exit
          end if
        end do
      end if
    end do

!   nodal coordinates

    mesh%nnodes = nnodes
    allocate( mesh%coor(nnodes,mesh%ndim) )
    do node = 1, mesh%nnodes
      mesh%coor(node,:) = [x(node),y(node),z(node)]
    end do


!   points

    allocate( mesh%points(MAXPOINTS) )

    mesh%npoints = 0


!   curves

    if (ncurves > 0) then

      mesh%ncurves = ncurves
      allocate( mesh%curves(max(ncurves,MAXCURVES)), curves(ncurves) )
      mesh%curves(:mesh%ncurves)%ndim = mesh%ndim

      do curve = 1, mesh%ncurves
        curves(curve)%nelem = num_boun(curve)
        allocate ( curves(curve)%boun(curves(curve)%nelem) )
        mesh%curves(curve)%nelem = num_boun(curve)
        mesh%curves(curve)%nblend = 0
        allocate(mesh%curves(curve)%element_blend(0))
      end do

    else

      mesh%ncurves = 0
      allocate( mesh%curves(MAXCURVES) )

    end if

!   surfaces

    if (nsurfaces > 0) then

      mesh%nsurfaces = nsurfaces
      allocate( mesh%surfaces(max(nsurfaces,MAXSURFACES)), surfaces(nsurfaces) )
      mesh%surfaces(:mesh%nsurfaces)%ndim = mesh%ndim

      do surface = 1, mesh%nsurfaces
        surfaces(surface)%nelem = num_boun(surface)
        allocate ( surfaces(surface)%boun(surfaces(surface)%nelem) )
        mesh%surfaces(surface)%nelem = num_boun(surface)
        mesh%surfaces(surface)%nblend = 0
        allocate(mesh%surfaces(surface)%element_blend(0))
      end do

    else

      mesh%nsurfaces = 0
      allocate( mesh%surfaces(MAXSURFACES) )

    end if

!   derive curve/surface topology information
!   local node sequence at a face (defined in ideas) of element group elgrp
!   curve_node_seq(i,face,elgrp)
!   surface_node_seq(i,face,elgrp)

    call derivations(mesh, surface_node_seq, curve_node_seq)

    allocate (boun_nodes(mesh%nnodes))

!   read curves & surface information from a unversal file

    rewind(unit_unv)

    do

      read(unit_unv,'(i10)', iostat=ios) istart  ! dataset start id (    -1)
      if (ios /= 0) exit
      read(unit_unv,*) idaset                    ! dataset number

      if (idaset == 790) then                    ! curves from load set data
                                                 ! for BCs
        select case (ife)
          case (91,92,94,95)
            read(unit_unv,'(2i10)') i, iload     ! i : curve number
            if (i < 0) exit
            read(unit_unv,'(a)') load_set_name

            face = 0
            do
              read(unit_unv,'(4i10)') n, elem, iface, icolor
              if (n == -1) exit
              do j = 1, 5
                read(unit_unv,*)
              end do
              face = face + 1
              curves(i)%boun(face)%elem_unv = elem
              curves(i)%boun(face)%face_unv = iface
              curves(i)%boun(face)%elgrp    = grp_elem(1,elem)
              curves(i)%boun(face)%elem     = grp_elem(2,elem)

              elgrp   = curves(i)%boun(face)%elgrp
              elshape = mesh%element(elgrp)%elshape

              select case(elshape)
                case (3)
                  curves(i)%boun(face)%elshape = 1
                  curves(i)%boun(face)%elnumnod = 2
                  curves(i)%boun(face)%elglobalshape = 'line'
                case (4)
                  curves(i)%boun(face)%elshape = 2
                  curves(i)%boun(face)%elnumnod = 3
                  curves(i)%boun(face)%elglobalshape = 'line'
                case (5)
                  curves(i)%boun(face)%elshape = 1
                  curves(i)%boun(face)%elnumnod = 2
                  curves(i)%boun(face)%elglobalshape = 'line'
                case (30)
                  curves(i)%boun(face)%elshape = 2
                  curves(i)%boun(face)%elnumnod = 3
                  curves(i)%boun(face)%elglobalshape = 'line'
                case default
                  call errormsg_case_default ( 'read_mesh_ideas', &
                    'elshape', int_value=elshape )
              end select
            end do

!           set boun_nodes to zero

            boun_nodes = 0

            curve = i

            mesh%curves(curve)%element%globalshape = &
                                           curves(curve)%boun(1)%elglobalshape
            mesh%curves(curve)%element%elshape = curves(curve)%boun(1)%elshape
            mesh%curves(curve)%element%numnod = curves(curve)%boun(1)%elnumnod
            mesh%curves(curve)%element%ndim = mesh%ndim

            allocate ( &
              &mesh%curves(curve)%topology(mesh%curves(curve)%element%numnod,&
                                              &mesh%curves(curve)%nelem,2) )

            do n = 1, curves(curve)%nelem

              elgrp = curves(curve)%boun(n)%elgrp
              elem  = curves(curve)%boun(n)%elem
              face  = curves(curve)%boun(n)%face_unv

              boun_nodes(&
                mesh%topology(elgrp)%a(curve_node_seq(:,face,elgrp),elem)) = 1
              mesh%curves(curve)%topology(:,n,2) = &
                mesh%topology(elgrp)%a(curve_node_seq(:,face,elgrp),elem)

            end do

            mesh%curves(curve)%nnodes = count (boun_nodes == 1)

            mesh%curves(curve)%nnodes_blend = [0,mesh%curves(curve)%nnodes]

            allocate (mesh%curves(curve)%nodes(mesh%curves(curve)%nnodes))

!           fill local nodes

            lnode = 0
            do node = 1, mesh%nnodes
              if (boun_nodes(node) == 0) cycle
              lnode = lnode + 1
              mesh%curves(curve)%nodes(lnode) = node
              boun_nodes(node) = lnode
            end do

            if (lnode /= mesh%curves(curve)%nnodes) then
              write(*,'(/a,2i0/)') 'Error in read_mesh_ideas:', &
                'lnode, nnodes', lnode, mesh%curves(curve)%nnodes
              stop
            end if

!           fill local topology

            do elem = 1, mesh%curves(curve)%nelem
              mesh%curves(curve)%topology(:,elem,1) = &
                boun_nodes( mesh%curves(curve)%topology(:,elem,2) )
            end do

          case (111,115,116,118)
            read(unit_unv,'(2i10)') i, iload        ! i : surface number
            if (i < 0) exit
            read(unit_unv,'(a)') load_set_name

            face = 0
            do
              read(unit_unv,'(4i10)') n, elem, iface, icolor
              if (n == -1) exit
              read(unit_unv,*) tvar
              read(unit_unv,*) dummy
              face = face + 1
              surfaces(i)%boun(face)%elem_unv = elem
              surfaces(i)%boun(face)%face_unv = iface
              surfaces(i)%boun(face)%elgrp    = grp_elem(1,elem)
              surfaces(i)%boun(face)%elem     = grp_elem(2,elem)

              elgrp   = surfaces(i)%boun(face)%elgrp
              elshape = mesh%element(elgrp)%elshape

              select case(elshape)
                case (11)
                  surfaces(i)%boun(face)%elshape = 3
                  surfaces(i)%boun(face)%elnumnod = 3
                  surfaces(i)%boun(face)%elglobalshape = 'triangle'
                case (12)
                  surfaces(i)%boun(face)%elshape = 4
                  surfaces(i)%boun(face)%elnumnod = 6
                  surfaces(i)%boun(face)%elglobalshape = 'triangle'
                case (13)
                  surfaces(i)%boun(face)%elshape = 5
                  surfaces(i)%boun(face)%elnumnod = 4
                  surfaces(i)%boun(face)%elglobalshape = 'quadrilateral'
                case (14)
                  surfaces(i)%boun(face)%elshape = 6
                  surfaces(i)%boun(face)%elnumnod = 9
                  surfaces(i)%boun(face)%elglobalshape = 'quadrilateral'
                case (31)
                  surfaces(i)%boun(face)%elshape = 30
                  surfaces(i)%boun(face)%elnumnod = 8
                  surfaces(i)%boun(face)%elglobalshape = 'quadrilateral'
                case default
                  call errormsg_case_default ( 'read_mesh_ideas', &
                    'elshape', int_value=elshape )
              end select
            end do

!           set boun_nodes to zero

            boun_nodes = 0

            surface = i

            mesh%surfaces(surface)%element%globalshape = &
                                         surfaces(surface)%boun(1)%elglobalshape
            mesh%surfaces(surface)%element%elshape = &
                                         surfaces(surface)%boun(1)%elshape
            mesh%surfaces(surface)%element%numnod = &
                                         surfaces(surface)%boun(1)%elnumnod
            mesh%surfaces(surface)%element%ndim = mesh%ndim

            allocate ( mesh%surfaces(surface)%topology(&
                                    mesh%surfaces(surface)%element%numnod,&
                                    mesh%surfaces(surface)%nelem,2) )

            do n = 1, surfaces(surface)%nelem

              elgrp = surfaces(surface)%boun(n)%elgrp
              elem  = surfaces(surface)%boun(n)%elem
              face  = surfaces(surface)%boun(n)%face_unv

              boun_nodes(&
                mesh%topology(elgrp)%a(surface_node_seq(:,face,elgrp),elem)) = 1
              mesh%surfaces(surface)%topology(:,n,2) = &
                mesh%topology(elgrp)%a(surface_node_seq(:,face,elgrp),elem)

            end do

            mesh%surfaces(surface)%nnodes = count (boun_nodes == 1)

            mesh%surfaces(surface)%nnodes_blend = &
                                         [0,mesh%surfaces(surface)%nnodes]

            allocate(&
                  mesh%surfaces(surface)%nodes(mesh%surfaces(surface)%nnodes))

!           fill local nodes

            lnode = 0
            do node = 1, mesh%nnodes
              if (boun_nodes(node) == 0) cycle
              lnode = lnode + 1
              mesh%surfaces(surface)%nodes(lnode) = node
              boun_nodes(node) = lnode
            end do

            if (lnode /= mesh%surfaces(surface)%nnodes) then
              write(*,'(/a,2i0/)') 'Error in read_mesh_ideas:', &
                'lnode, nnodes', lnode, mesh%surfaces(surface)%nnodes
              stop
            end if

!           fill local topology

            do elem = 1, mesh%surfaces(surface)%nelem
              mesh%surfaces(surface)%topology(:,elem,1) = &
                boun_nodes( mesh%surfaces(surface)%topology(:,elem,2) )
            end do

          case default
            write(*,'(/a/a,i0/)') 'Error in read_mesh_ideas:', &
              ' Element type unsupported: ', ife
            stop
        end select
      else
        do
          read(unit_unv,'(a6)') start_id
          if (start_id == '    -1') then
            exit
          end if
        end do
      end if

    end do

!   volumes

    allocate ( mesh%volumes(MAXVOLUMES) )

!   blocks

    allocate( mesh%blocks(MAXBLOCKS) )

!   objects

    allocate( mesh%objects(MAXOBJECTS) )

!   nodesets

    allocate ( mesh%nodesets(MAXNODESETS) )

!   elementsets

    allocate ( mesh%elementsets(MAXELEMENTSETS) )

    mesh%meshgen = .true.

    close(unit = unit_unv)

!   array deallocation

    deallocate (color, x, y, z)
    deallocate (boun_nodes)

    if (allocated (nelnod)) deallocate (nelnod)

    if (allocated (iseq)) deallocate (iseq)
    if (allocated (jseq)) deallocate (jseq)

    if (allocated (nseq)) deallocate (nseq)
    if (allocated (neladj)) deallocate (neladj)
    if (allocated (faceadj)) deallocate (faceadj)

    if (allocated (grp_elem)) deallocate (grp_elem)
    if (allocated (ne)) deallocate (ne)

    if (allocated (curves)) then
      do curve = 1, ncurves
        deallocate (curves(curve)%boun)
      end do
      deallocate (curves)
    end if

    if (allocated (surfaces)) then
      do surface = 1, nsurfaces
        deallocate (surfaces(surface)%boun)
      end do
      deallocate (surfaces)
    end if

    if (allocated (curve_node_seq)) deallocate (curve_node_seq)
    if (allocated (surface_node_seq)) deallocate (surface_node_seq)

    deallocate ( num_boun )

  end subroutine read_mesh_ideas


  subroutine derivations ( mesh, surface_node_seq, curve_node_seq )

    type(mesh_t), intent(inout) :: mesh
    integer, intent(inout),allocatable,dimension(:,:,:) :: surface_node_seq
    integer, intent(inout),allocatable,dimension(:,:,:) :: curve_node_seq

    integer :: elshape, elgrp

    integer :: numnod

    integer :: nnf

!   numnod: number of surface nodes

    do elgrp = 1, mesh%nelgrp

      elshape = mesh%element(elgrp)%elshape

      select case (elshape)
        case(3,5,9,10)       ; numnod = 2
        case(4,6,7,11,18,30) ; numnod = 3
        case(13,17)          ; numnod = 4
        case(12,15)          ; numnod = 6
        case(16)             ; numnod = 7
        case(14)             ; numnod = 9
        case(31)             ; numnod = 8
        case default
          write(*,'(/a/a,i0/)') 'Error in read_mesh_ideas:', &
            ' Unknown elshape: ', elshape
          stop
      end select

!     number of faces

      select case (elshape)
        case(3,4,7,10)                ; nnf = 3
        case(5,6,9,11,12,15,16,18,30) ; nnf = 4
        case(13,14,17,31)             ; nnf = 6
        case default
          write(*,'(/a/a,i0/)') 'Error in read_mesh_ideas:', &
            ' Unknown elshape: ', elshape
          stop
      end select

    end do

!   allocate array

    allocate ( surface_node_seq(numnod,nnf,mesh%nelgrp) )
    allocate ( curve_node_seq  (numnod,nnf,mesh%nelgrp) )

!   define curve (or surface) node sequence
!   i    : local node number of the element of tfem
!   face : face number defined in ideas
!   surface_node_seq(i,face)

    do elgrp = 1, mesh%nelgrp

      elshape = mesh%element(elgrp)%elshape

!     Curves

      select case (elshape)
        case(3)
          curve_node_seq(:,1,elgrp) = [1,2]
          curve_node_seq(:,2,elgrp) = [2,3]
          curve_node_seq(:,3,elgrp) = [3,1]
        case(4)
          curve_node_seq(:,1,elgrp) = [1,2,3]
          curve_node_seq(:,2,elgrp) = [3,4,5]
          curve_node_seq(:,3,elgrp) = [5,6,1]
        case(5)
          curve_node_seq(:,1,elgrp) = [1,2]
          curve_node_seq(:,2,elgrp) = [2,3]
          curve_node_seq(:,3,elgrp) = [3,4]
          curve_node_seq(:,4,elgrp) = [4,1]
        case(30)
          curve_node_seq(:,1,elgrp) = [1,8,7]
          curve_node_seq(:,2,elgrp) = [7,6,5]
          curve_node_seq(:,3,elgrp) = [5,4,3]
          curve_node_seq(:,4,elgrp) = [3,2,1]
        case default
          call errormsg_case_default ( 'derivations', &
            'elshape', int_value=elshape )
      end select

!     Surfaces

      select case (elshape)
        case(11)
          surface_node_seq(:,1,elgrp) = [1,3,2]
          surface_node_seq(:,2,elgrp) = [1,2,4]
          surface_node_seq(:,3,elgrp) = [2,3,4]
          surface_node_seq(:,4,elgrp) = [1,4,3]
        case(12)
          surface_node_seq(:,1,elgrp) = [1,6,5,4,3,2]
          surface_node_seq(:,2,elgrp) = [1,2,3,8,10,7]
          surface_node_seq(:,3,elgrp) = [3,4,5,9,10,8]
          surface_node_seq(:,4,elgrp) = [1,7,10,9,5,6]
        case(31)
          surface_node_seq(:,1,elgrp) = [1,4,6,7,8,5,3,2]
          surface_node_seq(:,2,elgrp) = [13,14,15,17,20,19,18,16]
          surface_node_seq(:,3,elgrp) = [1,2,3,10,15,14,13,9]
          surface_node_seq(:,4,elgrp) = [3,5,8,12,20,17,15,10]
          surface_node_seq(:,5,elgrp) = [6,11,18,19,20,12,8,7]
          surface_node_seq(:,6,elgrp) = [1,9,13,16,18,11,6,4]
        case default
          call errormsg_case_default ( 'derivations', &
            'elshape', int_value=elshape )
      end select

    end do

  end subroutine derivations

end module ideas_utils_m


