! Fluctuating Stokes problem:
! Circle confined in a rectangular domain under the effect of an external
! harmonic potential.
! Predictor-Corrector time integration scheme to account for the divergence
! of the mobility.
! ALE body-fitting mesh scheme.
! Mesh generated by Gmsh using triangles.
! A remeshing is performed when the maximum normalized area or aspect ratio
! of the mesh elements is higher than a threshold.

program fh_2

  use tfem_m
  use hsl_ma57_m
  use generalized_stokes_elements_m
  use io_utils_m
  use figplot_m
  use subs3_m
  use update_mesh_nodes3_m
  use ziggurat_m
  use timer_m

  implicit none

! constants

  integer, parameter :: &
    uintpl = 6,             & ! P2 velocities
    pintpl = 2,             & ! P1 pressures
    physqvel = 1,           & ! physical quantity nr of the velocities
    physqpress = 2,         & ! physical quantity nr of the pressures
    gauss = 6,              & ! 6-point Gauss integration of triangles !6
    gaussb = 3,             & ! 3 point integration of boundary elements !3
    vtkevery = -1,          & ! vtk file every vtkevery steps. -1: means none
    numtimesteps =1000000,  & ! total number of timesteps
    ran = 3

  real(dp), parameter :: &
    eta = 1.0_dp,         & ! viscosity
    deltat0 = 0.02_dp,    & ! time step
    area_threshold = 1.1_dp,          & ! remeshing area threshold
    aspect_ratio_threshold = 1.05_dp, & ! remeshing aspect ratio threshold
    dist_toll = 0.1_dp,&  ! parameter related to how close to the wall
                          ! the mesh starts getting refined
    min_num = 4.1_dp      ! minimum number of elements in between particle
                          ! and wall

! definitions

  type(mesh_t) :: mesh
  type(input_probdef_t) :: input_probdef1, input_probdef2
  type(problem_t) :: problem1, problem2
  type(sysmatrix_t) :: sysmatrix
  type(sysvector_t), target :: sol, sol2
  type(sysvector_t) :: rhsd, rhsd1, rhsd2
  type(plot_options_t) :: plot_options
  type(oldvectors_t) :: oldvectors, oldvectors2, oldvectors3
  type(coefficients_t) :: coefficients
  type(vector_t), target :: pressure, stress_tensor
  type(solver_options_ma57_t) :: solver_options_ma57

  type(problem_t) :: problem_pois

  integer(si) :: seed

  integer :: i, step, ipost=0
  real(dp) :: time=0.0_dp
  real(dp) :: dx_box, dx_part, dx_part1, dx_part2, dx_bound1, dx_bound2, &
    dx_part_def

  real(dp) :: ox, oy, lx, ly, seed_rnd
  real(dp) :: up(3), un(3), pp(3), ppn(3), pp1(3)

  real(dp), dimension(:), allocatable :: init_area, areav
  real(dp), dimension(:), allocatable :: init_aspect_ratio, aspect_ratio
  real(dp) :: norm_area, norm_aspect_ratio

  character(len=30) :: filename
  logical :: remeshing=.false., seed_random = .true., pred_step

  open (unit = 100, file='output.out')

  solver_options_ma57%real_storage=2.0

! initialize RNG
  if ( ran == 2 .or. ran == 3 ) then
    if ( seed_random ) then
      call init_random_seed ( )
      call random_number ( seed_rnd )
      seed = floor( seed_rnd*1.e8_dp )
    end if
    call zigset ( seed )  ! ziggurat
  end if


! fill coefficients
  call create_coefficients ( coefficients, ncoefi=300, ncoefr=250 )

  coefficients%i = 0
  coefficients%i(1:11) = &
    [ uintpl,   pintpl,     0,     0,         0,  &
      physqvel, physqpress, 0,     0,     gauss,  &
      gaussb ]

  coefficients%i(12:) = 0
  coefficients%i(256) = ran  ! random number generator

  coefficients%r = 0
  coefficients%r(1) = eta
  coefficients%r(208) = 1 ! kT



  call write_coefficients ( coefficients, filename='coefficients.out' )

!Setting harmonic spring constant:
  spr_const = 1.0_dp


! mesh parameters
  ox = -10.0_dp
  oy = -1.0_dp
  lx =  20.0_dp
  ly =  2.0_dp

! one particle
  rp(1) = 0.5_dp         ! particle radius
  xp(1,1) = 2.0*(uni()-0.5_dp)   ! x-position of the particle from uniform
                                 ! distribution
  xp(1,2) = 0.979*(uni()-0.5_dp) ! y-position of the particle from uniform
                                 ! distribution

  pp = [ (xp(1,i),i=1,2), 0._dp ]

  dx_box = 1.5_dp        ! element spacing on the external boundaries far away
                         ! from the particle
  dx_part = 0.075_dp     ! element spacing on the particle boundary
  dx_part_def = 0.075_dp ! default element spacing on the particle boundary

  deltat = deltat0

  call generate_read_mesh


! plot mesh
  plot_options%fontsize = 6
  call plot_points_curves ( plot_options, mesh, 'curves.fig' )
  plot_options%fontsize = 10
  call plot_mesh ( plot_options, mesh, 'mesh.fig' )

! define problem, essential conditions and constraints
  call initialize_problem1

! define problem, essential conditions and constraints
  call initialize_problem2


! start time integration
  time = 0
  step = 0

  call tic

  do

    xp(1,1:2) = pp(1:2)
    dragv(:) = 0.0_dp

!   Starting the predictor step
    pred_step = .true.

    deltat = deltat0

    call create_system_matrix   ! create new system matrix

!   build and solve the fluctuating constrained system
    call build_solve_system

!   get particle velocity:
    call get_sysvector_constraint ( mesh, problem1, sol, constraint=1, &
      addunknowns=.true., u=up )

!   Predictor step:
    un = up
    ppn = pp

!   Check if the particle has overlapped with the wall:
!   (Note that we consider overlap if the particle is closer to the wall
!    than 2% of its radius)
    if ( ( abs( pp(2)  + sqrt(deltat) * un(2) ) ) >= &
                                     ly/2.0_dp-rp(1)*1.02_dp) then

!     if particle overlapped adjust the timestep size:
      if ( pp(2) > 0.0_dp) then
        deltat = 0.95*( (ly/2.0_dp-rp(1)*1.02_dp - pp(2)) / un(2) )**2
      else
        deltat = 0.95*( (-ly/2.0_dp+rp(1)*1.02_dp - pp(2)) /un(2) )**2
      end if

      call create_system_matrix   ! create new system matrix

!     build and solve the system with the new timestepsize
      call build_solve_system3

      call get_sysvector_constraint ( mesh, problem1, sol, constraint=1, &
        addunknowns=.true., u=up )

      un(:) = up(:)

    end if

!   Update the particle position
    pp = pp + sqrt(deltat) * un

!*************************************************
!   Double-check that the particle is inside the domain:
    if( ( ( abs(pp(2)) >= ly/2.0_dp-rp(1)*1.02_dp ) ) &
              .or.( abs(pp(1)) >=lx/2.0-rp(1)*1.02_dp ) ) then

!     REJECTIONS SHOULD NOT HAPPEN ANYMORE, IF A SKIPPED TIMESTEP OCCURS
!     VERIFY THE CODE
      pp = ppn
      print *, 'skipped predictor time-step'
      cycle

    end if
!*************************************************


    call create_system_matrix2   ! create new system matrix

!   Drag force computing step:
    call build_solve_system2       ! build and solve the system

!   Computing the viscous resistance force on the particle:
    call compute_drag

!   The External force (Brownian/Flow/External Pot.) is Equal to -dragv
    dragv(:) = -dragv(:)

!   To get the Brownian force we have to subtract the external
!   conservative force:
    dragv(1) = dragv(1) +sqrt(deltat)*spr_const*xp(1,1)

!   Move the particle to the predicted position update mesh nodes:
!   solve a Laplace's equation
    call update_mesh_nodes ( mesh, problem_pois, pp(1:2)-ppn(1:2) )

    xp(1,1:2) = pp(1:2)

!   Start the corrector step:
    pred_step = .false.

    call create_system_matrix   ! create new system matrix

!   build and solve the constrained system, no fluctuation in the fluid
    call build_solve_system

    call get_sysvector_constraint ( mesh, problem1, sol, constraint=1, &
      addunknowns=.true., u=up )

!   Corrector step
    pp1 = ppn + 0.5*sqrt(deltat)*(up + un )

!***************************************
!   Double-check again that the particle is inside the domain:
    if ( ( ( abs(pp1(2)) >= (ly/2.0_dp-rp(1)*1.02_dp ) ) ) &
         .or. ( abs(pp1(1))>=lx/2.0-rp(1)*1.02_dp ) ) then

!     Rejecting step code:
!     REJECTIONS SHOULD NOT HAPPEN ANYMORE, IF A SKIPPED TIMESTEP OCCURS
!     VERIFY THE CODE
!     using old mesh>>>update mesh nodes: solve a Laplace's equation
      call update_mesh_nodes ( mesh, problem_pois, -(pp(1:2)-ppn(1:2)) )
      print*, 'skipped corrector time-step', pp(:),pp1(:),ppn(:)
      print*,'corrector and predictor velcocities:', up(:), un(:)
      pp=ppn
      cycle

    end if
!*************************************************


!   Move the particle to the corrected position, update mesh nodes:
!   solve a Laplace's equation
    call update_mesh_nodes ( mesh, problem_pois, pp1(1:2)-pp(1:2) )

    pp = pp1
    step = step + 1
    time = time + deltat


!   Post-processing

!   extract info on particle

    write ( *, '(1X,A,I0,F15.6)' ) 'step = ', step, time
    write ( 100 , '(1X,60F13.9)') pp(1:2), deltat/(numtimesteps*deltat0)

!   compute current aspect ratio
    call compute_element_aspect_ratio ( mesh, areav, aspect_ratio )

!   compute maximum normalized aspect ratio and area
!   (with respect to the initial values)
    norm_area = maxval( abs(log(areav/init_area)) )
    norm_aspect_ratio = maxval( abs(log(aspect_ratio/init_aspect_ratio)) )


!   remeshing criterion
    if ( ( norm_area >= area_threshold .or. &
         norm_aspect_ratio >= aspect_ratio_threshold ) .and. &
         step /= numtimesteps ) then
      remeshing = .true.
      print *,'Doing remeshing...'
    end if

    if ( remeshing ) then

      call delete_old_problem     ! delete old mesh, problem, ...

      call generate_read_mesh     ! generate and read mesh

      call initialize_problem1     ! define new problem

      call initialize_problem2

      remeshing = .false.

    end if

!   write VTK files

    if ( vtkevery > 0 ) then
      if ( mod(step,vtkevery) == 0 ) then

        ipost = ipost + 1
        write(filename,'(a,i4.4,a)') 'mesh', ipost, '.vtk'

        call write_mesh_vtk ( mesh, filename=filename )

      end if
    end if


    if ( time >= numtimesteps*deltat0 ) exit


  end do

  close(unit=100)

  call toc

! delete all data including all allocated memory

  call delete ( problem1, problem2 )
  call delete ( input_probdef1, input_probdef2 )
  call delete ( mesh )
  call delete ( sol, sol2 )
  call delete ( rhsd, rhsd1, rhsd2 )
  call delete ( coefficients )
  call delete ( oldvectors, oldvectors2 )
  call delete ( problem_pois )

contains



!*******************************************************************
! random seed generation

  subroutine init_random_seed ( )

    use, intrinsic :: iso_fortran_env, only: int64

    integer :: i, n
    integer(int64) :: clock
    integer, dimension(:), allocatable :: seed

    call random_seed ( size = n )
    allocate ( seed(n) )

    call system_clock ( count = clock )

    seed = clock + 37 * [ (i - 1, i = 1, n) ]
    call random_seed ( put = seed )

    deallocate ( seed )

  end subroutine init_random_seed



! generate and read mesh

  subroutine generate_read_mesh

    integer :: iteration
    real(dp) :: dummy_correction

    iteration = 0
    dummy_correction = 1.0e-5_dp

    if( (xp(1,2)+rp(1)>=(ly/2.0_dp) - dist_toll) ) then

      dx_part1 =( (ly/2.0_dp) - (xp(1,2) +rp(1)) )/ min_num
      dx_bound1 = dx_part1
      dx_bound2 = 2.0_dp*dx_part_def
      dx_part2 = dx_part_def

    else if ( ( abs(xp(1,2)-rp(1))>=(ly/2.0_dp) - dist_toll ) ) then

      dx_part2 =( (ly/2.0_dp) - abs( (xp(1,2) -rp(1)) ) )/ min_num
      dx_bound2 = dx_part2
      dx_bound1 = 2.0_dp*dx_part_def
      dx_part1 = dx_part_def

    else

      dx_part1 = dx_part_def
      dx_part2 = dx_part1
      dx_bound1 = dx_part_def
      dx_bound2 = dx_bound1

    end if


!   Sometimes, for some specific choice of the mesh parameters gmsh is
!   surprisingly not able to generate a mesh.
!   In order to succesfully generate a mesh a small perturbation is iteratively
!   subtracted to the mesh parameters.

    do

      call write_gmsh_parameters ( ox, oy, lx, ly, xp, rp, dx_box, dx_part, &
        dx_part1, dx_part2,  dx_bound1, dx_bound2 )

      call execute_command_line ( 'gmsh -2 -order 2 -algo front2d -o mesh.msh &
                    &mesh.geo > outputmesh.out' )

!     read mesh generated by gmsh
      call read_mesh_gmsh ( mesh, filename='mesh.msh', ndim=2, physgeom=.true. )

      call fill_mesh_parts ( mesh )

      call write_mesh_vtk ( mesh, filename='mesh.vtk' )

      iteration = iteration + 1

      print*, 'mesh iteration number:', iteration

!     If the first condition is true, gmsh succesfully generated a mesh.
!     Note that 1500 is chosen for the present example, a different number
!     may be needed for different geometries
      if ( size(mesh%sidelem(1)%a ) >= 1500 ) then
        exit
      else
        call delete(mesh)
        dx_part1 = dx_part1 - dummy_correction
        dx_part2 = dx_part2 - dummy_correction
        dx_bound1 = dx_bound1 -dummy_correction
        dx_bound2 = dx_bound2 -dummy_correction
      end if

    end do

!   allocate aspect ratio arrays
    allocate ( init_area(mesh%nelem), areav(mesh%nelem) )
    allocate ( init_aspect_ratio(mesh%nelem), aspect_ratio(mesh%nelem) )

!   compute initial element aspect ratio
    call compute_element_aspect_ratio ( mesh, init_area, init_aspect_ratio )

    norm_area = 0.0_dp
    norm_aspect_ratio = 0.0_dp

  end subroutine generate_read_mesh


! compute the aspect ratio and area for each mesh element

  subroutine compute_element_aspect_ratio ( mesh, area, asp_ratio )

    type(mesh_t), intent(in) :: mesh
    real(dp), dimension(:), intent(out) :: asp_ratio, area

    integer, parameter :: elgrp=1
    integer :: elem, node(3)
    real(dp) :: la, lb, lc, sper
    real(dp) :: vert(3,2)

    do elem = 1,mesh%nelem

!     get coordinates of triangle vertices (local node numbers: 1, 3, 5)
      node = [1,3,5]
      vert = mesh%coor(mesh%topology(elgrp)%a(node,elem),:)

!     compute side lengths
      la = sqrt( (vert(1,1) - vert(2,1))**2 + (vert(1,2) - vert(2,2))**2 )
      lb = sqrt( (vert(2,1) - vert(3,1))**2 + (vert(2,2) - vert(3,2))**2 )
      lc = sqrt( (vert(3,1) - vert(1,1))**2 + (vert(3,2) - vert(1,2))**2 )

!     compute triangle semiperimeter and area
      sper = (la + lb + lc)/2.0_dp
      area(elem) = sqrt( sper*(sper - la)*(sper - lb)*(sper - lc) )

!     compute aspect ratio
      asp_ratio(elem) = max(la,lb,lc)**2/area(elem)

    end do

  end subroutine compute_element_aspect_ratio


! write the parameters in gmsh format

  subroutine write_gmsh_parameters ( ox, oy, lx, ly, xp, rp, dx_box, dx_part, &
    dx_part1, dx_part2, dx_bound1, dx_bound2 )

    real(dp), intent(in) :: ox, oy, lx, ly, xp(:,:), rp(:), dx_box, &
      dx_part, dx_part1, dx_part2, dx_bound1, dx_bound2

    integer :: i, nobj

    nobj = size(rp)

    open ( unit=25, file='mesh.geo' )

    write ( 25, '(1X,A,F18.14,A)' ) 'ox = ', ox, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'oy = ', oy, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'lx = ', lx, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'ly = ', ly, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'dx_box = ', dx_box, ';'
    write ( 25, '(1X,A,I0,A)' ) 'nobj = ', nobj, ';'

    do i = 1, nobj
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'xp[', i, '] = ', xp(i,1), ';'
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'yp[', i, '] = ', xp(i,2), ';'
      write ( 25, '(1X,A,I0,A,F18.14,A)' ) 'rp[', i, '] = ', rp(i), ';'
    end do

    write ( 25, '(1X,A,F18.14,A)' ) 'dx_part = ', dx_part, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'dx_part1 = ', dx_part1, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'dx_part2 = ', dx_part2, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'dx_bound1 = ', dx_bound1, ';'
    write ( 25, '(1X,A,F18.14,A)' ) 'dx_bound2 = ', dx_bound2, ';'

    write ( 25, '(/1x,a)' ) 'Include "particles_in_a_box_2D.igo";'

    close ( 25 )

  end subroutine write_gmsh_parameters


! define problem, bcs, constraints

  subroutine initialize_problem1

!   problem definition
    call create_input_probdef ( mesh, input_probdef1, nvec=4, nphysq=2 )

    input_probdef1%vec_elementdof(1)%a =   &
        reshape ( [2,2,2,2,2,2,    &  ! velocity
                    1,0,1,0,1,0,    &  ! pressure
                    1,1,1,1,1,1,    &  ! scalar, such as vorticity
                    3,3,3,3,3,3 ], &  ! symmetric two dimensional stress tensor
                     [6,4] )

    input_probdef1%physq = [1,2]

!   cell boundaries

    call define_essential ( mesh, input_probdef1, curve1=1, curve2=4, physq=1 )

    call define_essential ( mesh, input_probdef1, point=1, physq=2 )

!   constraint on particle boundary (freely floating)
     call define_constraint ( mesh, input_probdef1, curve1=5, physq=1, &
       discretization='collocation', nodedof=2, naddunknowns=3 )

    call problem_definition ( input_probdef1, mesh, problem1 )

!   create system vectors (solution and right-hand side)
    call create_sysvector ( problem1, sol, rhsd , rhsd1)

!   create oldvectors
    call create_oldvectors ( oldvectors, nsysvec=1 )
    oldvectors%s(1)%p => sol

    call fill_sysvector ( mesh, problem1, sol, curve1=1,curve2=4 , physq=1, &
      value=0.0_dp )

    call fill_sysvector ( mesh, problem1, sol, point=1, physq=2, value=0._dp )

  end subroutine initialize_problem1

  subroutine initialize_problem2

!   problem definition
    call create_input_probdef ( mesh, input_probdef2, nvec=4, nphysq=2 )

    input_probdef2%vec_elementdof(1)%a =   &
        reshape ( [2,2,2,2,2,2,    &  ! velocity
                    1,0,1,0,1,0,    &  ! pressure
                    1,1,1,1,1,1,    &  ! scalar, such as vorticity
                    3,3,3,3,3,3 ], &  ! two dimensional symmetric stress tensor
                     [6,4] )

    input_probdef2%physq = [1,2]

!   cell boundaries

    call define_essential ( mesh, input_probdef2, curve1=1, curve2=5, physq=1 )

    call define_essential ( mesh, input_probdef2, point=1, physq=2 )

    call problem_definition ( input_probdef2, mesh, problem2 )

!   create system vectors (solution and right-hand side)
    call create_sysvector ( problem2, sol2, rhsd2)

    call create_oldvectors ( oldvectors3, nsysvec=1 )
    oldvectors3%s(1)%p => sol2

!   create oldvectors
    call create_oldvectors ( oldvectors2, nvec=2 )

    call fill_sysvector ( mesh, problem2, sol2, curve1=1,curve2=5 , physq=1, &
      value=0.0_dp )

    call fill_sysvector ( mesh, problem2, sol2, point=1, physq=2, value=0._dp )

  end subroutine initialize_problem2

! create system matrix

  subroutine create_system_matrix

    call create_sysmatrix_structure_base ( sysmatrix, mesh, problem1, &
      symmetric=.true. )
    call create_sysmatrix_structure_constraint ( sysmatrix, mesh, problem1, diagonal = .true. )
    call finalize_sysmatrix_structure ( sysmatrix )

    call create_sysmatrix_data ( sysmatrix )

  end subroutine create_system_matrix

! create system matrix

  subroutine create_system_matrix2

    call create_sysmatrix_structure_base ( sysmatrix, mesh, problem2, &
      symmetric=.true. )
    call finalize_sysmatrix_structure ( sysmatrix )

    call create_sysmatrix_data ( sysmatrix )

  end subroutine create_system_matrix2

! build (assemble) matrix and vector from elements and solve

  subroutine build_solve_system

!   Stokes flow : velocity / pressure
    call build_system ( mesh, problem1, sysmatrix, rhsd1, elemsub=stokes_elem, &
      coefficients=coefficients )

    rhsd1%u = 0.0_dp

!   constraint on particle boundary
    call build_system_constraint ( mesh, problem1, sysmatrix, rhsd1, &
      constraint1=1, elemsub=elementc, addmatvec=.true., &
      coefficients=coefficients, diagonal = .true. )

    if (pred_step) then

!     FH hydrodynamics:
        call build_system ( mesh, problem1, sysmatrix, rhsd, &
          elemsub=generalized_stokes_rhs_fh, physqrow=[1], physqcol=[1], &
          coefficients=coefficients, buildmatrix=.false. )

        rhsd1%u = rhsd1%u + rhsd%u

    else ! redundant

    end if

    call check ( sysmatrix )

    call add_effect_of_essential_to_rhs ( problem1, sysmatrix, sol, rhsd1 )

    call solve_system_ma57 ( sysmatrix, rhsd1, sol, &
      solver_options=solver_options_ma57  )

    call delete ( sysmatrix )

  end subroutine build_solve_system

  subroutine build_solve_system2


   call fill_sysvector ( mesh, problem2, sol2, curve1=5 , physq=1, degfd= 1, &
     value= up(1) )

   call fill_sysvector ( mesh, problem2, sol2, curve1=5 , physq=1, degfd= 2, &
     value= up(2) )


!   Stokes flow : velocity / pressure
    call build_system ( mesh, problem2, sysmatrix, rhsd2, elemsub=stokes_elem, &
      coefficients=coefficients )

    call check ( sysmatrix )

    call add_effect_of_essential_to_rhs ( problem2, sysmatrix, sol2, rhsd2 )

    call solve_system_ma57 ( sysmatrix, rhsd2, sol2, &
      solver_options=solver_options_ma57  )

    call delete ( sysmatrix )


  end subroutine build_solve_system2

   subroutine build_solve_system3

!   Stokes flow : velocity / pressure
    call build_system ( mesh, problem1, sysmatrix, rhsd1, elemsub=stokes_elem, &
      coefficients=coefficients )

    rhsd1%u = rhsd%u

!   constraint on particle boundary
    call build_system_constraint ( mesh, problem1, sysmatrix, rhsd1, &
      constraint1=1, elemsub=elementc, addmatvec=.true., &
      coefficients=coefficients, diagonal = .true. )

    call check ( sysmatrix )

    call add_effect_of_essential_to_rhs ( problem1, sysmatrix, sol, rhsd1 )

    call solve_system_ma57 ( sysmatrix, rhsd1, sol, &
      solver_options=solver_options_ma57  )

    call delete ( sysmatrix )

  end subroutine build_solve_system3


  subroutine compute_drag

!   pressure
    call create_vector ( problem2, pressure, vec=3 )
    call derive_vector ( mesh, problem2, pressure, elemsub=stokes_pressure, &
      coefficients=coefficients, oldvectors=oldvectors3, elcurves=[5] )

!   viscous stress
    call create_vector ( problem2, stress_tensor, vec=4 )
    call derive_vector ( mesh, problem2,stress_tensor, &
      elemsub=stokes_stress_tensor, coefficients=coefficients,&
      oldvectors=oldvectors3, elcurves=[5] )

    oldvectors2%v(1)%p => stress_tensor
    oldvectors2%v(2)%p => pressure

!   integrate drag force
    call integrate_boundary_elements ( mesh, problem2, dragv, &
      elemsub=stokes_drag, curve=5, coefficients=coefficients, &
      oldvectors=oldvectors2 )

   call delete( pressure, stress_tensor)

  end subroutine compute_drag

! delete old problem

  subroutine delete_old_problem

    call delete ( problem1, problem2 )
    call delete ( problem_pois )
    call delete ( input_probdef1, input_probdef2 )
    call delete ( mesh )
    call delete ( sol, sol2 )
    call delete ( rhsd, rhsd1, rhsd2 )
    call delete ( oldvectors, oldvectors2, oldvectors3 )

!   deallocate area and aspect ratio arrays
    deallocate ( init_aspect_ratio, aspect_ratio )
    deallocate ( init_area, areav )

  end subroutine delete_old_problem

end program fh_2
